import React,{useEffect,useMemo,useState}from'react';
import{CheckSquare,Clock,AlertTriangle,FlaskConical,MessageSquare,Plus,ChevronRight,User,Filter}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{ClinicalWorkflowService}from'../../services/clinicalWorkflowService';
import{AuthorizationService}from'../../services/authorizationService';
import type{ClinicalTask,Patient}from'../../types/clinical';

const priorityClass=(p:ClinicalTask['priority'])=>p==='stat'?'bg-rose-500/10 text-rose-500':p==='urgent'?'bg-amber-500/10 text-amber-500':'bg-slate-100 dark:bg-slate-800 text-slate-500';
const isOverdue=(t:ClinicalTask)=>!!t.dueDateTime&&t.status!=='completed'&&t.status!=='cancelled'&&new Date(t.dueDateTime).getTime()<Date.now();

export const TasksCenterView:React.FC=()=>{
 const{currentUser,patients,beds,setCurrentPatientId,setCurrentView,showToast}=useApp();
 const[version,setVersion]=useState(0);const[filter,setFilter]=useState<'all'|'pending'|'completed'|'overdue'>('pending');const[priority,setPriority]=useState<'all'|'stat'|'urgent'|'routine'>('all');
 useEffect(()=>{let active=true;void ClinicalWorkflowService.hydrateTasks().finally(()=>{if(active)setVersion(v=>v+1)});const h=()=>setVersion(v=>v+1);window.addEventListener('cardiovault-task-updated',h);window.addEventListener('cardiovault-data-restored',h);return()=>{active=false;window.removeEventListener('cardiovault-task-updated',h);window.removeEventListener('cardiovault-data-restored',h)}},[]);
 const authorized=useMemo(()=>AuthorizationService.filterAuthorizedPatients<Patient>(patients.filter(p=>!p.isArchived),currentUser),[patients,currentUser]);
 const allowed=new Set(authorized.map(p=>p.id));
 const tasks=useMemo(()=>ClinicalWorkflowService.getTasks(),[version]);
 const clinicalActions=useMemo(()=>{
  const rows:{id:string;kind:'investigation'|'consult';patientId:string;patientName:string;unitId:string;title:string;status:string;priority:'routine'|'urgent'|'stat';createdAt:string;assignedTo?:string;description?:string}[]=[];
  authorized.forEach(p=>{
   (p.investigations||[]).filter(i=>i.status==='ordered'||i.status==='pending'||i.status==='available').forEach(i=>rows.push({id:'inv-'+i.id,kind:'investigation',patientId:p.id,patientName:p.fullName,unitId:p.unitId,title:'Order Investigation',status:i.status,priority:i.flag==='critical'?'stat':'urgent',createdAt:i.orderedAt,description:i.title}));
   (p.consultations||[]).filter(c=>c.status!=='Completed').forEach(c=>rows.push({id:'consult-'+c.id,kind:'consult',patientId:p.id,patientName:p.fullName,unitId:p.unitId,title:'Request Consult',status:c.status,priority:c.priority,createdAt:c.requestedAt,assignedTo:c.assignedClinician,description:c.specialty}));
  });return rows;
 },[authorized]);
 const pendingActions=clinicalActions.filter(x=>x.status!=='reviewed'&&x.status!=='Completed');
 const allCount=tasks.filter(t=>t.status!=='cancelled').length+pendingActions.length;
 const pendingCount=tasks.filter(t=>t.status==='pending'||t.status==='in_progress').length+pendingActions.length;
 const overdueCount=tasks.filter(isOverdue).length;
 const filteredTasks=tasks.filter(t=>filter==='all'?true:filter==='completed'?t.status==='completed':filter==='overdue'?isOverdue(t):t.status==='pending'||t.status==='in_progress').filter(t=>priority==='all'||t.priority===priority);
 const openPatient=(id:string)=>{setCurrentPatientId(id);setCurrentView('patient')};
 const complete=(id:string)=>{ClinicalWorkflowService.updateTaskStatus(id,'completed',currentUser);showToast('Task completed.','success')};
 return <div className="max-w-5xl mx-auto w-full px-3 sm:px-6 py-5 pb-24 space-y-4">
  <div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wider text-cyan-500">Clinical Work Queue</div><h1 className="text-2xl font-black">Tasks</h1><p className="text-xs text-slate-500">Your actionable clinical work, investigations and consults.</p></div><button onClick={()=>setCurrentView('home')} className="text-xs font-bold text-cyan-500">Home</button></div>
  <div className="grid grid-cols-3 gap-2"><div className="p-3 rounded-2xl bg-white dark:bg-slate-900 border"><div className="text-[9px] uppercase font-black text-slate-400">Pending</div><div className="text-2xl font-black text-cyan-500">{pendingCount}</div></div><div className="p-3 rounded-2xl bg-white dark:bg-slate-900 border"><div className="text-[9px] uppercase font-black text-slate-400">Overdue</div><div className="text-2xl font-black text-rose-500">{overdueCount}</div></div><div className="p-3 rounded-2xl bg-white dark:bg-slate-900 border"><div className="text-[9px] uppercase font-black text-slate-400">Total</div><div className="text-2xl font-black">{allCount}</div></div></div>
  <div className="flex gap-2 overflow-x-auto pb-1">{(['pending','overdue','completed','all'] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-3 py-1.5 rounded-xl text-[10px] font-bold whitespace-nowrap ${filter===f?'bg-cyan-500 text-slate-950':'bg-white dark:bg-slate-900 border text-slate-500'}`}>{f}</button>)}<select value={priority} onChange={e=>setPriority(e.target.value as any)} className="px-3 py-1.5 rounded-xl text-[10px] bg-white dark:bg-slate-900 border"><option value="all">All priority</option><option value="stat">STAT</option><option value="urgent">Urgent</option><option value="routine">Routine</option></select></div>
  <div className="rounded-2xl bg-white dark:bg-slate-900 border p-3 space-y-2"><div className="flex items-center justify-between"><h2 className="text-sm font-black flex items-center gap-2"><CheckSquare className="w-4 h-4 text-cyan-500"/>My Tasks</h2><span className="text-[10px] text-slate-400">{filteredTasks.length}</span></div>{filteredTasks.map(t=><div key={t.id} className={`p-3 rounded-xl border flex items-start gap-3 ${isOverdue(t)?'border-rose-300 bg-rose-50/40 dark:bg-rose-950/10':'border-slate-200 dark:border-slate-800'}`}><button onClick={()=>complete(t.id)} className={`w-5 h-5 mt-0.5 rounded-md border shrink-0 flex items-center justify-center ${t.status==='completed'?'bg-emerald-500 border-emerald-500':'hover:border-cyan-500'}`}>{t.status==='completed'?'✓':''}</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="text-xs truncate">{t.title}</b><span className={`px-1.5 py-0.5 rounded text-[8px] font-black uppercase ${priorityClass(t.priority)}`}>{t.priority}</span>{isOverdue(t)&&<span className="text-[8px] font-black text-rose-500">OVERDUE</span>}</div><div className="text-[10px] text-slate-400 mt-1">{t.patientName||'Unit task'} • Assigned to {t.assignedTo||t.assignedRole||'Team'}</div>{t.dueDateTime&&<div className="text-[9px] text-slate-400 mt-1"><Clock className="inline w-3 h-3 mr-1"/>{new Date(t.dueDateTime).toLocaleString()}</div>}</div>{t.patientId&&<button onClick={()=>openPatient(t.patientId!)} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><ChevronRight className="w-4 h-4"/></button>}</div>)}{!filteredTasks.length&&<div className="p-8 text-center text-xs text-slate-400">No tasks in this filter.</div>}</div>
  <div className="rounded-2xl bg-white dark:bg-slate-900 border p-3 space-y-2"><div className="flex items-center justify-between"><h2 className="text-sm font-black flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-500"/>Clinical Actions</h2><span className="text-[10px] text-slate-400">Always visible in Tasks</span></div>{pendingActions.map(a=><button key={a.id} onClick={()=>openPatient(a.patientId)} className="w-full text-left p-3 rounded-xl border border-slate-200 dark:border-slate-800 hover:border-cyan-500/50 flex items-center gap-3"><div className={`w-9 h-9 rounded-xl flex items-center justify-center ${a.kind==='investigation'?'bg-indigo-500/10 text-indigo-500':'bg-violet-500/10 text-violet-500'}`}>{a.kind==='investigation'?<FlaskConical className="w-4 h-4"/>:<MessageSquare className="w-4 h-4"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="text-xs">{a.title}</b><span className={`px-1.5 py-0.5 rounded text-[8px] font-black uppercase ${priorityClass(a.priority)}`}>{a.priority}</span></div><div className="text-[10px] text-slate-400 mt-1">{a.patientName} • {a.description||'Clinical action'} • {a.status}</div></div><ChevronRight className="w-4 h-4 text-slate-400"/></button>)}{!pendingActions.length&&<div className="p-6 text-center text-xs text-slate-400">No pending investigations or consults.</div>}</div>
 </div>
};