import test from 'node:test';import assert from 'node:assert/strict';import{buildPreviousAdmissionPatient,createReadOnlyMutationOverrides,consumeOpenPreviousAdmissionId,PREVIOUS_ADMISSION_OPEN_KEY}from'../src/services/previousAdmissionPatient.ts';import type{Patient,PastAdmission}from'../src/types/clinical.ts';
const source={id:'live-1',mrn:'M1',fullName:'Test Patient',age:55,sex:'Male',unitId:'u1',bedId:'b1',status:'Stable',admissionDate:'2026-10-08',admissionTime:'10:00',primaryDiagnosis:'Current ACS',secondaryDiagnoses:[],allergies:[],codeStatus:'Full Code',pastAdmissions:[],clinicalSummary:{chiefComplaint:'Current'},cardiovascularHistory:{hypertension:false,diabetes:false,dyslipidemia:false,cad:false,previousMI:false,heartFailure:false,arrhythmias:false,valvularDisease:false,previousPCI:false,previousCABG:false,previousStroke:false,pvd:false,smoking:false,alcohol:false,previousAdmissions:'',previousICU:'',other:''},vitalsHistory:[{id:'current-v'}],fluidRecords:[],examination:{},ecgRecords:[],cardiology:{},medications:[],infusions:[],ventilator:{},imaging:[],labs:[],procedures:[],calculatorResults:[],progressNotes:[],auditTrail:[{id:'current-audit',timestamp:'2026-10-08T10:00:00Z',action:'current',fields:['patient']}],handover:{situation:'CURRENT HANDOVER',background:'',assessment:'',recommendation:''},aiSummary:{summary:'CURRENT AI',keyPoints:[],generatedAt:'',savedAt:'',savedByUid:'',inputFingerprint:'',model:''}} as Patient;
const snapshot={unitId:'u1',bedId:'b1',status:'Stable',admissionDate:'2026-10-01',admissionTime:'10:00',primaryDiagnosis:'Old ACS',secondaryDiagnoses:[],allergies:[],codeStatus:'Full Code',isArchived:true,archiveReason:'Discharged Home',archiveDate:'2026-10-05',currentAdmissionStartedAt:'2026-10-01T09:00:00+03:00',clinicalSummary:{chiefComplaint:'OLD'},cardiovascularHistory:{hypertension:false,diabetes:false,dyslipidemia:false,cad:false,previousMI:false,heartFailure:false,arrhythmias:false,valvularDisease:false,previousPCI:false,previousCABG:false,previousStroke:false,pvd:false,smoking:false,alcohol:false,previousAdmissions:'',previousICU:'',other:''},handover:{situation:'OLD HANDOVER',background:'',assessment:'',recommendation:''},vitalsHistory:[{id:'old-v',timestamp:'2026-10-01T10:00:00+03:00'}],fluidRecords:[],hemodynamicHistory:[],fluidIntakeHistory:[],urineOutputHistory:[],examination:{},ecgRecords:[],cardiology:{},medications:[],infusions:[],ventilator:{},imaging:[],labs:[],labResults:[],procedures:[],calculatorResults:[],progressNotes:[],problems:[],tasks:[],investigations:[],medicationAdministrations:[],consultations:[],shiftHandovers:[],corrections:[],timelineEvents:[],attendedClinician:'Old Doctor',attendedNurse:'Old Nurse'} as any;
const admission={id:'e1',admissionDate:'2026-10-01',dischargeDate:'2026-10-05',unitName:'CCU',dischargeReason:'Discharged Home',dischargeSummary:'Old summary',primaryDiagnosis:'Old ACS',episodeSnapshot:snapshot} as PastAdmission;
test('viewer uses identity plus snapshot over an empty clinical shape',()=>{const viewer=buildPreviousAdmissionPatient(source,admission);assert.equal(viewer.id,'live-1::e1');assert.equal(viewer.mrn,source.mrn);assert.equal(viewer.fullName,source.fullName);assert.equal(viewer.primaryDiagnosis,'Old ACS');assert.equal(viewer.vitalsHistory[0].id,'old-v');assert.equal(viewer.currentAdmissionStartedAt,snapshot.currentAdmissionStartedAt);assert.equal(viewer.handover?.situation,'OLD HANDOVER');assert.equal(viewer.aiSummary,undefined);assert.deepEqual(viewer.auditTrail,[]);});
test('old vitals are visible to Now filtering through the old admission start',()=>{const viewer=buildPreviousAdmissionPatient(source,admission);assert.equal(viewer.currentAdmissionStartedAt,'2026-10-01T09:00:00+03:00');assert.equal(viewer.vitalsHistory[0].id,'old-v');assert.equal(Date.parse(viewer.vitalsHistory[0].timestamp)>=Date.parse(viewer.currentAdmissionStartedAt!),true);});
test('current handover and ai summary never leak into previous viewer',()=>{const viewer=buildPreviousAdmissionPatient(source,admission);assert.notEqual(viewer.handover?.situation,'CURRENT HANDOVER');assert.equal(viewer.aiSummary,undefined);});
test('read-only mutations are no-ops and snapshot remains unchanged',()=>{const original=JSON.stringify(admission.episodeSnapshot);const toasts:string[]=[];const app={units:[],beds:[],setCurrentView:()=>{},setCurrentUnitId:()=>{},setCurrentPatientId:()=>{},setActivePatientSection:()=>{},setIsSearchOpen:()=>{},dismissToast:()=>{},getBedsByUnit:()=>[],getUnitById:()=>undefined} as any;const viewer=buildPreviousAdmissionPatient(source,admission);const overrides=createReadOnlyMutationOverrides(app,(m)=>{toasts.push(m)},viewer);overrides.updatePatient(viewer.id,{primaryDiagnosis:'MUTATED'});overrides.deletePatientPermanently(viewer.id);assert.equal(viewer.primaryDiagnosis,'Old ACS');assert.equal(JSON.stringify(admission.episodeSnapshot),original);assert.equal(toasts.length,2);});
const patientResetFixture:any={
  id:'p-reset',mrn:'MRN-RESET',fullName:'Fixture Patient',name:'Fixture Alias',age:55,sex:'Male',gender:'male',weight:80,height:175,photoUrl:'photo://old',
  unitId:'unit-old',bedId:'bed-old',bedNumber:'B-01',departmentId:'dept-old',status:'Critical',admissionDate:'2026-10-01',admissionTime:'09:00',primaryDiagnosis:'Current ACS - isolation check',diagnosis:'Old diagnosis',secondaryDiagnoses:['Old secondary'],allergies:['Old allergy'],codeStatus:'Full Code',
  isArchived:true,archiveReason:'Discharged Home',archiveDate:'2026-10-08',currentAdmissionStartedAt:'2026-10-01T09:00:00+03:00',additionalConditions:['Previous admission condition'],dischargeSummary:'Old discharge',
  pastAdmissions:[],
  clinicalSummary:{chiefComplaint:'Old complaint',hpi:'Old HPI',pmh:['HTN'],psh:['PCI'],drugHistory:'Old drugs',allergies:['Old allergy'],familyHistory:'Old family',socialHistory:'Old social'},
  cardiovascularHistory:{hypertension:true,diabetes:true,dyslipidemia:true,cad:true,previousMI:true,heartFailure:true,arrhythmias:true,valvularDisease:true,previousPCI:true,previousCABG:true,previousStroke:true,pvd:true,smoking:true,alcohol:true,previousAdmissions:'Old admissions',previousICU:'Old ICU',other:'Old other'},
  handover:{situation:'Old situation',background:'Old background',assessment:'Old assessment',recommendation:'Old recommendation',updatedAt:'old'},
  vitalsHistory:[{id:'v-old'}],fluidRecords:[{id:'f-old'}],hemodynamicHistory:[{id:'h-old'}],fluidIntakeHistory:[{id:'fi-old'}],urineOutputHistory:[{id:'u-old'}],
  examination:{general:{appearance:'Old',consciousness:'Old',distress:'Old',hydration:'Old',pallor:true,cyanosis:true,jaundice:true,edema:'Old'},cardiovascular:{jvp:'Old',heartSounds:'Old',murmurs:'Old',peripheralPulses:'Old',edema:'Old',perfusion:'Old'},respiratory:{chestExam:'Old',airEntry:'Old',addedSounds:'Old',workOfBreathing:'Old'},abdomen:{inspection:'Old',palpation:'Old',tenderness:'Old',organomegaly:'Old',ascites:'Old'},neurological:{consciousness:'Old',gcs:'Old',pupils:'Old',motor:'Old',sensory:'Old',reflexes:'Old'},extremities:{pulses:'Old',edema:'Old',temp:'Old',perfusion:'Old'},customFields:[{label:'Old',value:'Old'}]},
  ecgRecords:[{id:'ecg-old'}],cardiology:{rhythm:'Old',heartRate:100,bp:'120/80',heartFailureStatus:'Old',nyha:'Old',killip:'Old',congestion:'Old',perfusion:'Old',echo:{lvDimensions:'Old',lvFunction:'Old',rvFunction:'Old',rwma:'Old',la:'Old',ra:'Old',mr:'Old',ar:'Old',as:'Old',ms:'Old',tr:'Old',pr:'Old',ivc:'Old',pericardium:'Old',otherFindings:'Old'},biomarkers:{troponin:'Old',ckmb:'Old',bnp:'Old',ntProBnp:'Old'},coronary:{cath:'Old',coronaryFindings:'Old',pci:'Old',stent:'Old',cabg:'Old'},antithrombotic:{antiplatelet:'Old',anticoagulation:'Old',thrombolysis:'Old'}},
  medications:[{id:'med-old',drug:'Old drug',dose:'10',route:'PO',frequency:'OD'}],infusions:[{id:'inf-old',drugName:'Old infusion',dose:1,unit:'mg',rateMlHr:10}],ventilator:{mode:'Old',fio2:50,peep:5,tidalVolume:500,rr:16,pressureSupport:5,inspiratoryPressure:10,ieRatio:'1:2',peakPressure:20,plateauPressure:15,meanAirwayPressure:10,spo2:98,etco2:35,compliance:40,resistance:10,abgHistory:[{id:'abg-old'}]},
  imaging:[{id:'img-old'}],labs:[{date:'2026-10-08'}],labResults:[{id:'lab-old',name:'Hb',value:10,unit:'g/dL'}],procedures:[{id:'proc-old'}],calculatorResults:[{id:'calc-old'}],progressNotes:[{id:'note-old'}],
  auditTrail:[{id:'audit-old',timestamp:'2026-10-08',action:'old',fields:['old']}],aiSummary:{summary:'Old AI',keyPoints:['Old'],generatedAt:'old',savedAt:'old',savedByUid:'old',inputFingerprint:'old',model:'old'},
  problems:[{id:'problem-old'}],tasks:[{id:'task-old'}],investigations:[{id:'invest-old'}],medicationAdministrations:[{id:'ma-old'}],consultations:[{id:'consult-old'}],shiftHandovers:[{id:'sh-old'}],corrections:[{id:'corr-old'}],timelineEvents:[{id:'timeline-old'}],
  attendedClinician:'Old clinician',attendedNurse:'Old nurse'
};
const fullCurrent:Patient=patientResetFixture;
const snapshotWithDistinctEpisode={...snapshot,additionalConditions:['OLD CONDITION'],labResults:[{id:'old-lab',name:'Hb',value:9,unit:'g/dL'}],bedNumber:'OLD-BED',diagnosis:'Old diagnosis'};
const fullAdmission={...admission,episodeSnapshot:snapshotWithDistinctEpisode};
test('viewer isolates every episode key and preserves current identity only',()=>{const original=structuredClone(fullCurrent);const viewer=buildPreviousAdmissionPatient(fullCurrent,fullAdmission);assert.equal(viewer.id,`${fullCurrent.id}::${fullAdmission.id}`);for(const key of ['mrn','fullName','name','age','sex','gender','weight','height','photoUrl'])assert.deepEqual(viewer[key],fullCurrent[key],key);assert.equal(viewer.primaryDiagnosis,'Old ACS');assert.equal(viewer.diagnosis,'Old diagnosis');assert.deepEqual(viewer.additionalConditions,['OLD CONDITION']);assert.deepEqual(viewer.labResults,snapshotWithDistinctEpisode.labResults);assert.notEqual(viewer.primaryDiagnosis,fullCurrent.primaryDiagnosis);assert.deepEqual(viewer.pastAdmissions,[]);assert.deepEqual(viewer.auditTrail,[]);assert.equal(viewer.aiSummary,undefined);assert.deepEqual(fullCurrent,original);});
test('snapshot-less admission gets the complete empty episode shape without current-patient fallback',()=>{const original=structuredClone(fullCurrent);const noSnapshot={...fullAdmission,episodeSnapshot:undefined};const viewer=buildPreviousAdmissionPatient(fullCurrent,noSnapshot);assert.equal(viewer.id,`${fullCurrent.id}::${fullAdmission.id}`);assert.equal(viewer.mrn,fullCurrent.mrn);assert.equal(viewer.fullName,fullCurrent.fullName);assert.equal(viewer.primaryDiagnosis,'');assert.deepEqual(viewer.additionalConditions,[]);assert.deepEqual(viewer.labResults,[]);assert.equal(viewer.status,'Not documented');assert.equal(viewer.codeStatus,'Not documented');assert.deepEqual(viewer.pastAdmissions,[]);assert.deepEqual(viewer.auditTrail,[]);assert.equal(viewer.aiSummary,undefined);assert.deepEqual(fullCurrent,original);});

const memStore=(initial?:Record<string,string>)=>{const m:Record<string,string>={...(initial||{})};return{getItem:(k:string)=> (k in m?m[k]:null),removeItem:(k:string)=>{delete m[k];},peek:()=>({...m})};};
test('archive deep-link opens a matching previous admission and clears the key',()=>{const s=memStore({[PREVIOUS_ADMISSION_OPEN_KEY]:'e1'});const id=consumeOpenPreviousAdmissionId({id:'p1',pastAdmissions:[{id:'e1'}]} as any,s);assert.equal(id,'e1');assert.deepEqual(s.peek(),{});});
test('archive deep-link ignores unknown admission ids and clears the key',()=>{const s=memStore({[PREVIOUS_ADMISSION_OPEN_KEY]:'nope'});const id=consumeOpenPreviousAdmissionId({id:'p1',pastAdmissions:[{id:'e1'}]} as any,s);assert.equal(id,null);assert.deepEqual(s.peek(),{});});
test('archive deep-link handles missing key and missing history',()=>{const s=memStore();assert.equal(consumeOpenPreviousAdmissionId({id:'p1'} as any,s),null);assert.equal(consumeOpenPreviousAdmissionId({id:'p1',pastAdmissions:undefined} as any,memStore({[PREVIOUS_ADMISSION_OPEN_KEY]:'e1'})),null);});
