import type {AdmissionEpisodeSnapshot,Patient,PastAdmission} from '../types/clinical';
export type PatientKeyClass='identity'|'assigned'|'episode'|'history'|'meta';
export const PATIENT_KEY_CLASS:Record<keyof Patient,PatientKeyClass>={
  id:'identity',mrn:'identity',fullName:'identity',name:'identity',age:'identity',sex:'identity',gender:'identity',weight:'identity',height:'identity',photoUrl:'identity',
  unitId:'assigned',bedId:'assigned',departmentId:'assigned',admissionDate:'assigned',admissionTime:'assigned',currentAdmissionStartedAt:'assigned',status:'assigned',codeStatus:'assigned',
  bedNumber:'episode',primaryDiagnosis:'episode',diagnosis:'episode',secondaryDiagnoses:'episode',allergies:'episode',isArchived:'episode',archiveReason:'episode',archiveDate:'episode',additionalConditions:'episode',dischargeSummary:'episode',
  clinicalSummary:'episode',cardiovascularHistory:'episode',handover:'episode',vitalsHistory:'episode',fluidRecords:'episode',hemodynamicHistory:'episode',fluidIntakeHistory:'episode',urineOutputHistory:'episode',
  examination:'episode',ecgRecords:'episode',cardiology:'episode',medications:'episode',infusions:'episode',ventilator:'episode',imaging:'episode',labs:'episode',labResults:'episode',procedures:'episode',
  calculatorResults:'episode',progressNotes:'episode',aiSummary:'episode',problems:'episode',tasks:'episode',investigations:'episode',medicationAdministrations:'episode',consultations:'episode',shiftHandovers:'episode',
  corrections:'episode',timelineEvents:'episode',attendedClinician:'episode',attendedNurse:'episode',
  pastAdmissions:'history',auditTrail:'meta'
};
export const MAX_PATIENT_DOCUMENT_BYTES=700*1024;
export const serializedBytes=(value:unknown):number=>new TextEncoder().encode(JSON.stringify(value)).byteLength;
export const cloneDefined=<T>(value:T):T=>{
  if(Array.isArray(value))return value.filter(item=>item!==undefined).map(item=>cloneDefined(item)) as T;
  if(value&&typeof value==='object'){
    const out:Record<string,unknown>={};
    for(const [key,child] of Object.entries(value as Record<string,unknown>))if(child!==undefined)out[key]=cloneDefined(child);
    return out as T;
  }
  return value;
};
export const normalizeDischargeReason=(value:unknown):PastAdmission['dischargeReason']=>value==='Discharged Home'||value==='Transferred'||value==='Deceased'||value==='Other'?value:'Other';
export class AdmissionHistoryTooLargeError extends Error{constructor(){super('Previous-admission history is too large. Export the previous admission as PDF, then contact the administrator.');this.name='AdmissionHistoryTooLargeError';}}
const sameLightweight=(e:PastAdmission,p:Patient)=>!e.episodeSnapshot&&e.admissionDate===p.admissionDate&&e.dischargeDate===p.archiveDate;
export const createAdmissionEpisodeSnapshot=(p:Patient,unitName:string,episodeId:string):AdmissionEpisodeSnapshot=>{const{id:_,mrn:__,fullName:___,name:____,age:_____,sex:______,gender:_______,weight:________,height:_________,photoUrl:__________,pastAdmissions:___________,auditTrail:____________,aiSummary:_____________,...episodeData}=p;return{...cloneDefined(episodeData),episodeId,unitName,dischargeDate:p.archiveDate,dischargeReason:normalizeDischargeReason(p.archiveReason),dischargeSummary:p.dischargeSummary};};
export const makePastAdmission=(p:Patient,unitName:string,id:string,dischargeDate:string,dischargeReason:PastAdmission['dischargeReason'],summary:string):PastAdmission=>({id,admissionDate:p.admissionDate,dischargeDate,unitName,dischargeReason,dischargeSummary:summary,primaryDiagnosis:p.primaryDiagnosis});
export const prepareDischargedPatient=(p:Patient,unitName:string,id:string,dischargeDate:string,reason:string,summary:string):Patient=>cloneDefined({...p,isArchived:true,archiveReason:reason,archiveDate:dischargeDate,pastAdmissions:[makePastAdmission(p,unitName,id,dischargeDate,normalizeDischargeReason(reason),summary),...(p.pastAdmissions||[])],dischargeSummary:summary||''});
export const upsertReadmissionHistory=(history:PastAdmission[],source:Patient,unitName:string):PastAdmission[]=>{const i=history.findIndex(e=>sameLightweight(e,source));const id=i>=0?history[i].id:'adm-'+Date.now();const full={...makePastAdmission(source,unitName,id,source.archiveDate||'',normalizeDischargeReason(source.archiveReason),source.dischargeSummary||''),episodeSnapshot:createAdmissionEpisodeSnapshot(source,unitName,id)};return i<0?[full,...history]:history.map((e,n)=>n===i?full:e);};
const stripSnapshotExcluded=(p:Patient)=>{const{id:_,mrn:__,fullName:___,name:____,age:_____,sex:______,gender:_______,weight:________,height:_________,photoUrl:__________,pastAdmissions:___________,auditTrail:____________,aiSummary:_____________,dischargeSummary:______________,...rest}=p;return rest};
export const verifyAdmissionSnapshot=(p:Patient,s:AdmissionEpisodeSnapshot):boolean=>{const{episodeId:_,unitName:__,dischargeDate:___,dischargeReason:____,dischargeSummary:_____,...sd}=s;const pd=stripSnapshotExcluded(p);return JSON.stringify(sd)===JSON.stringify(pd);};
export const emptyExam=():Patient['examination']=>({general:{appearance:'',consciousness:'',distress:'',hydration:'',pallor:false,cyanosis:false,jaundice:false,edema:''},cardiovascular:{jvp:'',heartSounds:'',murmurs:'',peripheralPulses:'',edema:'',perfusion:''},respiratory:{chestExam:'',airEntry:'',addedSounds:'',workOfBreathing:''},abdomen:{inspection:'',palpation:'',tenderness:'',organomegaly:'',ascites:''},neurological:{consciousness:'',gcs:'',pupils:'',motor:'',sensory:'',reflexes:''},extremities:{pulses:'',edema:'',temp:'',perfusion:''},customFields:[]});
export const emptyCV=():Patient['cardiovascularHistory']=>({hypertension:false,diabetes:false,dyslipidemia:false,cad:false,previousMI:false,heartFailure:false,arrhythmias:false,valvularDisease:false,previousPCI:false,previousCABG:false,previousStroke:false,pvd:false,smoking:false,alcohol:false,previousAdmissions:'',previousICU:'',other:''});
export const emptyCardio=():Patient['cardiology']=>({rhythm:'',heartRate:0,bp:'',heartFailureStatus:'',nyha:'',killip:'',congestion:'',perfusion:'',echo:{lvDimensions:'',lvFunction:'',rvFunction:'',rwma:'',la:'',ra:'',mr:'',ar:'',as:'',ms:'',tr:'',pr:'',ivc:'',pericardium:'',otherFindings:''},biomarkers:{troponin:'',ckmb:'',bnp:'',ntProBnp:''},coronary:{cath:'',coronaryFindings:'',pci:'',stent:'',cabg:''},antithrombotic:{antiplatelet:'',anticoagulation:'',thrombolysis:''}});
export const emptyVent=():Patient['ventilator']=>({mode:'',fio2:0,peep:0,tidalVolume:0,rr:0,pressureSupport:0,inspiratoryPressure:0,ieRatio:'',peakPressure:0,plateauPressure:0,meanAirwayPressure:0,spo2:0,etco2:0,compliance:0,resistance:0,abgHistory:[]});
export const createEmptyPatientShape=():Patient=>({id:'',mrn:'',fullName:'',name:undefined,age:0,sex:'Other',gender:undefined,weight:0,height:0,photoUrl:undefined,unitId:'',bedId:'',bedNumber:undefined,departmentId:undefined,status:'Not documented',admissionDate:'',admissionTime:'',primaryDiagnosis:'',diagnosis:undefined,secondaryDiagnoses:[],allergies:[],codeStatus:'Not documented',isArchived:false,archiveReason:undefined,archiveDate:undefined,currentAdmissionStartedAt:undefined,additionalConditions:[],dischargeSummary:undefined,pastAdmissions:[],clinicalSummary:{chiefComplaint:'',hpi:'',pmh:[],psh:[],drugHistory:'',allergies:[],familyHistory:'',socialHistory:''},cardiovascularHistory:emptyCV(),handover:undefined,vitalsHistory:[],fluidRecords:[],hemodynamicHistory:[],fluidIntakeHistory:[],urineOutputHistory:[],examination:emptyExam(),ecgRecords:[],cardiology:emptyCardio(),medications:[],infusions:[],ventilator:emptyVent(),imaging:[],labs:[],labResults:[],procedures:[],calculatorResults:[],progressNotes:[],auditTrail:[],aiSummary:undefined,problems:[],tasks:[],investigations:[],medicationAdministrations:[],consultations:[],shiftHandovers:[],corrections:[],timelineEvents:[],attendedClinician:undefined,attendedNurse:undefined});
export const pickIdentityFields=(patient:Patient):Partial<Patient>=>{const out:Partial<Patient>={};for(const key of Object.keys(PATIENT_KEY_CLASS) as Array<keyof Patient>)if(PATIENT_KEY_CLASS[key]==='identity')out[key]=patient[key] as never;return out;};
export const resetForNewAdmission=(p:Patient,unitId:string,bedId:string,unitName:string,admissionDate:string,admissionTime:string,currentAdmissionStartedAt:string,departmentId?:string):Patient=>{const history=upsertReadmissionHistory(p.pastAdmissions||[],p,unitName);const next=cloneDefined<Patient>({...createEmptyPatientShape(),...pickIdentityFields(p),unitId,bedId,departmentId,status:'Not documented',admissionDate,admissionTime,currentAdmissionStartedAt,pastAdmissions:history,auditTrail:p.auditTrail});if(serializedBytes(next)>MAX_PATIENT_DOCUMENT_BYTES)throw new AdmissionHistoryTooLargeError();return next;};