import type {AdmissionEpisodeSnapshot,Patient,PastAdmission} from '../types/clinical';
export const MAX_PATIENT_DOCUMENT_BYTES=700*1024;
export const serializedBytes=(value:unknown):number=>new TextEncoder().encode(JSON.stringify(value)).byteLength;
export const normalizeDischargeReason=(value:unknown):PastAdmission['dischargeReason']=>value==='Discharged Home'||value==='Transferred'||value==='Deceased'||value==='Other'?value:'Other';
export class AdmissionHistoryTooLargeError extends Error{constructor(){super('Previous-admission history is too large. Export the previous admission as PDF, then contact the administrator.');this.name='AdmissionHistoryTooLargeError';}}
const sameLightweight=(e:PastAdmission,p:Patient)=>!e.episodeSnapshot&&e.admissionDate===p.admissionDate&&e.dischargeDate===p.archiveDate;
export const createAdmissionEpisodeSnapshot=(p:Patient,unitName:string,episodeId:string):AdmissionEpisodeSnapshot=>{const{id:_,mrn:__,fullName:___,name:____,age:_____,sex:______,gender:_______,weight:________,height:_________,photoUrl:__________,pastAdmissions:___________,auditTrail:____________,aiSummary:_____________,...episodeData}=p;return{...structuredClone(episodeData),episodeId,unitName,dischargeDate:p.archiveDate,dischargeReason:normalizeDischargeReason(p.archiveReason),dischargeSummary:p.dischargeSummary};};
export const makePastAdmission=(p:Patient,unitName:string,id:string,dischargeDate:string,dischargeReason:PastAdmission['dischargeReason'],summary:string):PastAdmission=>({id,admissionDate:p.admissionDate,dischargeDate,unitName,dischargeReason,dischargeSummary:summary,primaryDiagnosis:p.primaryDiagnosis});
export const upsertReadmissionHistory=(history:PastAdmission[],source:Patient,unitName:string):PastAdmission[]=>{const i=history.findIndex(e=>sameLightweight(e,source));const id=i>=0?history[i].id:'adm-'+Date.now();const full={...makePastAdmission(source,unitName,id,source.archiveDate||'',normalizeDischargeReason(source.archiveReason),source.dischargeSummary||''),episodeSnapshot:createAdmissionEpisodeSnapshot(source,unitName,id)};return i<0?[full,...history]:history.map((e,n)=>n===i?full:e);};
export const verifyAdmissionSnapshot=(p:Patient,s:AdmissionEpisodeSnapshot):boolean=>{const{episodeId:_,unitName:__,dischargeDate:___,dischargeReason:____,dischargeSummary:_____,...sd}=s;const{id:______,mrn:_______,fullName:________,name:_________,age:__________,sex:___________,gender:____________,weight:_____________,height:______________,photoUrl:_______________,pastAdmissions:________________,auditTrail:_________________,aiSummary:__________________,...pd}=p;return JSON.stringify(sd)===JSON.stringify(pd);};
const emptyExam=():Patient['examination']=>({general:{appearance:'',consciousness:'',distress:'',hydration:'',pallor:false,cyanosis:false,jaundice:false,edema:''},cardiovascular:{jvp:'',heartSounds:'',murmurs:'',peripheralPulses:'',edema:'',perfusion:''},respiratory:{chestExam:'',airEntry:'',addedSounds:'',workOfBreathing:''},abdomen:{inspection:'',palpation:'',tenderness:'',organomegaly:'',ascites:''},neurological:{consciousness:'',gcs:'',pupils:'',motor:'',sensory:'',reflexes:''},extremities:{pulses:'',edema:'',temp:'',perfusion:''},customFields:[]});
const emptyCV=():Patient['cardiovascularHistory']=>({hypertension:false,diabetes:false,dyslipidemia:false,cad:false,previousMI:false,heartFailure:false,arrhythmias:false,valvularDisease:false,previousPCI:false,previousCABG:false,previousStroke:false,pvd:false,smoking:false,alcohol:false,previousAdmissions:'',previousICU:'',other:''});
const emptyCardio=():Patient['cardiology']=>({rhythm:'',heartRate:0,bp:'',heartFailureStatus:'',nyha:'',killip:'',congestion:'',perfusion:'',echo:{lvDimensions:'',lvFunction:'',rvFunction:'',rwma:'',la:'',ra:'',mr:'',ar:'',as:'',ms:'',tr:'',pr:'',ivc:'',pericardium:'',otherFindings:''},biomarkers:{troponin:'',ckmb:'',bnp:'',ntProBnp:''},coronary:{cath:'',coronaryFindings:'',pci:'',stent:'',cabg:''},antithrombotic:{antiplatelet:'',anticoagulation:'',thrombolysis:''}});
const emptyVent=():Patient['ventilator']=>({mode:'',fio2:0,peep:0,tidalVolume:0,rr:0,pressureSupport:0,inspiratoryPressure:0,ieRatio:'',peakPressure:0,plateauPressure:0,meanAirwayPressure:0,spo2:0,etco2:0,compliance:0,resistance:0,abgHistory:[]});
export const resetForNewAdmission=(p:Patient,unitId:string,bedId:string,unitName:string,admissionDate:string,admissionTime:string,currentAdmissionStartedAt:string,departmentId?:string):Patient=>{const history=upsertReadmissionHistory(p.pastAdmissions||[],p,unitName);const next:Patient={id:p.id,mrn:p.mrn,fullName:p.fullName,name:p.name,age:p.age,sex:p.sex,gender:p.gender,weight:p.weight,height:p.height,photoUrl:p.photoUrl,unitId,bedId,bedNumber:undefined,departmentId,status:'Not documented',admissionDate,admissionTime,primaryDiagnosis:'',diagnosis:undefined,secondaryDiagnoses:[],allergies:[],codeStatus:'Not documented',isArchived:false,archiveReason:undefined,archiveDate:undefined,currentAdmissionStartedAt,dischargeSummary:undefined,pastAdmissions:history,clinicalSummary:{chiefComplaint:'',hpi:'',pmh:[],psh:[],drugHistory:'',allergies:[],familyHistory:'',socialHistory:''},cardiovascularHistory:emptyCV(),handover:undefined,vitalsHistory:[],fluidRecords:[],hemodynamicHistory:[],fluidIntakeHistory:[],urineOutputHistory:[],examination:emptyExam(),ecgRecords:[],cardiology:emptyCardio(),medications:[],infusions:[],ventilator:emptyVent(),imaging:[],labs:[],labResults:[],procedures:[],calculatorResults:[],progressNotes:[],auditTrail:p.auditTrail,aiSummary:undefined,problems:[],tasks:[],investigations:[],medicationAdministrations:[],consultations:[],shiftHandovers:[],corrections:[],timelineEvents:[],attendedClinician:undefined,attendedNurse:undefined};if(serializedBytes(next)>MAX_PATIENT_DOCUMENT_BYTES)throw new AdmissionHistoryTooLargeError();return next;};