import {Capacitor} from '@capacitor/core';
import {FirebaseFirestore} from '@capacitor-firebase/firestore';
import {webDoc,webSetDoc,webGetDocs,webCollection} from './webFirebase';
import {MASTER_WORKSPACE_ID} from './workspaceAccess';
export type SharedMedicationTemplate={id:string;name:string;dose:string;route:string;frequency:string;createdAt:string;createdBy?:string};
export type SharedLabTemplate={id:string;name:string;unit:string;referenceRange?:string;min?:number;max?:number;createdAt:string;createdBy?:string};
const medKey='cardiovault_department_medication_library_v1',labKey='cardiovault_department_lab_library_v1';
const read=(k:string)=>{try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[];}catch{return[];}};
async function uid(){try{if(Capacitor.isNativePlatform()){const m=await import('@capacitor-firebase/authentication');return (await m.FirebaseAuthentication.getCurrentUser()).user?.uid||'';}const {webCurrentUser}=await import('./webFirebase');return webCurrentUser()?.uid||'';}catch{return'';}}
export async function getSharedMedicationLibrary():Promise<SharedMedicationTemplate[]>{try{let rows:any[]=[];if(Capacitor.isNativePlatform()){const r:any=await FirebaseFirestore.getCollection({reference:`workspaces/${MASTER_WORKSPACE_ID}/libraries/medications/items`});rows=(r?.snapshots||[]).map((s:any)=>s.data?.()||s.data||{});}else{const s=await webGetDocs(webCollection(`workspaces/${MASTER_WORKSPACE_ID}/libraries/medications/items`));rows=s.docs.map((d:any)=>d.data());}if(rows.length)localStorage.setItem(medKey,JSON.stringify(rows));return rows;}catch{return read(medKey);}}
export async function saveSharedMedicationTemplate(input:Omit<SharedMedicationTemplate,'id'|'createdAt'>){const row={...input,id:`medtpl-${Date.now()}`,createdAt:new Date().toISOString(),createdBy:await uid()};localStorage.setItem(medKey,JSON.stringify([...read(medKey).filter((x:any)=>x.id!==row.id),row]));try{const ref=`workspaces/${MASTER_WORKSPACE_ID}/libraries/medications/items/${row.id}`;if(Capacitor.isNativePlatform())await FirebaseFirestore.setDocument({reference:ref,data:row,merge:true});else await webSetDoc(webDoc(ref),row,{merge:true});}catch(e){console.warn('Shared medication library cloud save failed:',e);}return row;}
export async function getSharedLabLibrary():Promise<SharedLabTemplate[]>{try{let rows:any[]=[];if(Capacitor.isNativePlatform()){const r:any=await FirebaseFirestore.getCollection({reference:`workspaces/${MASTER_WORKSPACE_ID}/libraries/labs/items`});rows=(r?.snapshots||[]).map((s:any)=>s.data?.()||s.data||{});}else{const s=await webGetDocs(webCollection(`workspaces/${MASTER_WORKSPACE_ID}/libraries/labs/items`));rows=s.docs.map((d:any)=>d.data());}if(rows.length)localStorage.setItem(labKey,JSON.stringify(rows));return rows;}catch{return read(labKey);}}
export async function saveSharedLabTemplate(input:Omit<SharedLabTemplate,'id'|'createdAt'>){const row={...input,id:`labtpl-${Date.now()}`,createdAt:new Date().toISOString(),createdBy:await uid()};localStorage.setItem(labKey,JSON.stringify([...read(labKey).filter((x:any)=>x.name!==row.name),row]));try{const ref=`workspaces/${MASTER_WORKSPACE_ID}/libraries/labs/items/${row.id}`;if(Capacitor.isNativePlatform())await FirebaseFirestore.setDocument({reference:ref,data:row,merge:true});else await webSetDoc(webDoc(ref),row,{merge:true});}catch(e){console.warn('Shared lab library cloud save failed:',e);}return row;}
