import { jsPDF } from 'jspdf';

const ARABIC_RE=/[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]/;
const mmPerPx=0.2645833333;

type PdfLike=any;

function renderArabic(this:PdfLike,value:string|string[],x:number,y:number,options?:any,transform?:any,originalText?:Function){
 const fallback=()=>typeof originalText==='function'?originalText.call(this,value,x,y,options,transform):this;
 const lines=(Array.isArray(value)?value.map(String):String(value).split('\n'));
 if(!lines.some(line=>ARABIC_RE.test(line)))return fallback();
 const fontSizePt=Number(this.internal?.getFontSize?.()||10);
 const scale=3;
 const pxPerPt=96/72;
 const linePx=Math.max(18,Math.ceil(fontSizePt*pxPerPt*1.45));
 const fontInfo=this.getFont?.()||{};
 const weight=/bold/i.test(String(fontInfo.fontStyle||''))?'700':'400';
 const family='Arial, Tahoma, "Noto Naskh Arabic", sans-serif';
 const measureCanvas=document.createElement('canvas');
 const measure=measureCanvas.getContext('2d');
 if(!measure)return fallback();
 measure.font=`${weight} ${fontSizePt*pxPerPt}px ${family}`;
 const widths=lines.map(line=>Math.ceil(measure.measureText(line).width)+16);
 const widthPx=Math.max(40,...widths);
 const heightPx=Math.max(linePx,lines.length*linePx+6);
 const canvas=document.createElement('canvas');canvas.width=widthPx*scale;canvas.height=heightPx*scale;
 const ctx=canvas.getContext('2d');if(!ctx)return fallback();ctx.scale(scale,scale);ctx.font=`${weight} ${fontSizePt*pxPerPt}px ${family}`;
 const color=this.getTextColor?.();ctx.fillStyle=typeof color==='string'&&color.startsWith('#')?color:'#000000';ctx.textBaseline='alphabetic';ctx.direction='rtl';ctx.textAlign='right';
 lines.forEach((line,index)=>ctx.fillText(line,widthPx-5,linePx*(index+1)));
 const widthMm=widthPx*mmPerPx;const heightMm=(heightPx/scale)*mmPerPx;
 this.addImage(canvas.toDataURL('image/png'),'PNG',x,y-fontSizePt*0.28,widthMm,heightMm,undefined,'FAST');
 return this;
}

export function installArabicTextSupport(doc:PdfLike){
 if(!doc||doc.__cardiovaultArabicSupportInstalled)return doc;
 const original=doc.text;
 if(typeof original!=='function')return doc;
 doc.text=function(value:any,x:any,y:any,options?:any,transform?:any){return renderArabic.call(this,value,x,y,options,transform,original);};
 Object.defineProperty(doc,'__cardiovaultArabicSupportInstalled',{value:true,enumerable:false,configurable:false});
 return doc;
}

// Keep the compatibility patch for any PDF generated by code that does not explicitly install it.
try{
 const api=(jsPDF as any).API;
 if(api&&typeof api.text==='function'&&!api.__cardiovaultArabicSupportInstalled){
   const original=api.text;
   api.text=function(value:any,x:any,y:any,options?:any,transform?:any){return renderArabic.call(this,value,x,y,options,transform,original);};
   api.__cardiovaultArabicSupportInstalled=true;
 }
}catch{}
