import {Capacitor} from '@capacitor/core';
import {FirebaseAuthentication} from '@capacitor-firebase/authentication';
import {FirebaseFirestore} from '@capacitor-firebase/firestore';
export type WorkspaceRole='owner'|'view_only'|'clinical_editor';
export interface WorkspaceAccessState{workspaceId:string;role:WorkspaceRole;unitId:string|null;unitName:string|null;}
export interface UnitAccessCode{unitId:string;unitName:string;code:string;role:Exclude<WorkspaceRole,'owner'>;active:boolean;}
const ACTIVE_KEY='cardiovault_active_workspace_access_v1';const WORKSPACE_PREFIX='workspace_';
const safe=(snapshot:any):any=>{try{return typeof snapshot?.data==='function'?snapshot.data():(snapshot?.data||null);}catch{return null;}};
const uid=async():Promise<string|null>=>{if(!Capacitor.isNativePlatform())return null;try{return(await FirebaseAuthentication.getCurrentUser()).user?.uid||null;}catch{return null;}};
const ownerWorkspace=(id:string)=>`${WORKSPACE_PREFIX}${id}`;
const hash=async(value:string)=>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value.trim().toUpperCase()));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');};
const newCode=()=>{const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=new Uint8Array(10);crypto.getRandomValues(bytes);const raw=Array.from(bytes).map(b=>alphabet[b%alphabet.length]).join('');return`CV-${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8)}`;};
export const getStoredWorkspaceAccess=():WorkspaceAccessState|null=>{try{const value=JSON.parse(localStorage.getItem(ACTIVE_KEY)||'null');return value?.workspaceId?value:null;}catch{return null;}};
export const setStoredWorkspaceAccess=(state:WorkspaceAccessState|null)=>{if(state)localStorage.setItem(ACTIVE_KEY,JSON.stringify(state));else localStorage.removeItem(ACTIVE_KEY);};
export async function ensureOwnerWorkspace():Promise<WorkspaceAccessState|null>{const id=await uid();if(!id)return null;const workspaceId=ownerWorkspace(id);try{const result:any=await FirebaseFirestore.getDocument({reference:`workspaces/${workspaceId}`});const data=safe(result?.snapshot);if(data?.ownerUid===id){const state={workspaceId,role:'owner' as const,unitId:null,unitName:null};setStoredWorkspaceAccess(state);return state;}return null;}catch{return null;}}
export async function redeemUnitAccessCode(raw:string):Promise<WorkspaceAccessState>{const id=await uid();if(!id)throw new Error('A Firebase account must be signed in before entering an access code.');const code=raw.trim().toUpperCase();if(code.length<10)throw new Error('Invalid Unit Access Code.');const accessCodeHash=await hash(code);const result:any=await FirebaseFirestore.getDocument({reference:`accessCodes/${accessCodeHash}`});const access=safe(result?.snapshot);if(!access?.active||!access?.workspaceId||!access?.unitId)throw new Error('Invalid or inactive Unit Access Code.');await FirebaseFirestore.setDocument({reference:`workspaces/${access.workspaceId}/members/${id}`,data:{uid:id,workspaceId:access.workspaceId,unitId:access.unitId,role:access.role==='view_only'?'view_only':'clinical_editor',accessCodeHash,joinedAt:new Date().toISOString(),updatedAt:new Date().toISOString()},merge:true});let unitName=String(access.unitName||'');try{const unit:any=await FirebaseFirestore.getDocument({reference:`workspaces/${access.workspaceId}/units/${access.unitId}`});unitName=String(safe(unit?.snapshot)?.name||unitName);}catch{}const state={workspaceId:String(access.workspaceId),role:(access.role==='view_only'?'view_only':'clinical_editor') as WorkspaceRole,unitId:String(access.unitId),unitName};setStoredWorkspaceAccess(state);return state;}
export async function getUnitAccessCodes():Promise<UnitAccessCode[]>{const state=await ensureOwnerWorkspace();if(!state)return[];const result:any=await FirebaseFirestore.getCollection({reference:`workspaces/${state.workspaceId}/accessCodes`});const snapshots=Array.isArray(result?.snapshots)?result.snapshots:[];return snapshots.map((s:any)=>{const d=safe(s)||{};return{unitId:String(d.unitId||''),unitName:String(d.unitName||'Unit'),code:String(d.code||''),role:(d.role==='view_only'?'view_only':'clinical_editor') as Exclude<WorkspaceRole,'owner'>,active:d.active!==false};}).filter(x=>x.unitId&&x.code&&x.active);}
export async function generateUnitAccessCode(unitId:string,unitName:string,role:Exclude<WorkspaceRole,'owner'>='clinical_editor'):Promise<string>{const state=await ensureOwnerWorkspace();if(!state)throw new Error('Only the Workspace Owner can generate Unit Access Codes.');const existing=await getUnitAccessCodes();for(const item of existing.filter(x=>x.unitId===unitId&&x.active))await revokeUnitAccessCode(item.code);const code=newCode();const accessCodeHash=await hash(code);const now=new Date().toISOString();const payload={hash:accessCodeHash,code,workspaceId:state.workspaceId,unitId,unitName,role,active:true,createdAt:now};await FirebaseFirestore.setDocument({reference:`workspaces/${state.workspaceId}/accessCodes/${accessCodeHash}`,data:{...payload,createdBy:state.workspaceId.replace(WORKSPACE_PREFIX,'')},merge:false});await FirebaseFirestore.setDocument({reference:`accessCodes/${accessCodeHash}`,data:payload,merge:true});return code;}
export async function revokeUnitAccessCode(code:string):Promise<void>{const state=await ensureOwnerWorkspace();if(!state)throw new Error('Only the Workspace Owner can revoke Unit Access Codes.');const accessCodeHash=await hash(code);await FirebaseFirestore.setDocument({reference:`workspaces/${state.workspaceId}/accessCodes/${accessCodeHash}`,data:{active:false,revokedAt:new Date().toISOString()},merge:true});await FirebaseFirestore.setDocument({reference:`accessCodes/${accessCodeHash}`,data:{active:false,revokedAt:new Date().toISOString()},merge:true});}
export function isOwnerAccess(){return getStoredWorkspaceAccess()?.role==='owner';}
export function canEditClinicalData(){const role=getStoredWorkspaceAccess()?.role;return role==='owner'||role==='clinical_editor';}
export function canManageStructure(){return isOwnerAccess();}
