import { Capacitor } from '@capacitor/core';
import { FirebaseAuthentication } from '@capacitor-firebase/authentication';
import { FirebaseFirestore } from '@capacitor-firebase/firestore';

export type WorkspaceRole = 'owner' | 'view_only' | 'clinical_editor';
export interface WorkspaceAccessState { workspaceId:string; role:WorkspaceRole; unitId:string|null; unitName:string|null; }
export interface UnitAccessCode { unitId:string; unitName:string; code:string; role:Exclude<WorkspaceRole,'owner'>; active:boolean; }
const ACTIVE_KEY='cardiovault_active_workspace_access_v1';
const WORKSPACE_PREFIX='workspace_';
const safeSnapshotData=(snapshot:any):any=>{try{return typeof snapshot?.data==='function'?snapshot.data():(snapshot?.data||null);}catch{return null;}};
const getUid=async():Promise<string|null>=>{if(!Capacitor.isNativePlatform())return null;try{return(await FirebaseAuthentication.getCurrentUser()).user?.uid||null;}catch{return null;}};
const workspaceIdForOwner=(uid:string)=>`${WORKSPACE_PREFIX}${uid}`;
const sha256=async(value:string):Promise<string>=>{const bytes=new TextEncoder().encode(value.trim().toUpperCase());const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');};
const randomCode=()=>{const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=new Uint8Array(10);crypto.getRandomValues(bytes);const raw=Array.from(bytes).map(b=>alphabet[b%alphabet.length]).join('');return`CV-${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8)}`;};
export const getStoredWorkspaceAccess=():WorkspaceAccessState|null=>{try{const parsed=JSON.parse(localStorage.getItem(ACTIVE_KEY)||'null');return parsed?.workspaceId?parsed:null;}catch{return null;}};
export const setStoredWorkspaceAccess=(state:WorkspaceAccessState|null)=>{if(state)localStorage.setItem(ACTIVE_KEY,JSON.stringify(state));else localStorage.removeItem(ACTIVE_KEY);};
export async function ensureOwnerWorkspace():Promise<WorkspaceAccessState|null>{const uid=await getUid();if(!uid)return null;const workspaceId=workspaceIdForOwner(uid);try{const result:any=await FirebaseFirestore.getDocument({reference:`workspaces/${workspaceId}`});const data=safeSnapshotData(result?.snapshot);if(data?.ownerUid===uid){const state={workspaceId,role:'owner' as const,unitId:null,unitName:null};setStoredWorkspaceAccess(state);return state;}return null;}catch{return null;}}
export async function redeemUnitAccessCode(rawCode:string):Promise<WorkspaceAccessState>{const uid=await getUid();if(!uid)throw new Error('A Firebase account must be signed in before entering an access code.');const code=rawCode.trim().toUpperCase();if(code.length<10)throw new Error('Invalid Unit Access Code.');const hash=await sha256(code);const index:any=await FirebaseFirestore.getDocument({reference:`accessCodes/${hash}`});const access=safeSnapshotData(index?.snapshot);if(!access?.active||!access?.workspaceId||!access?.unitId)throw new Error('Invalid or inactive Unit Access Code.');const memberRef=`workspaces/${access.workspaceId}/members/${uid}`;await FirebaseFirestore.setDocument({reference:memberRef,data:{uid,workspaceId:access.workspaceId,unitId:access.unitId,role:access.role==='view_only'?'view_only':'clinical_editor',accessCodeHash:hash,joinedAt:new Date().toISOString(),updatedAt:new Date().toISOString()},merge:true});let unitName=String(access.unitName||'');try{const unit:any=await FirebaseFirestore.getDocument({reference:`workspaces/${access.workspaceId}/units/${access.unitId}`});unitName=String(safeSnapshotData(unit?.snapshot)?.name||unitName);}catch{}const state={workspaceId:String(access.workspaceId),role:(access.role==='view_only'?'view_only':'clinical_editor') as WorkspaceRole,unitId:String(access.unitId),unitName};setStoredWorkspaceAccess(state);return state;}
export async function getUnitAccessCodes():Promise<UnitAccessCode[]>{const state=await ensureOwnerWorkspace();if(!state)return[];const result:any=await FirebaseFirestore.getCollection({reference:`workspaces/${state.workspaceId}/accessCodes`});const snapshots=Array.isArray(result?.snapshots)?result.snapshots:[];return snapshots.map((s:any)=>{const d=safeSnapshotData(s)||{};return{unitId:String(d.unitId||''),unitName:String(d.unitName||'Unit'),code:String(d.code||''),role:(d.role==='view_only'?'view_only':'clinical_editor') as Exclude<WorkspaceRole,'owner'>,active:d.active!==false};}).filter(x=>x.unitId&&x.code);}
export async function generateUnitAccessCode(unitId:string,unitName:string,role:Exclude<WorkspaceRole,'owner'>='clinical_editor'):Promise<string>{const state=await ensureOwnerWorkspace();if(!state)throw new Error('Only the Workspace Owner can generate Unit Access Codes.');const code=randomCode();const hash=await sha256(code);const now=new Date().toISOString();await FirebaseFirestore.setDocument({reference:`workspaces/${state.workspaceId}/accessCodes/${hash}`,data:{hash,code,workspaceId:state.workspaceId,unitId,unitName,role,active:true,createdAt:now,createdBy:state.workspaceId.replace(WORKSPACE_PREFIX,'')},merge:false});await FirebaseFirestore.setDocument({reference:`accessCodes/${hash}`,data:{hash,code,workspaceId:state.workspaceId,unitId,unitName,role,active:true,createdAt:now},merge:true});return code;}
export async function revokeUnitAccessCode(code:string):Promise<void>{const state=await ensureOwnerWorkspace();if(!state)throw new Error('Only the Workspace Owner can revoke Unit Access Codes.');const hash=await sha256(code);await FirebaseFirestore.setDocument({reference:`workspaces/${state.workspaceId}/accessCodes/${hash}`,data:{active:false,revokedAt:new Date().toISOString()},merge:true});await FirebaseFirestore.setDocument({reference:`accessCodes/${hash}`,data:{active:false,revokedAt:new Date().toISOString()},merge:true});}
export function isOwnerAccess(){return getStoredWorkspaceAccess()?.role==='owner';}
export function canEditClinicalData(){const role=getStoredWorkspaceAccess()?.role;return role==='owner'||role==='clinical_editor';}
export function canManageStructure(){return isOwnerAccess();}
