import React, { useState } from 'react';
import { ArrowLeft, Plus, ChevronRight, BedDouble, UserPlus, LogOut, X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { PatientStatus } from '../../types/clinical';

export const UnitCensusView: React.FC = () => {
  const { currentUnitId, getUnitById, getBedsByUnit, patients, setCurrentPatientId, setCurrentView, addBed, addPatient, setActivePatientSection, dischargePatient, showToast } = useApp();
  const [showAdmitModal, setShowAdmitModal] = useState(false);
  const [selectedBedId, setSelectedBedId] = useState<string | null>(null);
  const [dischargeTarget, setDischargeTarget] = useState<{ id: string; name: string; bed: string } | null>(null);
  const [dischargeReason, setDischargeReason] = useState('Clinical Discharge');
  const [dischargeSummary, setDischargeSummary] = useState('');
  const [newPatientName, setNewPatientName] = useState('');
  const [newPatientAge, setNewPatientAge] = useState<number>(55);
  const [newPatientSex, setNewPatientSex] = useState<'Male' | 'Female'>('Male');
  const [newPatientDiagnosis, setNewPatientDiagnosis] = useState('');
  const [newPatientStatus, setNewPatientStatus] = useState<PatientStatus>('Stable');
  const [newPatientMRN, setNewPatientMRN] = useState('');

  const currentUnit = currentUnitId ? getUnitById(currentUnitId) : null;
  const unitBeds = currentUnitId ? getBedsByUnit(currentUnitId) : [];

  if (!currentUnit) return <div className="p-8 text-center text-slate-400"><p>No unit selected.</p><button onClick={() => setCurrentView('home')} className="mt-4 px-4 py-2 bg-cyan-500 text-slate-950 rounded-xl font-semibold text-sm">Return Home</button></div>;

  const handleOpenPatient = (patientId: string) => { setCurrentPatientId(patientId); setActivePatientSection('overview'); setCurrentView('patient'); };
  const handleOpenAdmitModal = (bedId: string) => { setSelectedBedId(bedId); setNewPatientName(''); setNewPatientDiagnosis(''); setNewPatientMRN(`MRN-${Math.floor(100000 + Math.random() * 900000)}`); setShowAdmitModal(true); };
  const handleAdmitSubmit = (e: React.FormEvent) => { e.preventDefault(); if (!newPatientName.trim() || !selectedBedId) return; const p = addPatient({ fullName:newPatientName.trim(), age:newPatientAge, sex:newPatientSex, mrn:newPatientMRN, primaryDiagnosis:newPatientDiagnosis.trim() || 'Acute Admission', status:newPatientStatus, unitId:currentUnit.id }, selectedBedId); setShowAdmitModal(false); handleOpenPatient(p.id); };
  const openDischarge = (e: React.MouseEvent, patientId: string, name: string, bedNumber: string) => { e.stopPropagation(); setDischargeTarget({id:patientId,name,bed:bedNumber}); setDischargeReason('Clinical Discharge'); setDischargeSummary(''); };
  const confirmDischarge = () => { if (!dischargeTarget) return; dischargePatient(dischargeTarget.id, dischargeReason, dischargeSummary); setDischargeTarget(null); setCurrentView('census'); showToast(`${dischargeTarget.name} discharged. ${dischargeTarget.bed} is now available.`, 'success'); };
  const getStatusBadge = (status: PatientStatus) => {
    const styles = status==='Critical' ? 'bg-rose-500/15 text-rose-500 border-rose-500/30' : status==='Unstable' ? 'bg-amber-500/15 text-amber-500 border-amber-500/30' : 'bg-emerald-500/15 text-emerald-500 border-emerald-500/30';
    return <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold border ${styles}`}><span className="w-1.5 h-1.5 rounded-full bg-current" />{status}</span>;
  };

  return <div className="max-w-5xl mx-auto px-4 py-6 space-y-6 animate-in fade-in duration-200">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={() => setCurrentView('home')} className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300"><ArrowLeft className="w-5 h-5" /></button><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">{currentUnit.name}</h1><p className="text-xs text-slate-500 dark:text-slate-400">{unitBeds.length} Beds • {currentUnit.type}</p></div></div><button onClick={() => addBed(currentUnit.id)} className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 border border-cyan-500/30 text-xs font-bold"><Plus className="w-4 h-4" /> Add Bed</button></div>

    <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] overflow-hidden shadow-sm"><div className="hidden md:grid grid-cols-[90px_1.5fr_1.4fr_120px_210px] gap-3 px-5 py-3 bg-slate-50 dark:bg-slate-900/70 text-[10px] font-bold uppercase tracking-wider text-slate-400"><span>Bed</span><span>Patient</span><span>Diagnosis</span><span>Status</span><span>Actions</span></div>
      {unitBeds.map(bed => { const patient = bed.patientId ? patients.find(p => p.id===bed.patientId && !p.isArchived) : null; return <div key={bed.id} className={`grid ${patient ? 'grid-cols-1' : 'grid-cols-[auto_1fr_auto]'} md:grid-cols-[90px_1.5fr_1.4fr_120px_210px] gap-2 md:gap-3 md:items-center px-3 md:px-5 py-2.5 md:py-3 border-t border-slate-100 dark:border-slate-800 ${patient ? 'hover:bg-slate-50 dark:hover:bg-slate-900/40' : 'bg-slate-50/50 dark:bg-slate-900/20'}`}>
        <div className="flex items-center gap-2.5"><div className={`w-9 h-9 rounded-xl flex items-center justify-center ${patient ? 'bg-cyan-500/10 text-cyan-500' : 'bg-slate-200/60 dark:bg-slate-800 text-slate-400'}`}><BedDouble className="w-4.5 h-4.5" /></div><div><span className="text-xs font-bold text-slate-700 dark:text-slate-300">{bed.bedNumber}</span><div className="md:hidden text-[9px] text-slate-400">Bed</div></div></div>
        {patient ? <><button onClick={() => handleOpenPatient(patient.id)} className="text-left min-w-0"><div className="text-sm font-bold text-slate-900 dark:text-white truncate">{patient.fullName}</div><div className="text-[11px] text-slate-500 dark:text-slate-400 truncate">{patient.mrn}</div></button><div className="text-xs text-slate-600 dark:text-slate-300 truncate">{patient.primaryDiagnosis || '—'}</div><div>{getStatusBadge(patient.status)}</div><div className="flex items-center gap-2" onClick={e => e.stopPropagation()}><button onClick={() => handleOpenPatient(patient.id)} className="flex-1 inline-flex items-center justify-center gap-1 px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-bold text-slate-700 dark:text-slate-200 hover:border-cyan-500 hover:text-cyan-500"><ChevronRight className="w-3.5 h-3.5" /> View</button><button onClick={e => openDischarge(e, patient.id, patient.fullName, bed.bedNumber)} className="flex-1 inline-flex items-center justify-center gap-1 px-3 py-2 rounded-xl border border-rose-500/40 text-rose-500 hover:bg-rose-500 hover:text-white text-xs font-bold"><LogOut className="w-3.5 h-3.5" /> Discharge</button></div></> : <><div className="md:col-span-3 min-w-0"><div className="text-sm font-semibold text-slate-400 truncate">Empty Bed</div><div className="text-[10px] text-slate-400/80 truncate">Available for immediate admission</div></div><button type="button" onClick={() => handleOpenAdmitModal(bed.id)} className="inline-flex items-center justify-center gap-1 px-2.5 py-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-[11px] whitespace-nowrap"><UserPlus className="w-3.5 h-3.5" /> Admit</button></>}
      </div>; })}
    </div>

    {showAdmitModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-lg bg-white dark:bg-[#111C2E] rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xl"><h3 className="text-lg font-bold text-slate-900 dark:text-white">Admit Patient to {currentUnit.name}</h3><p className="text-xs text-slate-500 mt-1">Create a new patient file assigned to this bed.</p><form onSubmit={handleAdmitSubmit} className="space-y-4 mt-5"><input required value={newPatientName} onChange={e=>setNewPatientName(e.target.value)} placeholder="Patient Full Name" className="w-full px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><div className="grid grid-cols-2 gap-3"><input value={newPatientMRN} onChange={e=>setNewPatientMRN(e.target.value)} placeholder="MRN" className="px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><input type="number" value={newPatientAge} onChange={e=>setNewPatientAge(parseInt(e.target.value)||0)} placeholder="Age" className="px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/></div><div className="grid grid-cols-2 gap-3"><select value={newPatientSex} onChange={e=>setNewPatientSex(e.target.value as any)} className="px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"><option>Male</option><option>Female</option><option>Other</option></select><select value={newPatientStatus} onChange={e=>setNewPatientStatus(e.target.value as PatientStatus)} className="px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"><option>Stable</option><option>Unstable</option><option>Critical</option></select></div><input required value={newPatientDiagnosis} onChange={e=>setNewPatientDiagnosis(e.target.value)} placeholder="Primary Diagnosis" className="w-full px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><div className="flex justify-end gap-2 pt-3"><button type="button" onClick={()=>setShowAdmitModal(false)} className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-500">Cancel</button><button type="submit" className="px-5 py-2.5 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Complete Admission</button></div></form></div></div>}

    {dischargeTarget && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl border border-rose-200 dark:border-rose-900/40 p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><div className="w-11 h-11 rounded-xl bg-rose-500/10 text-rose-500 flex items-center justify-center mb-3"><LogOut className="w-5 h-5" /></div><h3 className="text-lg font-bold text-slate-900 dark:text-white">Discharge Patient</h3><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Are you sure you want to discharge <strong>{dischargeTarget.name}</strong> from {dischargeTarget.bed}?</p></div><button onClick={()=>setDischargeTarget(null)} className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4" /></button></div><div className="space-y-3 mt-5"><div><label className="block text-xs font-semibold text-slate-600 dark:text-slate-300 mb-1">Discharge Reason</label><select value={dischargeReason} onChange={e=>setDischargeReason(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"><option>Clinical Discharge</option><option>Transfer</option><option>Patient Improved</option><option>Against Medical Advice</option><option>Death</option></select></div><div><label className="block text-xs font-semibold text-slate-600 dark:text-slate-300 mb-1">Discharge Summary</label><textarea value={dischargeSummary} onChange={e=>setDischargeSummary(e.target.value)} rows={4} placeholder="Optional discharge summary..." className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm resize-none"/></div></div><div className="flex justify-end gap-2 mt-5 pt-4 border-t border-slate-100 dark:border-slate-800"><button onClick={()=>setDischargeTarget(null)} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold">Cancel</button><button onClick={confirmDischarge} className="px-5 py-2 rounded-xl bg-rose-500 hover:bg-rose-600 text-white text-xs font-bold inline-flex items-center gap-2"><LogOut className="w-3.5 h-3.5" /> Discharge</button></div><p className="text-[10px] text-slate-400 mt-3">The patient will be moved to Archive and the bed will become available. You will remain on this census page.</p></div></div>}
  </div>;
};
