import React,{useState} from 'react';
import {Brain,AlertTriangle,CheckCircle2,RefreshCw,Sparkles,ShieldAlert,X} from 'lucide-react';
import {Patient} from '../../types/clinical';
import {AIClinicalResult,analyzePatientWithAI} from '../../services/aiClinicalService';

interface Props{patient:Patient;onClose:()=>void;}

export const AIClinicalAssistant:React.FC<Props>=({patient,onClose})=>{
 const[result,setResult]=useState<AIClinicalResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const run=async()=>{setLoading(true);setError('');try{setResult(await analyzePatientWithAI(patient));}catch(e){setError(e instanceof Error?e.message:'AI analysis failed.');}finally{setLoading(false);}};
 return <div className="fixed inset-0 z-[120] bg-slate-950/70 backdrop-blur-sm p-3 sm:p-6 flex items-center justify-center">
  <div className="w-full max-w-5xl max-h-[92vh] overflow-y-auto rounded-3xl bg-white dark:bg-[#0E1626] border border-slate-200 dark:border-slate-800 shadow-2xl">
   <div className="sticky top-0 z-10 flex items-center justify-between gap-3 px-5 py-4 border-b border-slate-200 dark:border-slate-800 bg-white/95 dark:bg-[#0E1626]/95 backdrop-blur"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-violet-500/15 text-violet-500 flex items-center justify-center"><Brain className="w-5 h-5"/></div><div><h2 className="text-base font-extrabold text-slate-900 dark:text-white">AI Clinical Assistant</h2><p className="text-[11px] text-slate-400">Differential analysis + clinician-reviewed treatment suggestions</p></div></div><button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-5 h-5"/></button></div>
   <div className="p-5 space-y-5">
    <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 flex gap-3"><ShieldAlert className="w-5 h-5 text-amber-500 shrink-0 mt-0.5"/><div className="text-xs leading-relaxed text-slate-700 dark:text-slate-300"><b>Clinical safety:</b> AI output is decision support only. It may be incomplete or wrong. It does not confirm a diagnosis, prescribe automatically, or replace bedside assessment, local protocols, drug references, or specialist review. Verify every recommendation before acting.</div></div>
    {!result&&!loading&&<div className="text-center py-10"><Sparkles className="w-10 h-10 mx-auto text-violet-500 mb-3"/><h3 className="text-lg font-extrabold text-slate-900 dark:text-white">Analyze {patient.fullName}</h3><p className="text-xs text-slate-500 max-w-lg mx-auto mt-2">The assistant will review the structured clinical data currently stored in this patient file and identify a differential, safety issues, missing data, and possible next actions.</p><button onClick={run} className="mt-5 inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-violet-500 text-white text-sm font-bold shadow-sm hover:bg-violet-600"><Sparkles className="w-4 h-4"/>Run AI Analysis</button></div>}
    {loading&&<div className="py-12 text-center"><RefreshCw className="w-8 h-8 mx-auto animate-spin text-violet-500"/><p className="mt-3 text-sm font-bold text-slate-700 dark:text-slate-200">Analyzing clinical data…</p><p className="text-xs text-slate-400 mt-1">No clinical action is taken automatically.</p></div>}
    {error&&<div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-xs text-rose-600 dark:text-rose-300"><b>AI error:</b> {error}</div>}
    {result&&<div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><span className="inline-flex items-center gap-2 text-xs font-bold text-violet-500"><Sparkles className="w-4 h-4"/>Working assessment — not a confirmed diagnosis</span><button onClick={run} disabled={loading} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold"><RefreshCw className="w-3.5 h-3.5"/>Re-analyze</button></div>
      <section className="rounded-2xl border border-violet-500/25 bg-violet-500/[0.06] p-4"><h3 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2">Clinical analysis</h3><p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300 whitespace-pre-wrap">{result.diagnosticAnalysis}</p><div className="mt-3 text-[11px] text-slate-400">Model confidence: {result.confidence}</div></section>
      <section><h3 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2">Differential diagnoses</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{result.differentialDiagnoses?.map((d,i)=><div key={i} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] p-4"><div className="flex items-center justify-between gap-2"><b className="text-sm text-slate-900 dark:text-white">{d.diagnosis}</b><span className={`text-[10px] font-bold uppercase ${d.urgency==='urgent'?'text-rose-500':d.urgency==='important'?'text-amber-500':'text-slate-400'}`}>{d.urgency}</span></div><p className="text-xs leading-relaxed text-slate-500 dark:text-slate-400 mt-2">{d.rationale}</p></div>)}</div></section>
      <section><h3 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2">Recommended actions — clinician review</h3><div className="space-y-2">{result.recommendedActions?.map((x,i)=><div key={i} className="flex gap-2 rounded-xl bg-slate-50 dark:bg-slate-900/60 p-3 text-xs text-slate-700 dark:text-slate-300"><CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0"/>{x}</div>)}</div></section>
      <section><h3 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2">Safety checks</h3><div className="space-y-2">{result.safetyChecks?.map((x,i)=><div key={i} className="flex gap-2 rounded-xl bg-amber-500/10 border border-amber-500/20 p-3 text-xs text-slate-700 dark:text-slate-300"><AlertTriangle className="w-4 h-4 text-amber-500 shrink-0"/>{x}</div>)}</div></section>
      {result.missingData?.length>0&&<section><h3 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2">Missing / useful data</h3><div className="flex flex-wrap gap-2">{result.missingData.map((x,i)=><span key={i} className="px-2.5 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-800 text-[11px] text-slate-600 dark:text-slate-300">{x}</span>)}</div></section>}
    </div>}
   </div>
  </div>
 </div>;
};
