import React,{useState}from'react';
import {Save,X} from'lucide-react';
import {Patient,CalculatorResult}from'../../types/clinical';
import {useApp}from'../../context/AppContext';

const calculators=[
 ['cha2ds2-vasc','CHA₂DS₂-VASc'],['has-bled','HAS-BLED'],['heart-score','HEART Score'],['timi-nstemi','TIMI Risk Score (UA/NSTEMI)'],['killip-class','Killip Classification'],['qtc-calc','QTc Corrected'],['sofa-score','SOFA Score'],['qsofa','qSOFA'],['news2','NEWS2'],['gcs-calc','Glasgow Coma Scale (GCS)'],['vent-mechanics','Ventilator Mechanics'],['winter-abg',"Systematic ABG & Winter's Formula"],['map-hemodynamics','MAP & Hemodynamic Indices'],['infusion-rate','Vasopressor & Infusion Rate'],['crcl-calc','Creatinine Clearance & eGFR'],['corrected-na-ca','Corrected Sodium & Calcium'],['fena-calc','FENa & Free Water Deficit']
] as const;

export const CalculatorSaveBar:React.FC<{patient:Patient}>=({patient})=>{
 const{updatePatient,showToast}=useApp();const[open,setOpen]=useState(false);const[name,setName]=useState<string>(calculators[0][0]);const[score,setScore]=useState('');const[interpretation,setInterpretation]=useState('');
 const selected=calculators.find(x=>x[0]===name)?.[1]||name;
 const save=()=>{if(!score.trim())return;const n=Number(score);const riskLevel=(/critical/i.test(interpretation)?'Critical':/very high/i.test(interpretation)?'Very High':/high/i.test(interpretation)?'High':/intermediate|moderate/i.test(interpretation)?'Intermediate':'Normal') as CalculatorResult['riskLevel'];const result:CalculatorResult={id:`calc-${Date.now()}`,calculatorId:name,name:selected,timestamp:new Date().toISOString(),score:Number.isFinite(n)?n:score.trim(),riskLevel,interpretation:interpretation.trim()||'Saved clinical score',summary:`${selected}: ${score.trim()}`};updatePatient(patient.id,{calculatorResults:[...(patient.calculatorResults||[]),result]});showToast(`${selected} saved to patient file.`,'success');setScore('');setInterpretation('');setOpen(false);};
 return <><div className="mb-4 flex items-center justify-between gap-3 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 dark:bg-cyan-500/5 px-4 py-3"><div><div className="text-xs font-extrabold text-slate-900 dark:text-white">Save a Clinical Score</div><div className="text-[10px] text-slate-400">Store a calculator result directly in this patient's file.</div></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Save className="w-3.5 h-3.5"/>Save Score</button></div>{open&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-md rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 shadow-2xl p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-slate-900 dark:text-white">Save Calculator Result</h3><button onClick={()=>setOpen(false)} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4"/></button></div><div className="space-y-3 mt-4"><select value={name} onChange={e=>setName(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm">{calculators.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input autoFocus value={score} onChange={e=>setScore(e.target.value)} placeholder="Score / result" className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><input value={interpretation} onChange={e=>setInterpretation(e.target.value)} placeholder="Interpretation (optional)" className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><button onClick={save} disabled={!score.trim()} className="w-full py-2.5 rounded-xl bg-cyan-500 disabled:opacity-40 text-slate-950 text-xs font-bold">Save to Patient File</button></div></div></div>}</>;
};