import React,{useEffect,useMemo,useState}from'react';
import {AlarmClock, BellRing, Check, Trash2, X}from'lucide-react';
import {PatientSectionId}from'../../types/clinical';

export type PanelAlarm={id:string;sectionId:PatientSectionId;label:string;message:string;severity:'warning'|'critical';active:boolean;createdAt:string};
const key=(patientId:string)=>`cardiovault_panel_alarms_v1_${patientId}`;
const read=(patientId:string):PanelAlarm[]=>{try{const v=JSON.parse(localStorage.getItem(key(patientId))||'[]');return Array.isArray(v)?v:[];}catch{return[];}};
export const getPanelAlarms=(patientId:string)=>read(patientId).filter(a=>a.active);
const emit=()=>window.dispatchEvent(new CustomEvent('cardiovault-panel-alarm-change'));

interface Props{patientId:string;sectionId:PatientSectionId;sectionLabel:string;readOnly?:boolean;compact?:boolean;}
export const PanelAlarmManager:React.FC<Props>=({patientId,sectionId,sectionLabel,readOnly=false,compact=false})=>{
 const[open,setOpen]=useState(false);const[alarms,setAlarms]=useState<PanelAlarm[]>(()=>read(patientId));const[label,setLabel]=useState('');const[message,setMessage]=useState('');const[severity,setSeverity]=useState<PanelAlarm['severity']>('warning');
 useEffect(()=>{setAlarms(read(patientId));},[patientId]);
 const active=useMemo(()=>alarms.filter(a=>a.active&&a.sectionId===sectionId),[alarms,sectionId]);
 const save=()=>{if(!label.trim())return;const next=[...alarms,{id:`alarm-${Date.now()}`,sectionId,label:label.trim(),message:message.trim(),severity,active:true,createdAt:new Date().toISOString()}];localStorage.setItem(key(patientId),JSON.stringify(next));setAlarms(next);emit();setLabel('');setMessage('');setSeverity('warning');setOpen(false);};
 const clear=(id:string)=>{const next=alarms.map(a=>a.id===id?{...a,active:false}:a);localStorage.setItem(key(patientId),JSON.stringify(next));setAlarms(next);emit();};
 return <>{!readOnly&&<button type="button" onClick={()=>setOpen(true)} className={`inline-flex items-center gap-1.5 rounded-xl border text-xs font-bold ${active.length?'border-rose-400/60 bg-rose-500/10 text-rose-600 dark:text-rose-300':'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-500 dark:text-slate-300'} ${compact?'px-2.5 py-2':'px-3 py-2'}`}><AlarmClock className="w-4 h-4"/>{compact?'Alarm':'Set Alarm'}{active.length>0&&<span className="min-w-5 h-5 px-1 rounded-full bg-rose-500 text-white text-[10px] inline-flex items-center justify-center">{active.length}</span>}</button>}
 {active.length>0&&<div className="flex flex-wrap gap-1.5">{active.map(a=><button key={a.id} type="button" onClick={()=>!readOnly&&setOpen(true)} className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-[10px] font-bold border ${a.severity==='critical'?'border-rose-400/50 bg-rose-500/10 text-rose-600 dark:text-rose-300':'border-amber-400/50 bg-amber-500/10 text-amber-600 dark:text-amber-300'}`}><BellRing className="w-3.5 h-3.5"/>{a.label}</button>)}</div>}
 {open&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><div className="w-full max-w-md rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 shadow-2xl p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold text-slate-900 dark:text-white">{sectionLabel} Alarm</h3><p className="text-[11px] text-slate-500 mt-1">This alarm is shown outside the panel in the patient file.</p></div><button onClick={()=>setOpen(false)} className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4"/></button></div><div className="space-y-3 mt-5"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Alarm label e.g. Review ECG" className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm"/><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="Optional note / reason" className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm resize-none"/><div className="grid grid-cols-2 gap-2"><button onClick={()=>setSeverity('warning')} className={`px-3 py-2 rounded-xl border text-xs font-bold ${severity==='warning'?'border-amber-400 bg-amber-500/10 text-amber-600':'border-slate-200 dark:border-slate-700 text-slate-500'}`}>Warning</button><button onClick={()=>setSeverity('critical')} className={`px-3 py-2 rounded-xl border text-xs font-bold ${severity==='critical'?'border-rose-400 bg-rose-500/10 text-rose-600':'border-slate-200 dark:border-slate-700 text-slate-500'}`}>Critical</button></div></div>{active.length>0&&<div className="mt-5 pt-4 border-t border-slate-100 dark:border-slate-800 space-y-2"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">Active alarms</div>{active.map(a=><div key={a.id} className="flex items-center gap-2 p-2 rounded-xl bg-slate-50 dark:bg-slate-900"><div className="min-w-0 flex-1"><div className="text-xs font-bold">{a.label}</div>{a.message&&<div className="text-[10px] text-slate-500 truncate">{a.message}</div>}</div><button onClick={()=>clear(a.id)} className="inline-flex items-center gap-1 px-2 py-1.5 rounded-lg text-[10px] font-bold text-rose-500 hover:bg-rose-500/10"><Trash2 className="w-3.5 h-3.5"/>Clear</button></div>)}</div>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>setOpen(false)} className="px-4 py-2 rounded-xl text-xs font-bold text-slate-500">Cancel</button><button onClick={save} disabled={!label.trim()} className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold disabled:opacity-40"><Check className="w-4 h-4"/>Save Alarm</button></div></div></div>}
 </>;
};