import React,{useState}from'react';
import {ArrowLeft,Edit,ArrowRightLeft,LogOut}from'lucide-react';
import {useApp}from'../../context/AppContext';
import {Patient,PatientStatus}from'../../types/clinical';
interface PatientFileHeaderProps{patient:Patient;onEditClick?:()=>void;readOnly?:boolean;}
export const PatientFileHeader:React.FC<PatientFileHeaderProps>=({patient,onEditClick,readOnly=false})=>{const{setCurrentView,getUnitById,beds,units,transferPatient,dischargePatient,updatePatient}=useApp();const[showTransferModal,setShowTransferModal]=useState(false);const[showDischargeModal,setShowDischargeModal]=useState(false);const[targetUnitId,setTargetUnitId]=useState(patient.unitId);const[targetBedId,setTargetBedId]=useState('');const[dischargeReason,setDischargeReason]=useState('Discharged Home');const[dischargeSummary,setDischargeSummary]=useState('');const currentUnit=getUnitById(patient.unitId);const currentBed=beds.find(b=>b.id===patient.bedId);const availableBeds=beds.filter(b=>b.unitId===targetUnitId&&!b.patientId);const handleTransfer=(e:React.FormEvent)=>{e.preventDefault();if(!targetBedId)return;transferPatient(patient.id,targetUnitId,targetBedId);setShowTransferModal(false);};const handleDischarge=(e:React.FormEvent)=>{e.preventDefault();dischargePatient(patient.id,dischargeReason,dischargeSummary);setShowDischargeModal(false);};const handleStatusChange=(newStatus:PatientStatus)=>{if(!readOnly)updatePatient(patient.id,{status:newStatus});};return <>
<div className="relative z-10 bg-white dark:bg-[#111C2E] border-b border-slate-200 dark:border-slate-800 shadow-sm min-h-0 h-auto overflow-visible">
 <div className="max-w-7xl mx-auto w-full px-3 sm:px-6 py-3">
  <div className="flex flex-col gap-3 min-h-0">
   <div className="flex items-center gap-3 min-w-0">
    <button onClick={()=>setCurrentView(readOnly?'archive':'census')} className="rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 p-2 shrink-0" title={readOnly?'Back to Archive':'Back to Unit Census'}><ArrowLeft className="w-5 h-5"/></button>
    <div className="relative shrink-0">{patient.photoUrl?<img src={patient.photoUrl} alt={patient.fullName} referrerPolicy="no-referrer" className="w-12 h-12 rounded-2xl object-cover ring-2 ring-cyan-500/40 shadow-md"/>:<div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-cyan-600 to-sky-400 text-white text-lg font-bold flex items-center justify-center shadow-md">{patient.fullName.charAt(0)}</div>}{patient.status==='Critical'&&<span className="absolute -top-1 -right-1 w-3.5 h-3.5 bg-rose-500 border-2 border-white dark:border-[#111C2E] rounded-full"/>}</div>
    <div className="min-w-0 flex-1">
     <div className="flex flex-wrap items-center gap-2"><h1 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white tracking-tight truncate">{patient.fullName}</h1>{readOnly?<span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-amber-500/15 text-amber-600 border border-amber-500/30">ARCHIVED • READ ONLY</span>:<div className="relative shrink-0"><select value={patient.status} onChange={e=>handleStatusChange(e.target.value as PatientStatus)} className={`text-xs font-bold px-2.5 py-1 rounded-full border cursor-pointer focus:outline-none appearance-none pr-5 ${patient.status==='Critical'?'bg-rose-500/15 text-rose-500 border-rose-500/40':patient.status==='Unstable'?'bg-amber-500/15 text-amber-500 border-amber-500/40':'bg-emerald-500/15 text-emerald-500 border-emerald-500/40'}`}><option value="Critical">Critical</option><option value="Unstable">Unstable</option><option value="Stable">Stable</option></select><span className="absolute right-1.5 top-1/2 -translate-y-1/2 pointer-events-none text-[9px]">▼</span></div>}</div>
     <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-[11px] sm:text-xs text-slate-500 dark:text-slate-400 mt-1"><span className="font-semibold text-slate-700 dark:text-slate-300">MRN: {patient.mrn}</span><span>•</span><span className="text-cyan-600 dark:text-cyan-400 font-medium">{currentUnit?.name||'Unit'} • {currentBed?.bedNumber||'Archived'}</span><span>•</span><span>{patient.age}y / {patient.sex}</span><span>•</span><span className="font-medium text-slate-700 dark:text-slate-300 truncate max-w-[220px]">{patient.primaryDiagnosis}</span></div>
    </div>
   </div>
   {!readOnly&&<div className="flex items-center gap-2 overflow-x-auto pb-0"><button onClick={onEditClick} className="flex items-center gap-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-semibold px-3 py-2 text-xs shrink-0"><Edit className="w-3.5 h-3.5 text-cyan-500"/>Edit</button><button onClick={()=>{setTargetUnitId(patient.unitId);setShowTransferModal(true)}} className="flex items-center gap-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-semibold px-3 py-2 text-xs shrink-0"><ArrowRightLeft className="w-3.5 h-3.5 text-sky-500"/>Transfer</button><button onClick={()=>setShowDischargeModal(true)} className="flex items-center gap-1.5 rounded-xl bg-rose-50 dark:bg-rose-950/30 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-900/50 font-semibold px-3 py-2 text-xs shrink-0"><LogOut className="w-3.5 h-3.5"/>Discharge</button></div>}
  </div>
 </div>
</div>
{showTransferModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl p-6 space-y-4"><h3 className="text-lg font-bold">Transfer {patient.fullName}</h3><form onSubmit={handleTransfer} className="space-y-4"><select value={targetUnitId} onChange={e=>{setTargetUnitId(e.target.value);setTargetBedId('')}} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option value="">Select Unit</option>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.type})</option>)}</select><select required value={targetBedId} onChange={e=>setTargetBedId(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option value="">Select Bed</option>{availableBeds.map(b=><option key={b.id} value={b.id}>{b.bedNumber}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowTransferModal(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-4 py-2 rounded-xl bg-sky-500 text-white text-xs font-bold">Confirm Transfer</button></div></form></div></div>}
{showDischargeModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl p-6 space-y-4"><h3 className="text-lg font-bold">Discharge & Archive Patient</h3><form onSubmit={handleDischarge} className="space-y-4"><select value={dischargeReason} onChange={e=>setDischargeReason(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option>Discharged Home</option><option>Transferred to Ward</option><option>Transferred to Rehab</option><option>Deceased</option><option>Left AMA</option></select><textarea rows={4} value={dischargeSummary} onChange={e=>setDischargeSummary(e.target.value)} placeholder="Discharge clinical summary..." className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowDischargeModal(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-4 py-2 rounded-xl bg-rose-500 text-white text-xs font-bold">Discharge to Archive</button></div></form></div></div>}
</>};
