import React,{useEffect,useState}from'react';
import {Check,ClipboardList,Edit3,Save,X}from'lucide-react';
import {useApp}from'../../context/AppContext';
import {Patient}from'../../types/clinical';

interface Props{patient:Patient;readOnly?:boolean;onClose:()=>void;}
type Draft={situation:string;background:string;assessment:string;recommendation:string};

export const PatientHandoverPanel:React.FC<Props>=({patient,readOnly=false,onClose})=>{
 const{updatePatient,showToast}=useApp();
 const makeDraft=():Draft=>{const v=patient.vitalsHistory?.[0];const note=patient.progressNotes?.[0];return{situation:patient.handover?.situation||`${patient.primaryDiagnosis} | Admitted ${patient.admissionDate} ${patient.admissionTime||''}`,background:patient.handover?.background||`PMH ${patient.clinicalSummary?.pmh?.join(', ')||'Not documented'} | Allergies ${patient.allergies?.join(', ')||'NKDA'}`,assessment:patient.handover?.assessment||`BP ${v?.sbp??'--'}/${v?.dbp??'--'} mmHg, HR ${v?.hr??'--'} bpm, SpO₂ ${v?.spo2??'--'}%, Temp ${v?.temp??'--'}°C | LVEF ${patient.cardiology?.echo?.ef??'--'}%`,recommendation:patient.handover?.recommendation||note?.plan||'Continue current monitoring and clinical plan.'};};
 const[draft,setDraft]=useState<Draft>(makeDraft);const[editing,setEditing]=useState(!readOnly);const[notice,setNotice]=useState(false);
 useEffect(()=>{setDraft(makeDraft());setEditing(!readOnly);},[patient.id,patient.handover?.updatedAt,readOnly]);
 const save=()=>{updatePatient(patient.id,{handover:{...draft,updatedAt:new Date().toISOString()}});setEditing(false);setNotice(true);showToast('Handover updated successfully.','success');window.setTimeout(()=>setNotice(false),2200);};
 const field=(key:keyof Draft,label:string,accent:string)=><label className="block text-xs font-bold text-slate-600 dark:text-slate-300"><span className={`inline-block mb-1 ${accent}`}>{label}</span><textarea disabled={!editing} value={draft[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))} rows={4} className={`w-full rounded-xl border px-3 py-2.5 text-sm outline-none transition ${editing?'bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-700 focus:border-cyan-500':'bg-slate-50 dark:bg-slate-900/60 border-slate-200 dark:border-slate-800'} text-slate-900 dark:text-white resize-y disabled:opacity-100`} /> </label>;
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 backdrop-blur-sm p-3 sm:p-5" style={{paddingTop:'max(0.75rem, env(safe-area-inset-top, 0px))',paddingBottom:'max(0.75rem, env(safe-area-inset-bottom, 0px))'}}><div className="w-full max-w-3xl max-h-[calc(100vh-1.5rem)] overflow-y-auto rounded-3xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 shadow-2xl">
  <div className="sticky top-0 z-10 flex items-center justify-between gap-3 px-4 sm:px-6 py-4 bg-white/95 dark:bg-[#111C2E]/95 backdrop-blur border-b border-slate-200 dark:border-slate-800"><div className="min-w-0"><div className="flex items-center gap-2"><ClipboardList className="w-5 h-5 text-cyan-500 shrink-0"/><h2 className="text-base sm:text-lg font-black truncate">Patient Handover</h2></div><p className="text-[11px] text-slate-500 dark:text-slate-400 truncate">{patient.fullName} • MRN {patient.mrn} • {patient.status}</p></div><button onClick={onClose} className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500 shrink-0" title="Close"><X className="w-5 h-5"/></button></div>
  <div className="p-4 sm:p-6 space-y-4">{field('situation','Situation','text-rose-500')}{field('background','Background','text-amber-500')}{field('assessment','Assessment','text-cyan-500')}{field('recommendation','Recommendation','text-emerald-500')}
   <div className="flex flex-wrap items-center justify-end gap-2 pt-2"><span className={`mr-auto text-xs font-semibold text-emerald-600 transition-opacity ${notice?'opacity-100':'opacity-0'}`}><Check className="inline w-4 h-4 mr-1"/>Saved</span>{readOnly?null:editing?<><button onClick={()=>{setDraft(makeDraft());setEditing(false)}} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold">Cancel</button><button onClick={save} className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Save className="w-4 h-4"/>Save Handover</button></>:<button onClick={()=>setEditing(true)} className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold"><Edit3 className="w-4 h-4 text-cyan-500"/>Edit Handover</button>}</div>
  </div>
 </div></div>;
};
