import React,{useEffect,useState}from'react';
import {ArrowLeft,Edit,ArrowRightLeft,LogOut,ChevronDown}from'lucide-react';
import {useApp}from'../../context/AppContext';
import {Patient,PatientStatus}from'../../types/clinical';
interface PatientFileHeaderProps{patient:Patient;onEditClick?:()=>void;readOnly?:boolean;}
export const PatientFileHeader:React.FC<PatientFileHeaderProps>=({patient,onEditClick,readOnly=false})=>{const{setCurrentView,getUnitById,beds,units,transferPatient,dischargePatient,updatePatient}=useApp();const[showTransferModal,setShowTransferModal]=useState(false);const[showDischargeModal,setShowDischargeModal]=useState(false);const[compact,setCompact]=useState(false);const[targetUnitId,setTargetUnitId]=useState(patient.unitId);const[targetBedId,setTargetBedId]=useState('');const[dischargeReason,setDischargeReason]=useState('Discharged Home');const[dischargeSummary,setDischargeSummary]=useState('');const currentUnit=getUnitById(patient.unitId);const currentBed=beds.find(b=>b.id===patient.bedId);const availableBeds=beds.filter(b=>b.unitId===targetUnitId&&!b.patientId);
 useEffect(()=>{let frame=0;const onScroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{setCompact(window.scrollY>72);frame=0;});};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',onScroll);};},[]);
 const handleTransfer=(e:React.FormEvent)=>{e.preventDefault();if(!targetBedId)return;transferPatient(patient.id,targetUnitId,targetBedId);setShowTransferModal(false);};const handleDischarge=(e:React.FormEvent)=>{e.preventDefault();dischargePatient(patient.id,dischargeReason,dischargeSummary);setShowDischargeModal(false);};const handleStatusChange=(newStatus:PatientStatus)=>{if(!readOnly)updatePatient(patient.id,{status:newStatus});};const openTransfer=()=>{setTargetUnitId(patient.unitId);setTargetBedId('');setShowTransferModal(true)};
 return <>
 <div className="sticky z-40 w-full bg-white/96 dark:bg-[#111C2E]/96 backdrop-blur-xl border-b border-slate-200/90 dark:border-slate-800/90 shadow-sm transition-[height,box-shadow] duration-700 ease-[cubic-bezier(.16,1,.3,1)]" style={{top:'3.65rem'}}>
  <div className="max-w-7xl mx-auto w-full px-3 sm:px-6 overflow-hidden transition-[height] duration-700 ease-[cubic-bezier(.16,1,.3,1)]" style={{height:compact?'4.05rem':'8.35rem'}}>
   <div className="h-full relative">
    <div className={`absolute inset-x-0 top-0 flex items-center gap-2.5 transition-[opacity,transform] duration-700 ease-[cubic-bezier(.16,1,.3,1)] ${compact?'opacity-100 translate-y-0':'opacity-0 -translate-y-4 pointer-events-none'}`} style={{height:'4.05rem'}}>
      <button onClick={()=>setCurrentView(readOnly?'archive':'census')} className="rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 p-2 shrink-0 transition-colors"><ArrowLeft className="w-5 h-5"/></button>
      <div className="relative shrink-0">{patient.photoUrl?<img src={patient.photoUrl} alt="" referrerPolicy="no-referrer" className="w-9 h-9 rounded-xl object-cover ring-2 ring-cyan-500/40 transition-all duration-700 ease-[cubic-bezier(.16,1,.3,1)]"/>:<div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-cyan-600 to-sky-400 text-white font-bold text-sm flex items-center justify-center">{patient.fullName.charAt(0)}</div>}{patient.status==='Critical'&&<span className="absolute -top-1 -right-1 w-3 h-3 bg-rose-500 border-2 border-white dark:border-[#111C2E] rounded-full"/>}</div>
      <div className="min-w-0 flex-1"><div className="flex items-center gap-2 min-w-0"><h1 className="text-sm sm:text-base font-extrabold truncate">{patient.fullName}</h1>{readOnly?<span className="hidden sm:inline-flex text-[9px] font-bold px-2 py-1 rounded-full bg-amber-500/15 text-amber-600 shrink-0">READ ONLY</span>:<span className={`text-[9px] font-black px-2 py-1 rounded-full shrink-0 ${patient.status==='Critical'?'bg-rose-500/15 text-rose-500':patient.status==='Unstable'?'bg-amber-500/15 text-amber-500':'bg-emerald-500/15 text-emerald-500'}`}>{patient.status}</span>}</div><div className="text-[10px] text-slate-400 truncate mt-0.5">MRN {patient.mrn} • {currentUnit?.name||'Unit'} • Bed {currentBed?.bedNumber||'—'}</div></div>
      {!readOnly&&<div className="hidden sm:flex items-center gap-1.5 shrink-0"><button onClick={onEditClick} className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800"><Edit className="w-4 h-4 text-cyan-500"/></button><button onClick={openTransfer} className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800"><ArrowRightLeft className="w-4 h-4 text-sky-500"/></button><button onClick={()=>setShowDischargeModal(true)} className="p-2 rounded-xl bg-rose-50 dark:bg-rose-950/30 text-rose-600"><LogOut className="w-4 h-4"/></button></div>}
    </div>
    <div className={`absolute inset-x-0 top-0 transition-[opacity,transform] duration-700 ease-[cubic-bezier(.16,1,.3,1)] ${compact?'opacity-0 translate-y-4 pointer-events-none':'opacity-100 translate-y-0'}`} style={{height:'8.35rem'}}>
      <div className="flex items-center gap-2.5 pt-3"><button onClick={()=>setCurrentView(readOnly?'archive':'census')} className="rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 p-2 shrink-0"><ArrowLeft className="w-5 h-5"/></button><div className="relative shrink-0">{patient.photoUrl?<img src={patient.photoUrl} alt="" referrerPolicy="no-referrer" className="w-12 h-12 rounded-2xl object-cover ring-2 ring-cyan-500/40 shadow-md"/>:<div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-cyan-600 to-sky-400 text-white font-bold text-lg flex items-center justify-center shadow-md">{patient.fullName.charAt(0)}</div>}{patient.status==='Critical'&&<span className="absolute -top-1 -right-1 w-3 h-3 bg-rose-500 border-2 border-white dark:border-[#111C2E] rounded-full"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 min-w-0"><h1 className="text-lg sm:text-xl font-extrabold truncate">{patient.fullName}</h1>{readOnly?<span className="text-[9px] font-bold px-2 py-1 rounded-full bg-amber-500/15 text-amber-600 shrink-0">ARCHIVED • READ ONLY</span>:<div className="relative shrink-0"><select value={patient.status} onChange={e=>handleStatusChange(e.target.value as PatientStatus)} className={`appearance-none text-[10px] sm:text-xs font-bold px-2.5 py-1 rounded-full border pr-6 ${patient.status==='Critical'?'bg-rose-500/15 text-rose-500 border-rose-500/40':patient.status==='Unstable'?'bg-amber-500/15 text-amber-500 border-amber-500/40':'bg-emerald-500/15 text-emerald-500 border-emerald-500/40'}`}><option>Critical</option><option>Unstable</option><option>Stable</option></select><ChevronDown className="absolute right-1.5 top-1/2 -translate-y-1/2 w-3 h-3 pointer-events-none"/></div>}</div><div className="text-[10px] sm:text-xs text-slate-500 dark:text-slate-400 mt-1 truncate">MRN: <b>{patient.mrn}</b> • {currentUnit?.name||'Unit'} • Bed {currentBed?.bedNumber||'Archived'} • {patient.age}y / {patient.sex}</div></div></div>
      <div className="flex items-center justify-between gap-2 mt-3"><div className="min-w-0 text-[10px] sm:text-xs text-slate-500 truncate"><b className="text-slate-700 dark:text-slate-300">Diagnosis:</b> {patient.primaryDiagnosis||'Not documented'}</div>{!readOnly&&<div className="flex items-center gap-1.5 shrink-0"><button onClick={onEditClick} className="flex items-center gap-1 rounded-xl bg-slate-100 dark:bg-slate-800 px-2.5 py-1.5 text-[10px] font-bold"><Edit className="w-3 h-3 text-cyan-500"/>Edit</button><button onClick={openTransfer} className="flex items-center gap-1 rounded-xl bg-slate-100 dark:bg-slate-800 px-2.5 py-1.5 text-[10px] font-bold"><ArrowRightLeft className="w-3 h-3 text-sky-500"/>Transfer</button><button onClick={()=>setShowDischargeModal(true)} className="flex items-center gap-1 rounded-xl bg-rose-50 dark:bg-rose-950/30 text-rose-600 px-2.5 py-1.5 text-[10px] font-bold"><LogOut className="w-3 h-3"/>Discharge</button></div>}</div>
    </div>
   </div>
  </div>
 </div>
 {showTransferModal&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl p-5 space-y-4 max-h-[calc(100vh-2rem)] overflow-y-auto"><h3 className="text-lg font-bold">Transfer {patient.fullName}</h3><form onSubmit={handleTransfer} className="space-y-4"><select value={targetUnitId} onChange={e=>{setTargetUnitId(e.target.value);setTargetBedId('')}} className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option value="">Select Unit</option>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.type})</option>)}</select><select required value={targetBedId} onChange={e=>setTargetBedId(e.target.value)} className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option value="">Select Bed</option>{availableBeds.map(b=><option key={b.id} value={b.id}>{b.bedNumber}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowTransferModal(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-4 py-2 rounded-xl bg-sky-500 text-white text-xs font-bold">Confirm Transfer</button></div></form></div></div>}
 {showDischargeModal&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl p-5 space-y-4 max-h-[calc(100vh-2rem)] overflow-y-auto"><h3 className="text-lg font-bold">Discharge & Archive Patient</h3><form onSubmit={handleDischarge} className="space-y-4"><select value={dischargeReason} onChange={e=>setDischargeReason(e.target.value)} className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border"><option>Discharged Home</option><option>Transferred to Ward</option><option>Transferred to Rehab</option><option>Deceased</option><option>Left AMA</option></select><textarea rows={4} value={dischargeSummary} onChange={e=>setDischargeSummary(e.target.value)} placeholder="Discharge clinical summary..." className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowDischargeModal(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-4 py-2 rounded-xl bg-rose-500 text-white text-xs font-bold">Discharge to Archive</button></div></form></div></div>}
 </>;
};