import React,{useState} from 'react';
import {ClipboardPlus,X} from 'lucide-react';
import {Patient,ProgressNote} from '../../types/clinical';
import {useApp} from '../../context/AppContext';

interface Props{patient:Patient;onClose:()=>void;}
export const QuickClinicalRecord:React.FC<Props>=({patient,onClose})=>{
 const{updatePatient,showToast,auth}=useApp();const[text,setText]=useState('');const[type,setType]=useState('Quick Clinical Record');
 const save=()=>{const value=text.trim();if(!value)return;const now=new Date();const note:ProgressNote={id:`quick-${Date.now()}`,date:now.toISOString().split('T')[0],time:now.toTimeString().slice(0,5),author:auth.userName||'Physician',type,subjective:'',objective:'',assessment:value,plan:value,updatedAt:now.toISOString()};updatePatient(patient.id,{progressNotes:[note,...(patient.progressNotes||[])]});showToast('Clinical record saved to Progress Notes and Timeline.','success');onClose();};
 return <div className="fixed inset-0 z-[110] bg-slate-950/60 backdrop-blur-sm p-3 flex items-end sm:items-center justify-center"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-[#0E1626] border border-slate-200 dark:border-slate-800 shadow-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="text-base font-extrabold text-slate-900 dark:text-white flex items-center gap-2"><ClipboardPlus className="w-5 h-5 text-cyan-500"/>Quick Clinical Record</h2><p className="text-[11px] text-slate-400">Saved as a dated Progress Note and shown in the patient timeline.</p></div><button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4"/></button></div><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Record type<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-3 py-2.5 text-sm"><option>Quick Clinical Record</option><option>Rounding Update</option><option>Clinical Event</option><option>Consultation Update</option><option>Important Observation</option></select></label><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Document the important clinical event, observation, response, or update…" className="mt-3 w-full min-h-[170px] resize-y rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-4 py-3 text-sm outline-none focus:border-cyan-500 text-slate-900 dark:text-white"/><div className="flex justify-end gap-2 mt-4"><button onClick={onClose} className="px-4 py-2.5 rounded-xl text-xs font-bold border border-slate-200 dark:border-slate-700">Cancel</button><button disabled={!text.trim()} onClick={save} className="px-5 py-2.5 rounded-xl bg-cyan-500 disabled:opacity-40 text-white text-xs font-bold">Save Record</button></div></div></div>;
};
