import React, { useMemo, useState } from 'react';
import { jsPDF } from 'jspdf';
import { FileDown, Printer, Copy, Check, FileText } from 'lucide-react';
import { Capacitor } from '@capacitor/core';
import { Directory, Filesystem } from '@capacitor/filesystem';
import { Patient } from '../../../types/clinical';
import { useApp } from '../../../context/AppContext';

type SectionKey = 'overview'|'history'|'vitals'|'ecg'|'examination'|'cardiology'|'medications'|'icu'|'imaging'|'labs'|'procedures'|'calculators'|'progress';
const sectionIds: SectionKey[] = ['overview','history','vitals','ecg','examination','cardiology','medications','icu','imaging','labs','procedures','calculators','progress'];
const labels: Record<SectionKey,string> = { overview:'Overview', history:'History', vitals:'Vital Signs & Fluid Balance', ecg:'ECG', examination:'Examination', cardiology:'Cardiology & Echocardiography', medications:'Medications', icu:'ICU / Ventilator & ABG', imaging:'Imaging & Cardiac Studies', labs:'Laboratory Results', procedures:'Procedures & Interventions', calculators:'Clinical Calculators', progress:'Progress Notes' };
interface Props { patient: Patient; }
interface Row { label:string; value:string; }
const text=(v:any,fallback='—')=>v===undefined||v===null||v===''?fallback:Array.isArray(v)?(v.length?v.join(', '):fallback):typeof v==='boolean'?(v?'Yes':'No'):String(v);
const yesNo=(v:boolean|undefined)=>v===undefined?'—':v?'Yes':'No';
const latest=<T,>(arr:T[]|undefined)=>arr&&arr.length?arr[arr.length-1]:undefined;
const formatDate=(d:string|undefined)=>d?d.replace('T',' '):'—';

async function imageToPng(src:string){
  try{
    let data=src;
    if(!/^data:image\//i.test(src)){
      const r=await fetch(src); if(!r.ok) throw new Error(`HTTP ${r.status}`);
      const b=await r.blob();
      data=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=()=>reject(f.error);f.readAsDataURL(b);});
    }
    const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Image decode failed'));i.src=data;});
    const w=img.naturalWidth||1200,h=img.naturalHeight||800,c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)return null;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);return {data:c.toDataURL('image/png'),width:w,height:h};
  }catch(e){console.warn('PDF image failed',e);return null;}
}

export const ExportSummarySection:React.FC<Props>=({patient})=>{
 const {units,beds,showToast}=useApp();
 const [selected,setSelected]=useState<SectionKey[]>(sectionIds);
 const [copied,setCopied]=useState(false);
 const [busy,setBusy]=useState(false);
 const unit=units.find(u=>u.id===patient.unitId); const bed=beds.find(b=>b.id===patient.bedId);
 const previews=useMemo(()=>selected.map(id=>({id,label:labels[id]})),[selected]);
 const toggle=(id:SectionKey)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const copy=async()=>{try{await navigator.clipboard.writeText(`[SBAR] ${patient.fullName} | ${unit?.name||'Unit'} ${bed?.bedNumber||''}\nDiagnosis: ${patient.primaryDiagnosis}\nStatus: ${patient.status}`);setCopied(true);showToast('SBAR copied.','success');setTimeout(()=>setCopied(false),1800);}catch{showToast('Clipboard access unavailable.','error');}};

 const exportPdf=async()=>{
  if(!selected.length){showToast('Select at least one section.','error');return;}
  setBusy(true);
  try{
   const doc=new jsPDF({unit:'mm',format:'a4',compress:true});
   const M=12,W=186,RIGHT=198,TOP=34,BOTTOM=278;
   let page=1,y=39;
   const resetPage=()=>{y=39;};
   const header=()=>{
    doc.setFillColor(255,255,255);doc.rect(0,0,210,297,'F');
    doc.setTextColor(10,32,57);doc.setFont('helvetica','bold');doc.setFontSize(21);doc.text('Cardio',M,14);doc.setTextColor(16,128,136);doc.text('Vault',M+35,14);
    doc.setFontSize(8.6);doc.setTextColor(10,32,57);doc.text('ICU / CCU Clinical Patient Report',M,21);doc.setFont('helvetica','normal');doc.setFontSize(6.3);doc.setTextColor(82,94,105);doc.text('Organize Care. Improve Outcomes.',M,27);
    doc.setFont('helvetica','bold');doc.setTextColor(184,28,34);doc.setFontSize(8.2);doc.text('CONFIDENTIAL',RIGHT-34,10);doc.setFont('helvetica','normal');doc.setTextColor(82,94,105);doc.text('Medical Document',RIGHT-34,16);doc.text(`Generated: ${new Date().toLocaleString()}`,RIGHT-55,22);
    doc.setDrawColor(20,92,113);doc.setLineWidth(.55);doc.line(M,31,RIGHT,31);
   };
   const footer=()=>{doc.setDrawColor(180,194,201);doc.setLineWidth(.35);doc.line(M,282,RIGHT,282);doc.setFont('helvetica','bold');doc.setFontSize(6.8);doc.setTextColor(45,69,83);doc.text('CardioVault',M,288);doc.setFont('helvetica','normal');doc.text(' ICU / CCU Clinical Notebook',M+22,288);doc.text('Confidential Medical Document',M,293);doc.text('Better Data.   Better Decisions.',RIGHT-50,288);doc.text(`Page ${page}`,RIGHT-15,293);};
   const newPage=()=>{footer();doc.addPage();page++;header();resetPage();};
   const ensure=(h:number)=>{if(y+h>BOTTOM)newPage();};
   const section=(title:string,icon='')=>{ensure(14);doc.setFillColor(226,242,246);doc.setDrawColor(161,194,203);doc.roundedRect(M,y,W,9,1.3,1.3,'FD');doc.setTextColor(7,68,92);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(`${icon}${icon?'  ':''}${title}`,M+5,y+6.1);y+=12;};
   const sub=(title:string)=>{ensure(9);doc.setFont('helvetica','bold');doc.setFontSize(7.8);doc.setTextColor(18,77,99);doc.text(title,M,y+5);y+=8;};
   const block=(title:string,body:string,accent=false)=>{if(!body||body==='—')return;const lines=doc.splitTextToSize(body,accent?W-10:W-8) as string[];const h=Math.max(10,lines.length*3.7+7);ensure(h);doc.setFillColor(accent?249:248,accent?236:250,accent?236:252);doc.setDrawColor(accent?218:214,accent?195:225,accent?195:230);doc.roundedRect(M,y,W,h,1.4,1.4,'FD');doc.setFont('helvetica','bold');doc.setFontSize(7);doc.setTextColor(accent?160:22,accent?36:61,accent?42:78);doc.text(title,M+4,y+5);doc.setFont('helvetica','normal');doc.setFontSize(7.1);doc.setTextColor(35,47,57);doc.text(lines,M+4,y+9);y+=h+3;};
   const twoCol=(left:[string,string][],right:[string,string][])=>{const colW=(W-5)/2;let maxH=10;const calc=(items:[string,string][])=>items.reduce((h,[k,v])=>{if(!v||v==='—')return h;const lines=doc.splitTextToSize(v,colW-35) as string[];return h+Math.max(7,lines.length*3.4+5);},5);maxH=Math.max(calc(left),calc(right));ensure(maxH);const x2=M+colW+5;const draw=(x:number,items:[string,string][])=>{let yy=y;for(const [k,v] of items){if(!v||v==='—')continue;const lines=doc.splitTextToSize(v,colW-35) as string[];const h=Math.max(7,lines.length*3.4+5);doc.setFillColor(250,252,253);doc.setDrawColor(215,227,231);doc.roundedRect(x,yy,colW,h,1,1,'FD');doc.setFont('helvetica','bold');doc.setFontSize(6.6);doc.setTextColor(28,70,87);doc.text(k,x+3,yy+4.3);doc.setFont('helvetica','normal');doc.setFontSize(6.8);doc.setTextColor(40,48,55);doc.text(lines,x+35,yy+4.3);yy+=h+1.5;}};draw(M,left);draw(x2,right);y+=maxH+3;};
   const table=(headers:string[],rows:string[][],widths?:number[])=>{if(!rows.length)return;const total=W;const ws=widths||headers.map(()=>total/headers.length);let yy=y;const headH=7;ensure(headH+8);let x=M;doc.setFillColor(229,241,245);doc.setDrawColor(180,204,212);doc.rect(M,yy,total,headH,'FD');doc.setFont('helvetica','bold');doc.setFontSize(6.2);doc.setTextColor(18,63,80);headers.forEach((h,i)=>{doc.text(h,x+2,yy+4.6);x+=ws[i];});yy+=headH;rows.forEach(row=>{const cells=row.map((v,i)=>doc.splitTextToSize(v||'—',ws[i]-4) as string[]);const h=Math.max(6.5,...cells.map(c=>c.length*3.1+3));if(yy+h>BOTTOM){footer();doc.addPage();page++;header();yy=39;doc.setFillColor(229,241,245);doc.rect(M,yy,total,headH,'FD');x=M;doc.setFont('helvetica','bold');doc.setFontSize(6.2);headers.forEach((h2,i)=>{doc.text(h2,x+2,yy+4.6);x+=ws[i];});yy+=headH;}x=M;doc.setFillColor(255,255,255);doc.setDrawColor(218,228,232);doc.rect(M,yy,total,h,'FD');doc.setFont('helvetica','normal');doc.setFontSize(6.2);doc.setTextColor(40,49,57);cells.forEach((c,i)=>{doc.text(c,x+2,yy+4.2);x+=ws[i];});yy+=h;});y=yy+4;};
   const addImage=async(src:string,label:string)=>{const im=await imageToPng(src);if(!im)return;const maxW=W-4,maxH=92,scale=Math.min(maxW/im.width,maxH/im.height);const iw=im.width*scale,ih=im.height*scale;ensure(ih+13);doc.setFont('helvetica','bold');doc.setFontSize(6.8);doc.setTextColor(13,74,96);doc.text(label,M,y+4.5);doc.addImage(im.data,'PNG',M,y+7,iw,ih,undefined,'FAST');y+=ih+11;};
   const identity=()=>{
    ensure(34);doc.setFillColor(247,250,252);doc.setDrawColor(188,205,212);doc.roundedRect(M,37,W,27,2,2,'FD');
    doc.setFont('helvetica','bold');doc.setFontSize(14);doc.setTextColor(8,31,54);doc.text(text(patient.fullName,'Unnamed Patient'),M+6,46);
    doc.setFont('helvetica','normal');doc.setFontSize(7.2);doc.setTextColor(35,52,63);doc.text(`MRN: ${text(patient.mrn)}    Age: ${text(patient.age)} years    Gender: ${text(patient.sex)}`,M+6,52);doc.text(`Unit: ${text(unit?.name)}    Bed: ${text(bed?.bedNumber)}    Admission: ${text(patient.admissionDate)} ${text(patient.admissionTime)}`,M+6,57);doc.text(`Attending: ${text((patient as any).attendingPhysician)}    Service: Cardiology / CCU`,M+6,62);doc.setFillColor(patient.status==='Critical'?218:229,patient.status==='Critical'?56:241,patient.status==='Critical'?62:245);doc.roundedRect(RIGHT-31,40,25,8,3,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(7);doc.setTextColor(255,255,255);doc.text(text(patient.status,'Active'),RIGHT-27,45.4);y=69;
   };
   const overview=()=>{section('Overview','✚');twoCol([['Primary Diagnosis',text(patient.primaryDiagnosis)],['Secondary Diagnoses',text(patient.secondaryDiagnoses)],['Allergies',text(patient.allergies)],['Code Status',text(patient.codeStatus)]],[['Admission Date & Time',`${text(patient.admissionDate)} ${text(patient.admissionTime)}`],['Unit / Bed',`${text(unit?.name)} / ${text(bed?.bedNumber)}`],['Weight',patient.weight?`${patient.weight} kg`:'—'],['Height',patient.height?`${patient.height} cm`:'—']]);const s:any=patient.clinicalSummary||{};block('Brief Clinical Summary',`Chief Complaint: ${text(s.chiefComplaint)}\nHistory of Present Illness: ${text(s.hpi)}`);block('Past Medical / Surgical History',`Past Medical History: ${text(s.pmh)}\nPast Surgical History: ${text(s.psh)}\nDrug History: ${text(s.drugHistory)}`);};
   const history=()=>{section('Brief Clinical History','▤');const s:any=patient.clinicalSummary||{},c:any=patient.cardiovascularHistory||{};block('Chief Complaint',text(s.chiefComplaint));block('History of Present Illness',text(s.hpi));twoCol([['Past Medical History',text(s.pmh)],['Past Surgical History',text(s.psh)],['Drug History',text(s.drugHistory)]],[['Family History',text(s.familyHistory)],['Social History',text(s.socialHistory)],['Cardiovascular Risk Factors',[c.hypertension?'HTN':'',c.diabetes?'DM':'',c.dyslipidemia?'Dyslipidemia':'',c.smoking?'Smoking':'',c.alcohol?'Alcohol':''].filter(Boolean).join(', ')||'—']]);if(c.previousAdmissions||c.previousICU||c.other)block('Previous Admissions / Other',`Previous Admissions: ${text(c.previousAdmissions)}\nPrevious ICU: ${text(c.previousICU)}\nOther: ${text(c.other)}`);};
   const vitals=()=>{section('Vital Signs & Fluid Balance','⌁');const v:any=latest(patient.vitalsHistory);if(v){table(['BP','HR','RR','SpO₂','Temp','GCS'],[[`${text(v.sbp)}/${text(v.dbp)} mmHg`,`${text(v.hr)} bpm`,`${text(v.rr)} /min`,`${text(v.spo2)} %`,`${text(v.temp)} °C`,`${text(v.gcsTotal)} /15`]]);}const fluid:any=latest(patient.fluidRecords);const intake=(patient.fluidIntakeHistory||[]).reduce((n:any,r:any)=>n+Number(r.amount||0),0);const urine=(patient.urineOutputHistory||[]).reduce((n:any,r:any)=>n+Number(r.amount||0),0);twoCol([['Fluid Intake',fluid?.totalIntake?`${fluid.totalIntake} mL`:(intake?`${intake} mL`:'—')],['Urine Output',fluid?.urineOutput?`${fluid.urineOutput} mL`:(urine?`${urine} mL`:'—')],['Net Balance',fluid?.netBalance!==undefined?`${fluid.netBalance} mL`:(intake||urine?`${intake-urine} mL`:'—')]],(patient.hemodynamicHistory||[]).slice(-6).map((h:any)=>[text(h.parameter),`${text(h.value)} ${text(h.unit)}`]) as [string,string][]);if((patient.vitalsHistory||[]).length>1)table(['Date / Time','BP','HR','RR','SpO₂','GCS'],patient.vitalsHistory.map((r:any)=>[formatDate(r.timestamp),`${text(r.sbp)}/${text(r.dbp)}`,text(r.hr),text(r.rr),text(r.spo2),text(r.gcsTotal)]).slice(-12));};
   const examination=()=>{section('Physical Examination','♙');const e:any=patient.examination||{};twoCol([['General',`${text(e.general?.appearance)}; ${text(e.general?.consciousness)}`],['Cardiovascular',`${text(e.cardiovascular?.heartSounds)}; ${text(e.cardiovascular?.murmurs)}`],['JVP / Perfusion',`${text(e.cardiovascular?.jvp)}; ${text(e.cardiovascular?.perfusion)}`]],[['Respiratory',`${text(e.respiratory?.chestExam)}; ${text(e.respiratory?.airEntry)}`],['Abdomen',`${text(e.abdomen?.palpation)}; ${text(e.abdomen?.tenderness)}`],['Neurological',`${text(e.neurological?.consciousness)}; GCS ${text(e.neurological?.gcs)}`]]);if(e.customFields?.length)table(['Finding','Value'],e.customFields.map((x:any)=>[text(x.label),text(x.value)]));};
   const ecg=async()=>{section('ECG','⌁');const r:any=latest(patient.ecgRecords);if(!r){block('ECG','No ECG record documented.');return;}twoCol([['Date / Time',`${text(r.date)} ${text(r.time)}`],['Heart Rate',text(r.heartRate)],['Rhythm',text(r.rhythm)],['Regularity',text(r.regularity)],['Axis',text(r.axis)]],[['PR',text(r.pr)],['QRS',text(r.qrs)],['QT / QTc',`${text(r.qt)} / ${text(r.qtc)}`],['ST / T Waves',`${text(r.stSegment)} / ${text(r.tWave)}`],['Final Impression',text(r.finalImpression)]]);if(r.qrsFindings||r.otherFindings)block('Findings',`QRS: ${text(r.qrsFindings)}\nOther: ${text(r.otherFindings)}`);for(const src of r.imageUrls||[])await addImage(src,'ECG image');};
   const cardiology=async()=>{section('Cardiology & Echocardiography','♥');const c:any=patient.cardiology||{},e:any=c.echo||{};twoCol([['Rhythm',text(c.rhythm)],['Heart Rate',text(c.heartRate)],['Blood Pressure',text(c.bp)],['Heart Failure',text(c.heartFailureStatus)],['NYHA / Killip',`${text(c.nyha||c.nyhaClass)} / ${text(c.killip||c.killipClass)}`]],[['Congestion',text(c.congestion)],['Perfusion',text(c.perfusion)],['EF',e.ef?`${e.ef}%`:'—'],['ROMA',text((e as any).roma)],['Echo Brief Summary',text(c.echoBriefSummary)]]);block('Echocardiography',`LV Dimensions: ${text(e.lvDimensions)}\nLV Function: ${text(e.lvFunction)}\nRV Function: ${text(e.rvFunction)}\nRWMA: ${text(e.rwma)}\nValves: MR ${text(e.mr)} | AR ${text(e.ar)} | AS ${text(e.as)} | MS ${text(e.ms)} | TR ${text(e.tr)} | PR ${text(e.pr)}\nPASP: ${text(e.pasp)}\nOther Findings: ${text(e.otherFindings)}`);block('Coronary / Biomarkers / Antithrombotic',`Cath: ${text(c.coronary?.cath)}\nCoronary Findings: ${text(c.coronary?.coronaryFindings)}\nPCI: ${text(c.coronary?.pci)}\nStent: ${text(c.coronary?.stent)}\nCABG: ${text(c.coronary?.cabg)}\nTroponin: ${text(c.biomarkers?.troponin)} | CK-MB: ${text(c.biomarkers?.ckmb)} | BNP: ${text(c.biomarkers?.bnp)}\nAntiplatelet: ${text(c.antithrombotic?.antiplatelet)} | Anticoagulation: ${text(c.antithrombotic?.anticoagulation)}`);if(c.cathRecords?.length)table(['Date','Indication','Findings','Intervention','Result'],c.cathRecords.map((r:any)=>[text(r.date),text(r.indication),text(r.findings),text(r.intervention),text(r.finalResult)]));if(c.devicesList?.length)table(['Device','Date','Status','Notes'],c.devicesList.map((r:any)=>[text(r.type),text(r.date),text(r.status),text(r.notes)]));};
   const medications=()=>{section('Medications (Current)','⚕');const rows=(patient.medications||[]).map((m:any)=>[text(m.drug||m.name),text(m.dose),text(m.route),text(m.frequency),text(m.indication),text(m.status)]);table(['Name','Dose','Route','Frequency','Indication','Status'],rows,[34,25,20,25,52,30]);};
   const labs=()=>{section('Laboratory Results','⚗');const panels:any[]=patient.labs||[];const p:any=latest(panels);if(p){const rows=[['Hemoglobin',p.hb,'g/dL'],['WBC',p.wbc,'10³/µL'],['Platelets',p.platelets,'10³/µL'],['Sodium',p.na,'mmol/L'],['Potassium',p.k,'mmol/L'],['Creatinine',p.creatinine,'mg/dL'],['Troponin I',p.troponin,'ng/mL'],['INR',p.inr,'']].filter((r:any)=>r[1]!==undefined&&r[1]!==null&&r[1]!==0);table(['Test','Result','Unit'],rows as string[][],[70,48,68]);}const results:any[]=(patient as any).labResults||[];if(results.length)table(['Test','Result','Unit','Reference','Date'],results.map(r=>[text(r.name||r.testName),text(r.value),text(r.unit),text(r.referenceRange),formatDate(r.timestamp)]));};
   const imaging=async()=>{section('Imaging & Cardiac Studies','▣');for(const r of patient.imaging||[]){block(`${text((r as any).type||r.modality||'Imaging Study')} — ${text((r as any).bodyRegion||r.region)}`,`Date: ${text(r.date)}\nIndication: ${text(r.indication)}\nFindings: ${text(r.findings)}\nImpression: ${text(r.impression)}\nRadiologist: ${text(r.radiologist)}\nNotes: ${text(r.notes)}`);for(const src of ((r as any).imageUrls||r.images||[]))await addImage(src,`${text((r as any).type||r.modality||'Imaging')} image`);}};
   const procedures=()=>{section('Procedures & Interventions','⚕');table(['Date / Time','Procedure','Indication','Performed By','Outcome'],(patient.procedures||[]).map((r:any)=>[`${text(r.date)} ${text(r.time)}`,text(r.procedure||r.name||r.surgeryName),text(r.indication),text(r.operator),text(r.outcome||r.complications)]),[28,48,43,32,35]);};
   const icu=()=>{section('ICU / Ventilator & ABG','▥');const v:any=patient.ventilator||{};twoCol([['Mode',text(v.mode)],['FiO₂',v.fio2!==undefined?`${v.fio2}%`:'—'],['PEEP',text(v.peep)],['Tidal Volume',text(v.tidalVolume)],['RR',text(v.rr)],['Pressure Support',text(v.pressureSupport)]],[['Peak Pressure',text(v.peakPressure)],['Plateau Pressure',text(v.plateauPressure)],['Mean Airway Pressure',text(v.meanAirwayPressure)],['SpO₂',text(v.spo2)],['EtCO₂',text(v.etco2)],['Compliance / Resistance',`${text(v.compliance)} / ${text(v.resistance)}`]]);const abg:any=latest(v.abgHistory);if(abg)block('Latest ABG',`pH ${text(abg.ph)} | PaCO₂ ${text(abg.paco2)} | PaO₂ ${text(abg.pao2)} | HCO₃ ${text(abg.hco3)} | BE ${text(abg.baseExcess||abg.be)} | Lactate ${text(abg.lactate)}\nFiO₂ ${text(abg.fio2)} | P/F ${text(abg.pfRatio)}\nInterpretation: ${text(abg.interpretation)}`);if(v.abgHistory?.length)table(['Date / Time','pH','PaCO₂','PaO₂','HCO₃','Lactate'],v.abgHistory.map((r:any)=>[formatDate(r.timestamp),text(r.ph),text(r.paco2),text(r.pao2),text(r.hco3),text(r.lactate)]));};
   const calculators=()=>{section('Clinical Calculators','▦');table(['Calculator','Result','Risk / Level','Interpretation'],(patient.calculatorResults||[]).map((r:any)=>[text(r.name||r.calculatorId),text(r.score),text(r.riskLevel),text(r.interpretation)]),[55,35,38,58]);};
   const progress=()=>{section('Progress Notes','▤');for(const r of patient.progressNotes||[]){block(`${text(r.date)} ${text(r.time)} — ${text(r.author)}`,`Type: ${text(r.type)}\nSubjective: ${text(r.subjective)}\nObjective: ${text(r.objective)}\nAssessment: ${text(r.assessment)}\nPlan: ${text(r.plan)}\nEvents: ${text(r.events)}\nInvestigations: ${text(r.investigations)}\nTreatment: ${text(r.treatment)}\nResponse: ${text(r.response)}`);}};

   header();identity();
   // The report uses the same clinical hierarchy as the supplied reference image.
   // Only checked sections are rendered; no placeholder/demo values are created.
   const order:SectionKey[]=['overview','history','vitals','examination','ecg','cardiology','labs','imaging','procedures','medications','icu','calculators','progress'];
   for(const id of order){if(!selected.includes(id))continue;if(id==='overview')overview();if(id==='history')history();if(id==='vitals')vitals();if(id==='examination')examination();if(id==='ecg')await ecg();if(id==='cardiology')await cardiology();if(id==='labs')labs();if(id==='imaging')await imaging();if(id==='procedures')procedures();if(id==='medications')medications();if(id==='icu')icu();if(id==='calculators')calculators();if(id==='progress')progress();}
   footer();
   const safe=`CardioVault_${(patient.fullName||'Patient').replace(/[^a-zA-Z0-9_-]+/g,'_')}_${new Date().toISOString().slice(0,10)}.pdf`;
   if(Capacitor.isNativePlatform()){const uri=doc.output('datauristring');const base64=uri.slice(uri.indexOf(',')+1);await Filesystem.writeFile({path:`CardioVault/${safe}`,data:base64,directory:Directory.Documents,recursive:true});showToast(`PDF saved to Documents/CardioVault/${safe}`,'success');}else{doc.save(safe);showToast('PDF downloaded successfully.','success');}
  }catch(e:any){console.error('PDF export failed',e);showToast(`PDF export failed: ${e?.message||'Unknown error'}`,'error');}finally{setBusy(false);}
 };
 return <div className="space-y-5">
  <div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900 dark:text-white">Clinical PDF Export</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Printed clinical report layout. Patient identity is always included; only selected sections are added.</p></div><FileText className="w-6 h-6 text-cyan-500"/></div>
  <div className="flex flex-wrap gap-2"><button onClick={()=>setSelected(sectionIds)} className="px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 text-xs font-bold">Select All</button><button onClick={()=>setSelected([])} className="px-3 py-2 rounded-lg bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-white text-xs font-bold">Deselect All</button></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">{sectionIds.map(id=>{const active=selected.includes(id);return <button key={id} onClick={()=>toggle(id)} className={`text-left p-3 rounded-xl border ${active?'border-cyan-500 bg-cyan-500/10':'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900'}`}><div className="flex items-center gap-2"><span className={`w-4 h-4 rounded border flex items-center justify-center text-[10px] ${active?'bg-cyan-500 border-cyan-500 text-slate-950':'border-slate-400'}`}>{active?'✓':''}</span><span className="text-sm font-semibold text-slate-800 dark:text-slate-100">{labels[id]}</span></div></button>;})}</div>
  <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0F172A] overflow-hidden"><div className="px-4 py-3 border-b border-slate-200 dark:border-slate-800"><p className="font-bold text-slate-900 dark:text-white">Print Layout</p><p className="text-xs text-slate-500">CardioVault clinical hierarchy — structured sections, tables, summaries and embedded ECG/imaging images.</p></div><div className="p-4 space-y-2">{previews.map(({id,label})=><div key={id} className="rounded-lg bg-slate-50 dark:bg-slate-900/70 px-3 py-2 text-xs font-semibold text-slate-800 dark:text-slate-100">{label}</div>)}{!selected.length&&<p className="text-sm text-slate-500 text-center py-8">Select one or more sections.</p>}</div></div>
  <div className="flex flex-wrap gap-2"><button disabled={busy||!selected.length} onClick={exportPdf} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 disabled:opacity-50 text-slate-950 font-bold text-sm"><FileDown className="w-4 h-4"/>{busy?'Creating Clinical PDF…':'Export PDF'}</button><button onClick={()=>window.print()} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-200 dark:bg-slate-800 text-slate-800 dark:text-white font-bold text-sm"><Printer className="w-4 h-4"/>Print</button><button onClick={copy} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-200 dark:bg-slate-800 text-slate-800 dark:text-white font-bold text-sm">{copied?<Check className="w-4 h-4"/>:<Copy className="w-4 h-4"/>}{copied?'Copied':'Copy SBAR'}</button></div>
 </div>;
};
