import React,{useMemo,useState} from 'react';
import {FlaskConical,Plus,Trash2,ChevronDown,ChevronUp,X} from 'lucide-react';
import {LabResult,Patient} from '../../../types/clinical';
import {useApp} from '../../../context/AppContext';

interface Props{patient:Patient}
type TestDef={name:string;unit:string;min?:number;max?:number;referenceRange?:string};
type PatientLabs=Patient&{customLabTests?:string[];customLabTestDefinitions?:TestDef[]};
const defs=(a:Array<[string,string,number?,number?]>):TestDef[]=>a.map(([name,unit,min,max])=>({name,unit,min,max}));
const TESTS:Record<string,TestDef[]>={
 CBC:defs([['Hemoglobin','g/dL',13,17.5],['Hematocrit','%',40,52],['RBC','10^6/µL',4.5,6],['WBC','10^3/µL',4,11],['Platelets','10^3/µL',150,400],['MCV','fL',80,100],['MCH','pg',27,33],['MCHC','g/dL',32,36],['RDW','%',11.5,14.5],['Neutrophils','%',40,75],['Lymphocytes','%',20,45],['Monocytes','%',2,10],['Eosinophils','%',1,6],['Basophils','%',0,2]]),
 Chemistry:defs([['Sodium','mmol/L',135,145],['Potassium','mmol/L',3.5,5.1],['Chloride','mmol/L',98,107],['Bicarbonate / HCO3','mmol/L',22,29],['Urea / BUN','mg/dL',7,20],['Creatinine','mg/dL',.6,1.3],['Glucose','mg/dL',70,99],['Calcium','mg/dL',8.5,10.5],['Magnesium','mg/dL',1.7,2.2],['Phosphate','mg/dL',2.5,4.5],['Uric Acid','mg/dL',3.5,7.2],['Serum Osmolality','mOsm/kg',275,295],['Lactate','mmol/L',.5,2.2]]),
 'Cardiac Markers':defs([['High-sensitivity Troponin','ng/L'],['CK','U/L'],['CK-MB','ng/mL'],['BNP','pg/mL'],['NT-proBNP','pg/mL'],['Myoglobin','ng/mL']]),
 'Coagulation':defs([['PT','sec',11,14],['INR','ratio',.8,1.2],['aPTT','sec',25,35],['Fibrinogen','mg/dL',200,400],['D-Dimer','mg/L FEU',0,.5],['Anti-Xa','IU/mL']]),
 'Lipid Profile':defs([['Total Cholesterol','mg/dL'],['LDL-C','mg/dL'],['HDL-C','mg/dL'],['Triglycerides','mg/dL'],['Non-HDL Cholesterol','mg/dL'],['Lipoprotein(a)','mg/dL']]),
 Diabetes:defs([['HbA1c','%'],['Fasting Glucose','mg/dL'],['Random Glucose','mg/dL'],['C-Peptide','ng/mL'],['Beta-hydroxybutyrate','mmol/L']]),
 Liver:defs([['AST','U/L',10,40],['ALT','U/L',7,56],['ALP','U/L',44,147],['GGT','U/L',8,61],['Total Bilirubin','mg/dL',.1,1.2],['Direct Bilirubin','mg/dL',0,.3],['Albumin','g/dL',3.5,5],['Total Protein','g/dL',6,8.3],['Ammonia','µmol/L']]),
 Thyroid:defs([['TSH','mIU/L'],['Free T4','ng/dL'],['Free T3','pg/mL'],['Total T4','µg/dL'],['Thyroid Peroxidase Ab','IU/mL']]),
 'ABG':defs([['pH','',7.35,7.45],['PaCO2','mmHg',35,45],['PaO2','mmHg',80,100],['HCO3','mmol/L',22,26],['Base Excess','mmol/L',-2,2],['Lactate','mmol/L',.5,2.2]]),
 Electrolytes:defs([['Ionized Calcium','mmol/L',1.12,1.32],['Sodium','mmol/L',135,145],['Potassium','mmol/L',3.5,5.1],['Magnesium','mmol/L',.7,1.1],['Phosphate','mmol/L',.8,1.5]]),
 'Inflammatory / Infection':defs([['CRP','mg/L'],['hs-CRP','mg/L'],['ESR','mm/hr'],['Procalcitonin','ng/mL'],['Ferritin','ng/mL'],['IL-6','pg/mL'],['Blood Culture','result'],['Urine Culture','result']]),
 'Iron / Vitamins':defs([['Serum Iron','µg/dL'],['Ferritin','ng/mL'],['TIBC','µg/dL'],['Transferrin Saturation','%'],['Vitamin B12','pg/mL'],['Folate','ng/mL'],['25-OH Vitamin D','ng/mL']])
};
const normalize=(s:string='')=>s.trim().toLowerCase().replace(/\s+/g,' ');
const flagFor=(value:string,ref:string|undefined):'Normal'|'Low'|'High'=>{const n=Number(value);if(!Number.isFinite(n)||!ref)return 'Normal';const m=ref.match(/(-?\d+(?:\.\d+)?)\s*(?:-|–|to)\s*(-?\d+(?:\.\d+)?)/);if(!m)return 'Normal';const lo=Number(m[1]),hi=Number(m[2]);return n<lo?'Low':n>hi?'High':'Normal';};
const badge=(flag:string)=>flag==='High'?'bg-rose-100 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300':flag==='Low'?'bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300':'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300';

export const LabsSection:React.FC<Props>=({patient})=>{
 const {updatePatient,showToast}=useApp();const p=patient as PatientLabs;
 const labs=Array.isArray(patient.labResults)?patient.labResults:[];const customDefs=Array.isArray(p.customLabTestDefinitions)?p.customLabTestDefinitions:[];const customNames=Array.from(new Set([...(p.customLabTests||[]),...customDefs.map(x=>x.name)]));
 const panelNames=['CBC',...Object.keys(TESTS).filter(x=>x!=='CBC'),'Custom Lab'];
 const [filter,setFilter]=useState('All');const [panel,setPanel]=useState('CBC');const [values,setValues]=useState<Record<string,string>>({});const [showEntry,setShowEntry]=useState(false);const [showCustom,setShowCustom]=useState(false);const [customName,setCustomName]=useState('');const [customUnit,setCustomUnit]=useState('');const [customRef,setCustomRef]=useState('');const [historyOpen,setHistoryOpen]=useState<Record<string,boolean>>({});
 const definitions=useMemo(()=>panel==='Custom Lab'?customDefs:TESTS[panel]||[],[panel,customDefs]);
 const groups=useMemo(()=>{const filtered=filter==='All'?labs:labs.filter(x=>String(x.panel||'').toLowerCase()===filter.toLowerCase());const map=new Map<string,LabResult[]>();for(const r of filtered){const k=normalize(r.testName||r.name||'Laboratory Test');if(!map.has(k))map.set(k,[]);map.get(k)!.push(r);}return [...map.entries()].map(([key,items])=>{const ordered=[...items].sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));return {key,latest:ordered[0],history:ordered.slice(1)};});},[labs,filter]);
 const openPanel=(name:string)=>{setPanel(name);setValues({});setShowEntry(true);};
 const updateValue=(name:string,v:string)=>setValues(x=>({...x,[name]:v}));
 const savePanel=()=>{const now=new Date().toISOString().slice(0,16).replace('T',' ');const additions:LabResult[]=[];for(const d of definitions){const v=(values[d.name]??'').trim();if(!v)continue;const ref=d.referenceRange||(d.min!==undefined&&d.max!==undefined?`${d.min} - ${d.max}`:'');additions.push({id:`lab-${Date.now()}-${additions.length}`,panel,testName:d.name,value:Number.isFinite(Number(v))?Number(v):v,unit:d.unit||'',referenceRange:ref,flag:flagFor(v,ref),timestamp:now});}if(!additions.length){showToast('Enter at least one laboratory result.','error');return;}updatePatient(patient.id,{labResults:[...additions,...labs]});setValues({});setShowEntry(false);showToast(`${additions.length} result${additions.length===1?'':'s'} saved. Previous values remain in each test history.`,'success');};
 const addCustom=()=>{const name=customName.trim();if(!name){showToast('Enter a panel/test name.','error');return;}if(customNames.some(x=>normalize(x)===normalize(name))){showToast('This custom lab already exists.','error');return;}const d={name,unit:customUnit.trim(),referenceRange:customRef.trim()};updatePatient(patient.id,{customLabTests:[...customNames,name],customLabTestDefinitions:[...customDefs,d]} as Partial<Patient>);setCustomName('');setCustomUnit('');setCustomRef('');setShowCustom(false);showToast('Custom laboratory test added.','success');};
 const deleteResult=(id?:string)=>{if(!id)return;updatePatient(patient.id,{labResults:labs.filter(x=>x.id!==id)});};
 return <div className="space-y-5 max-w-6xl mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-xl font-bold flex items-center gap-2"><FlaskConical className="w-5 h-5 text-cyan-500"/>Laboratory Results</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Choose a complete panel, enter all results, then save once. Repeated tests stay in the same card as history.</p></div><button onClick={()=>setShowCustom(true)} className="px-4 py-2 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-bold"><Plus className="inline w-4 h-4 mr-1 text-cyan-500"/>Custom Lab</button></div>
  <div className="flex flex-wrap gap-2"><button onClick={()=>setFilter('All')} className={`px-3 py-1.5 rounded-xl text-xs font-bold ${filter==='All'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>All</button>{panelNames.map(x=><button key={x} onClick={()=>{setFilter(x);if(x!=='Custom Lab')openPanel(x);}} className={`px-3 py-1.5 rounded-xl text-xs font-bold ${filter===x?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{x}</button>)}</div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{groups.map(({key,latest,history})=>{const flag=latest.flag||'Normal';const open=!!historyOpen[key];return <article key={key} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider font-bold text-slate-400">{latest.panel||'Laboratory'}</div><h3 className="text-base font-extrabold mt-1">{latest.testName||latest.name}</h3></div><button onClick={()=>deleteResult(latest.id)} className="p-2 rounded-lg text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 className="w-4 h-4"/></button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 dark:bg-slate-900/60 p-3"><div className="text-[11px] text-slate-400">Latest Result</div><div className="text-lg font-extrabold mt-1">{String(latest.value)} <span className="text-xs">{latest.unit||'—'}</span></div></div><div className="rounded-xl bg-slate-50 dark:bg-slate-900/60 p-3"><div className="text-[11px] text-slate-400">Reference</div><div className="text-sm font-bold mt-1">{latest.referenceRange||'Not specified'}</div></div></div><div className="mt-3 flex items-center justify-between gap-2"><span className={`px-2.5 py-1 rounded-lg text-[10px] font-extrabold ${badge(flag)}`}>{flag==='High'?'↑ HIGH':flag==='Low'?'↓ LOW':'✓ NORMAL'}</span><span className="text-[10px] text-slate-400">{latest.timestamp||'—'}</span></div>{history.length>0&&<><button onClick={()=>setHistoryOpen(x=>({...x,[key]:!open}))} className="mt-3 w-full flex items-center justify-between px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold"><span>History ({history.length})</span>{open?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button>{open&&<div className="mt-2 space-y-2">{history.map(r=><div key={r.id} className="flex items-center justify-between gap-2 px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 text-xs"><span className="text-slate-400">{r.timestamp||'—'}</span><span className="font-bold">{String(r.value)} {r.unit||''}</span><span className={`px-2 py-0.5 rounded-md text-[9px] font-bold ${badge(r.flag||'Normal')}`}>{r.flag||'Normal'}</span></div>)}</div>}</>}</article>;})}</div>
  {!groups.length&&<div className="rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 p-10 text-center text-sm text-slate-400">No laboratory results recorded yet. Choose a panel above to enter results.</div>}
  {showEntry&&<div className="fixed inset-0 z-[100] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-3"><div className="w-full max-w-3xl max-h-[92vh] overflow-hidden rounded-3xl bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-800 shadow-2xl"><div className="px-5 py-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><div><div className="text-lg font-extrabold">Enter {panel}</div><div className="text-xs text-slate-500">All tests are shown together. Blank fields will not be saved.</div></div><button onClick={()=>setShowEntry(false)} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-5 h-5"/></button></div><div className="p-4 overflow-y-auto max-h-[70vh] space-y-2">{definitions.map(d=>{const ref=d.referenceRange||(d.min!==undefined&&d.max!==undefined?`${d.min} - ${d.max}`:'');const val=values[d.name]||'';const flag=flagFor(val,ref);return <div key={d.name} className="grid grid-cols-12 gap-2 items-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900/60"><div className="col-span-5 sm:col-span-4 text-sm font-bold">{d.name}</div><input value={val} onChange={e=>updateValue(d.name,e.target.value)} inputMode="decimal" placeholder="Result" className="col-span-3 sm:col-span-3 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm outline-none focus:border-cyan-500"/><div className="col-span-2 text-[11px] text-slate-400">{d.unit||'—'}</div><div className="col-span-2 text-right">{val&&<span className={`px-2 py-1 rounded-md text-[9px] font-bold ${badge(flag)}`}>{flag}</span>}</div><div className="col-span-12 text-[10px] text-slate-400">Reference: {ref||'Not specified'}</div></div>;})}</div><div className="px-5 py-4 border-t border-slate-200 dark:border-slate-800 flex justify-end gap-2"><button onClick={()=>setShowEntry(false)} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-sm font-bold">Cancel</button><button onClick={savePanel} className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-sm font-extrabold">Save {panel} Results</button></div></div></div>}
  {showCustom&&<div className="fixed inset-0 z-[110] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-3"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-800 p-5"><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-extrabold">Add Custom Lab</h3><button onClick={()=>setShowCustom(false)}><X className="w-5 h-5"/></button></div><div className="space-y-3"><input value={customName} onChange={e=>setCustomName(e.target.value)} placeholder="Test name" className="w-full px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent"/><input value={customUnit} onChange={e=>setCustomUnit(e.target.value)} placeholder="Unit" className="w-full px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent"/><input value={customRef} onChange={e=>setCustomRef(e.target.value)} placeholder="Reference range e.g. 10 - 20" className="w-full px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setShowCustom(false)} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-sm font-bold">Cancel</button><button onClick={addCustom} className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-sm font-extrabold">Add</button></div></div></div>}
 </div>;
};
