import React,{useEffect,useMemo,useRef,useState} from 'react';
import {FlaskConical,Plus,Trash2,ChevronDown,ChevronUp,X,Upload,Loader2} from 'lucide-react';
import {LabResult,Patient} from '../../../types/clinical';
import {useApp} from '../../../context/AppContext';import{useIsPreviousViewer}from'../PreviousAdmissionViewer';
import {getSharedLabLibrary,saveSharedLabTemplate} from '../../../services/departmentLibraryService';
import {analyzeLabImage,type ExtractedLabResult} from '../../../services/aiLogic';
import {AIDataWarning} from '../AIDataWarning';
interface Props{patient:Patient} type TestDef={name:string;unit:string;min?:number;max?:number;referenceRange?:string};type PatientLabs=Patient&{customLabTests?:string[];customLabTestDefinitions?:TestDef[]};
const defs=(a:Array<[string,string,number?,number?]>):TestDef[]=>a.map(([name,unit,min,max])=>({name,unit,min,max}));
const TESTS:Record<string,TestDef[]>={
 CBC:defs([['Hemoglobin','g/dL',13,17.5],['Hematocrit','%',40,52],['RBC','10^6/µL',4.5,6],['WBC','10^3/µL',4,11],['Platelets','10^3/µL',150,400],['MCV','fL',80,100],['MCH','pg',27,33],['MCHC','g/dL',32,36],['RDW','%',11.5,14.5],['Neutrophils','%',40,75],['Lymphocytes','%',20,45],['Monocytes','%',2,10],['Eosinophils','%',1,6],['Basophils','%',0,2]]),
 Chemistry:defs([['Sodium','mmol/L',135,145],['Potassium','mmol/L',3.5,5.1],['Chloride','mmol/L',98,107],['Bicarbonate / HCO3','mmol/L',22,29],['Urea / BUN','mg/dL',7,20],['Creatinine','mg/dL',.6,1.3],['Glucose','mg/dL',70,99],['Calcium','mg/dL',8.5,10.5],['Magnesium','mg/dL',1.7,2.2],['Phosphate','mg/dL',2.5,4.5],['Uric Acid','mg/dL',3.5,7.2],['Serum Osmolality','mOsm/kg',275,295],['Lactate','mmol/L',.5,2.2]]),
 'Cardiac Markers':defs([['High-sensitivity Troponin','ng/L'],['CK','U/L'],['CK-MB','ng/mL'],['BNP','pg/mL'],['NT-proBNP','pg/mL'],['Myoglobin','ng/mL']]),
 'Coagulation':defs([['PT','sec',11,14],['INR','ratio',.8,1.2],['aPTT','sec',25,35],['Fibrinogen','mg/dL',200,400],['D-Dimer','mg/L FEU',0,.5],['Anti-Xa','IU/mL']]),
 'Lipid Profile':defs([['Total Cholesterol','mg/dL'],['LDL-C','mg/dL'],['HDL-C','mg/dL'],['Triglycerides','mg/dL'],['Non-HDL Cholesterol','mg/dL'],['Lipoprotein(a)','mg/dL']]),
 Diabetes:defs([['HbA1c','%'],['Fasting Glucose','mg/dL'],['Random Glucose','mg/dL'],['C-Peptide','ng/mL'],['Beta-hydroxybutyrate','mmol/L']]),
 Liver:defs([['AST','U/L',10,40],['ALT','U/L',7,56],['ALP','U/L',44,147],['GGT','U/L',8,61],['Total Bilirubin','mg/dL',.1,1.2],['Direct Bilirubin','mg/dL',0,.3],['Albumin','g/dL',3.5,5],['Total Protein','g/dL',6,8.3],['Ammonia','µmol/L']]),
 Thyroid:defs([['TSH','mIU/L'],['Free T4','ng/dL'],['Free T3','pg/mL'],['Total T4','µg/dL'],['Thyroid Peroxidase Ab','IU/mL']]),
 ABG:defs([['pH','',7.35,7.45],['PaCO2','mmHg',35,45],['PaO2','mmHg',80,100],['HCO3','mmol/L',22,26],['Base Excess','mmol/L',-2,2],['Lactate','mmol/L',.5,2.2]]),
 Electrolytes:defs([['Ionized Calcium','mmol/L',1.12,1.32],['Sodium','mmol/L',135,145],['Potassium','mmol/L',3.5,5.1],['Magnesium','mmol/L',.7,1.1],['Phosphate','mmol/L',.8,1.5]]),
 'Inflammatory / Infection':defs([['CRP','mg/L'],['hs-CRP','mg/L'],['ESR','mm/hr'],['Procalcitonin','ng/mL'],['Ferritin','ng/mL'],['IL-6','pg/mL'],['Blood Culture','result'],['Urine Culture','result']]),
 'Iron / Vitamins':defs([['Serum Iron','µg/dL'],['Ferritin','ng/mL'],['TIBC','µg/dL'],['Transferrin Saturation','%'],['Vitamin B12','pg/mL'],['Folate','ng/mL'],['25-OH Vitamin D','ng/mL']])
};
const normalize=(s:string='')=>s.trim().toLowerCase().replace(/\s+/g,' ');
const flagFor=(value:string,ref:string|undefined):'Normal'|'Low'|'High'=>{const n=Number(value);if(!Number.isFinite(n)||!ref)return'Normal';const m=ref.match(/(-?\d+(?:\.\d+)?)\s*(?:-|–|to)\s*(-?\d+(?:\.\d+)?)/);if(!m)return'Normal';const lo=Number(m[1]),hi=Number(m[2]);return n<lo?'Low':n>hi?'High':'Normal';};
const badge=(f:string)=>f==='High'?'bg-rose-100 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300':f==='Low'?'bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300':'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300';

export const LabsSection:React.FC<Props>=({patient})=>{
 const{updatePatient,showToast}=useApp();const isPreviousViewer=useIsPreviousViewer();
 const p=patient as PatientLabs;
 const labs=Array.isArray(patient.labResults)?patient.labResults:[];
 const customDefs=Array.isArray(p.customLabTestDefinitions)?p.customLabTestDefinitions:[];
 const customNames=Array.from(new Set([...(p.customLabTests||[]),...customDefs.map(x=>x.name)]));
 const panelNames=['CBC',...Object.keys(TESTS).filter(x=>x!=='CBC'),'Custom Lab'];
 const[sharedCustomDefs,setSharedCustomDefs]=useState<TestDef[]>([]); const aiInputRef=useRef<HTMLInputElement|null>(null); const[aiBusy,setAiBusy]=useState(false); const[aiCooldownSeconds,setAiCooldownSeconds]=useState(0); const[aiDraft,setAiDraft]=useState<ExtractedLabResult[]>([]); const[aiPanel,setAiPanel]=useState(''); const[aiNotes,setAiNotes]=useState<string[]>([]); const[aiSelectedFile,setAiSelectedFile]=useState<File|null>(null); const[aiError,setAiError]=useState('');useEffect(()=>{void getSharedLabLibrary().then(rows=>setSharedCustomDefs(rows));},[]);const[filter,setFilter]=useState('All');const[panel,setPanel]=useState('CBC');const[values,setValues]=useState<Record<string,string>>({});const[showEntry,setShowEntry]=useState(false);const[showCustom,setShowCustom]=useState(false);const[customRows,setCustomRows]=useState<TestDef[]>([{name:'',unit:'',referenceRange:''}]);const[historyOpen,setHistoryOpen]=useState<Record<string,boolean>>({});const[expandedPanels,setExpandedPanels]=useState<Record<string,boolean>>({});
 const allCustomDefs=useMemo(()=>{const map=new Map<string,TestDef>();[...customDefs,...sharedCustomDefs].forEach(x=>map.set(normalize(x.name),x));return [...map.values()];},[customDefs,sharedCustomDefs]);
 const definitions=useMemo(()=>panel==='Custom Lab'?allCustomDefs:TESTS[panel]||[],[panel,allCustomDefs]);
 const groupedPanels=useMemo(()=>{
   const filtered=filter==='All'?labs:labs.filter(x=>String(x.panel||'').toLowerCase()===filter.toLowerCase());
   const byPanel=new Map<string,LabResult[]>();
   for(const r of filtered){const name=String(r.panel||'Laboratory');if(!byPanel.has(name))byPanel.set(name,[]);byPanel.get(name)!.push(r);}
   return [...byPanel.entries()].map(([panelName,items])=>{
     const byTest=new Map<string,LabResult[]>();
     for(const r of items){const key=normalize(r.testName||r.name||'Laboratory Test');if(!byTest.has(key))byTest.set(key,[]);byTest.get(key)!.push(r);}
     const tests=[...byTest.entries()].map(([key,records])=>{const ordered=[...records].sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));return{key,latest:ordered[0],history:ordered.slice(1)};});
     const defOrder=(TESTS[panelName]||allCustomDefs).map(x=>normalize(x.name));
     tests.sort((a,b)=>{const ai=defOrder.indexOf(a.key),bi=defOrder.indexOf(b.key);if(ai<0&&bi<0)return String(a.latest.testName||a.latest.name).localeCompare(String(b.latest.testName||b.latest.name));if(ai<0)return 1;if(bi<0)return -1;return ai-bi;});
     return{panelName,tests};
   }).sort((a,b)=>{const ai=panelNames.indexOf(a.panelName),bi=panelNames.indexOf(b.panelName);return (ai<0?999:ai)-(bi<0?999:bi);});
 },[labs,filter,allCustomDefs]);
 const openPanel=(name:string)=>{if(isPreviousViewer)return;setPanel(name);setValues({});setShowEntry(true);};
 const updateValue=(name:string,v:string)=>setValues(x=>({...x,[name]:v}));
 const analyzeUploadedLab=async(file?:File)=>{if(!file)return;setAiSelectedFile(file);setAiError('');setAiBusy(true);try{const result=await analyzeLabImage(file);setAiDraft(Array.isArray(result.results)?result.results:[]);setAiPanel(String(result.panel||'AI Extracted Labs'));setAiNotes(Array.isArray(result.notes)?result.notes:[]);showToast('AI extracted the visible laboratory values. Review before saving.','success');}catch(error:any){const retryAfter=Number(error?.details?.retryAfterSeconds||0);if(error?.details?.httpStatus===429&&retryAfter>0)setAiCooldownSeconds(retryAfter);const message=error?.details?.httpStatus===429&&retryAfter>0?`AI limit reached, try again in ~${retryAfter} seconds`:String(error?.message||'AI laboratory analysis could not be completed. Please try again.');setAiError(message);showToast(message,'error');}finally{setAiBusy(false);}};
 const saveAiDraft=()=>{if(isPreviousViewer)return;if(!aiDraft.length)return;const now=new Date().toISOString().slice(0,16).replace('T',' ');const additions=aiDraft.map((r,i)=>({id:'ai-lab-'+Date.now()+'-'+i,panel:aiPanel||'AI Extracted Labs',testName:r.testName,value:r.value,unit:r.unit||'',referenceRange:r.referenceRange||'',status:r.status==='unknown'?'normal':r.status,flag:r.status,timestamp:now} as LabResult));updatePatient(patient.id,{labResults:[...additions,...labs]});setAiDraft([]);setAiNotes([]);showToast(additions.length+' AI-extracted result'+(additions.length===1?'':'s')+' saved.','success');};
 const savePanel=()=>{if(isPreviousViewer)return;const now=new Date().toISOString().slice(0,16).replace('T',' ');const additions:LabResult[]=[];for(const d of definitions){const v=(values[d.name]??'').trim();if(!v)continue;const ref=d.referenceRange||(d.min!==undefined&&d.max!==undefined?`${d.min} - ${d.max}`:'');additions.push({id:`lab-${Date.now()}-${additions.length}`,panel,testName:d.name,value:Number.isFinite(Number(v))?Number(v):v,unit:d.unit||'',referenceRange:ref,flag:flagFor(v,ref),timestamp:now});}if(!additions.length){showToast('Enter at least one laboratory result.','error');return;}updatePatient(patient.id,{labResults:[...additions,...labs]});setValues({});setShowEntry(false);setExpandedPanels(x=>({...x,[panel]:true}));showToast(`${additions.length} result${additions.length===1?'':'s'} saved in the ${panel} panel.`,'success');};
 const addCustomPanel=async()=>{if(isPreviousViewer)return;const rows=customRows.map(x=>({...x,name:x.name.trim(),unit:x.unit.trim(),referenceRange:x.referenceRange?.trim()||''})).filter(x=>x.name);if(!rows.length){showToast('Add at least one custom test.','error');return;}const names=new Set(customNames.map(normalize));if(rows.some(x=>names.has(normalize(x.name)))){showToast('One of these custom tests already exists.','error');return;}updatePatient(patient.id,{customLabTests:[...customNames,...rows.map(x=>x.name)],customLabTestDefinitions:[...customDefs,...rows]} as Partial<Patient>);setCustomRows([{name:'',unit:'',referenceRange:''}]);setShowCustom(false);for(const row of rows){try{const cloud=await saveSharedLabTemplate({name:row.name,unit:row.unit,referenceRange:row.referenceRange,min:row.referenceRange?.match(/^-?\\d+(?:\\.\\d+)?/) ? Number(row.referenceRange.match(/^-?\\d+(?:\\.\\d+)?/)![0]) : undefined,max:row.referenceRange?.match(/(?:-|–|to)\\s*(-?\\d+(?:\\.\\d+)?)$/i) ? Number(row.referenceRange.match(/(?:-|–|to)\\s*(-?\\d+(?:\\.\\d+)?)$/i)![1]) : undefined});setSharedCustomDefs(v=>[...v.filter(x=>normalize(x.name)!==normalize(cloud.name)),cloud]);}catch{}}showToast(`${rows.length} custom tests saved for later use.`,'success');};
 const deleteResult=(id?:string)=>{if(isPreviousViewer)return;if(!id)return;updatePatient(patient.id,{labResults:labs.filter(x=>x.id!==id)});};
 return <div className="space-y-5 max-w-6xl mx-auto"><AIDataWarning compact/>
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-xl font-bold flex items-center gap-2"><FlaskConical className="w-5 h-5 text-cyan-500"/>Laboratory Results</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Each panel is collapsed by default. Tap a panel to expand its saved items; each item keeps its own History.</p></div><div className="flex flex-wrap gap-2"><input ref={aiInputRef} type="file" accept="image/*" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void analyzeUploadedLab(file);e.currentTarget.value='';}}/><button type="button" disabled={aiBusy||aiCooldownSeconds>0} onClick={()=>aiInputRef.current?.click()} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-extrabold disabled:opacity-60 disabled:cursor-not-allowed">{aiBusy?<Loader2 className="inline w-4 h-4 mr-1 animate-spin"/>:<Upload className="inline w-4 h-4 mr-1"/>}{aiBusy?'Analyzing…':aiCooldownSeconds>0?`AI limit reached, try again in ~${aiCooldownSeconds} seconds`:'AI Lab Analysis'}</button>{aiError&&<div className="basis-full flex items-center gap-2 rounded-xl border border-amber-300 bg-amber-50 dark:bg-amber-950/20 dark:border-amber-800 px-3 py-2 text-xs text-amber-800 dark:text-amber-200"><span className="flex-1">{aiError}</span><button type="button" disabled={aiBusy||aiCooldownSeconds>0||!aiSelectedFile} onClick={()=>{if(aiSelectedFile)void analyzeUploadedLab(aiSelectedFile);}} className="shrink-0 px-3 py-1.5 rounded-lg bg-amber-200 dark:bg-amber-900/40 font-bold disabled:opacity-50">{aiBusy?'Trying…':aiCooldownSeconds>0?`Wait ~${aiCooldownSeconds}s`:'Try again'}</button><button type="button" onClick={()=>setAiError('')} className="shrink-0 text-amber-700 dark:text-amber-300 font-bold" aria-label="Dismiss AI lab error">×</button></div>}<button disabled={isPreviousViewer} onClick={()=>setShowCustom(true)} className="px-4 py-2 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-bold"><Plus className="inline w-4 h-4 mr-1 text-cyan-500"/>Custom Lab Panel</button></div></div>
  <div className="flex flex-wrap gap-2"><button onClick={()=>setFilter('All')} className={`px-3 py-1.5 rounded-xl text-xs font-bold ${filter==='All'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>All</button>{panelNames.map(x=><button key={x} onClick={()=>{setFilter(x);if(x==='Custom Lab'&&customDefs.length===0){setShowCustom(true);}else openPanel(x);}} className={`px-3 py-1.5 rounded-xl text-xs font-bold ${filter===x?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{x}</button>)}</div>
  <div className="space-y-4">{groupedPanels.map(({panelName,tests})=>{const expanded=!!expandedPanels[panelName];return <article key={panelName} className={`rounded-2xl border ${tests.some(t=>['Low','High','Critical'].includes(String(t.latest.flag||'')))?'border-rose-400/70 shadow-[0_0_0_1px_rgba(244,63,94,.12)]':'border-slate-200 dark:border-slate-800'} bg-white dark:bg-[#111C2E] overflow-hidden shadow-sm`}>
    <button type="button" onClick={()=>setExpandedPanels(x=>({...x,[panelName]:!expanded}))} className="w-full text-left px-4 py-4 flex items-center justify-between gap-3 bg-slate-50/70 dark:bg-slate-900/30 hover:bg-slate-100/70 dark:hover:bg-slate-900/50 transition-colors"><div className="min-w-0"><div className="text-[10px] uppercase tracking-wider font-bold text-cyan-500">Laboratory Panel</div><h3 className="text-lg font-extrabold mt-0.5">{panelName}</h3><div className="text-[10px] text-slate-400 mt-1">{expanded?'Tap to collapse':'Tap to expand'} • {tests.length} saved items {tests.some(t=>['Low','High','Critical'].includes(String(t.latest.flag||'')))&&<span className="text-rose-500 font-black ml-1">● ABNORMAL</span>}</div></div><div className="flex items-center gap-2 shrink-0"><span className="px-2.5 py-1 rounded-lg bg-cyan-500/10 text-cyan-600 dark:text-cyan-300 text-[10px] font-bold">{tests.length} items</span>{expanded?<ChevronUp className="w-5 h-5 text-cyan-500"/>:<ChevronDown className="w-5 h-5 text-slate-400"/>}</div></button>
    {expanded&&<div className="divide-y divide-slate-200 dark:divide-slate-800">{tests.map(({key,latest,history})=>{const flag=latest.flag||'Normal';const open=!!historyOpen[`${panelName}:${key}`];return <div key={key} className="px-4 py-3">
      <div className="flex items-center gap-3"><div className="min-w-0 flex-1"><div className="font-bold text-sm">{latest.testName||latest.name}</div><div className="text-[10px] text-slate-400 mt-0.5">Reference: {latest.referenceRange||'Not specified'}{latest.timestamp?` • ${latest.timestamp}`:''}</div></div><div className="text-right shrink-0"><div className="text-base font-extrabold">{String(latest.value)} <span className="text-[10px] font-semibold text-slate-400">{latest.unit||''}</span></div><span className={`inline-block mt-1 px-2 py-0.5 rounded-md text-[9px] font-extrabold ${badge(flag)}`}>{flag==='High'?'↑ HIGH':flag==='Low'?'↓ LOW':'✓ NORMAL'}</span></div><button disabled={isPreviousViewer} onClick={()=>deleteResult(latest.id)} aria-label={`Delete ${latest.testName||latest.name}`} className="p-2 rounded-lg text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 className="w-4 h-4"/></button></div>
      {history.length>0&&<><button onClick={()=>setHistoryOpen(x=>({...x,[`${panelName}:${key}`]:!open}))} className="mt-2 w-full flex items-center justify-between px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-bold"><span>History ({history.length})</span>{open?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button>{open&&<div className="mt-2 space-y-1.5">{history.map(r=><div key={r.id} className="flex items-center justify-between gap-2 px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 text-xs"><span className="text-slate-400">{r.timestamp||'—'}</span><span className="font-bold">{String(r.value)} {r.unit||''}</span><span className={`px-2 py-0.5 rounded-md text-[9px] font-bold ${badge(r.flag||'Normal')}`}>{r.flag||'Normal'}</span></div>)}</div>}</>}
    </div>})}</div>}
  </article>})}</div>
  {!groupedPanels.length&&<div className="rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 p-10 text-center text-sm text-slate-400">No laboratory results recorded yet. Choose a panel above to enter results.</div>}
  {aiDraft.length>0&&<div className="fixed inset-0 z-[120] bg-black/60 flex items-center justify-center p-3"><div className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white dark:bg-slate-900 p-5"><div className="flex justify-between items-start gap-3"><div><b>Review AI Lab Extraction</b><div className="text-xs text-slate-500 mt-1">Fake/test data only. Nothing is saved until you press Save.</div></div><button onClick={()=>{setAiDraft([]);setAiNotes([]);}} aria-label="Discard AI lab extraction"><X className="w-4 h-4"/></button></div><div className="mt-3 text-xs font-bold text-cyan-600 dark:text-cyan-300">Panel: {aiPanel||'AI Extracted Labs'}</div>{aiNotes.length>0&&<div className="mt-2 rounded-xl bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 p-3 text-xs text-amber-800 dark:text-amber-200"><b>AI notes:</b><ul className="mt-1 list-disc pl-4">{aiNotes.map((n,i)=><li key={i}>{n}</li>)}</ul></div>}<div className="mt-3 space-y-3">{aiDraft.map((r,i)=><div key={i} className="grid grid-cols-1 sm:grid-cols-4 gap-2 rounded-xl border border-slate-200 dark:border-slate-800 p-3"><label className="text-xs font-bold">Test name<input value={r.testName} onChange={e=>setAiDraft(a=>a.map((x,j)=>j===i?{...x,testName:e.target.value}:x))} className="mt-1 w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Value<input value={String(r.value)} onChange={e=>setAiDraft(a=>a.map((x,j)=>j===i?{...x,value:e.target.value}:x))} className="mt-1 w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Unit<input value={r.unit} onChange={e=>setAiDraft(a=>a.map((x,j)=>j===i?{...x,unit:e.target.value}:x))} className="mt-1 w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent"/></label><label className="text-xs font-bold">Reference range<input value={r.referenceRange} onChange={e=>setAiDraft(a=>a.map((x,j)=>j===i?{...x,referenceRange:e.target.value}:x))} className="mt-1 w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent"/></label></div>)}</div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setAiDraft([]);setAiNotes([]);}} className="px-3 py-2 rounded-xl border text-xs">Discard</button><button onClick={saveAiDraft} className="px-3 py-2 rounded-xl bg-cyan-500 text-white text-xs font-bold">Save Extracted Results</button></div></div></div>}
  {showEntry&&<div className="fixed inset-0 z-[100] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-3"><div className="w-full max-w-3xl max-h-[92vh] overflow-hidden rounded-3xl bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-800 shadow-2xl"><div className="px-5 py-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><div><div className="text-lg font-extrabold">Enter {panel}</div><div className="text-xs text-slate-500">All tests are shown together. Blank fields will not be saved.</div></div><button onClick={()=>setShowEntry(false)} className="p-2 rounded-xl"><X className="w-5 h-5"/></button></div><div className="p-4 overflow-y-auto max-h-[70vh] space-y-2">{definitions.map(d=>{const ref=d.referenceRange||(d.min!==undefined&&d.max!==undefined?`${d.min} - ${d.max}`:'');const val=values[d.name]||'';const flag=flagFor(val,ref);return <div key={d.name} className="grid grid-cols-12 gap-2 items-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900/60"><div className="col-span-5 sm:col-span-4 text-sm font-bold">{d.name}</div><input value={val} onChange={e=>updateValue(d.name,e.target.value)} inputMode="decimal" placeholder="Result" className="col-span-3 sm:col-span-3 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm outline-none focus:border-cyan-500"/><div className="col-span-2 text-[11px] text-slate-400">{d.unit||'—'}</div><div className="col-span-2 text-right">{val&&<span className={`px-2 py-1 rounded-md text-[9px] font-bold ${badge(flag)}`}>{flag}</span>}</div><div className="col-span-12 text-[10px] text-slate-400">Reference: {ref||'Not specified'}</div></div>;})}</div><div className="px-5 py-4 border-t border-slate-200 dark:border-slate-800 flex justify-end gap-2"><button onClick={()=>setShowEntry(false)} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-sm font-bold">Cancel</button><button onClick={savePanel} className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-sm font-extrabold">Save {panel} Results</button></div></div></div>}
  {showCustom&&<div className="fixed inset-0 z-[110] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-3"><div className="w-full max-w-3xl max-h-[90vh] overflow-hidden rounded-3xl bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-800 p-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-extrabold">Custom Lab Panel</h3><p className="text-xs text-slate-500 mt-1">Build the whole custom list first, then save it as one panel.</p></div><button onClick={()=>setShowCustom(false)}><X className="w-5 h-5"/></button></div><div className="mt-4 max-h-[60vh] overflow-y-auto space-y-2">{customRows.map((r,i)=><div key={i} className="grid grid-cols-12 gap-2 items-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900/60"><input value={r.name} onChange={e=>setCustomRows(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))} placeholder="Test name" className="col-span-5 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800"/><input value={r.unit} onChange={e=>setCustomRows(a=>a.map((x,j)=>j===i?{...x,unit:e.target.value}:x))} placeholder="Unit" className="col-span-3 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800"/><input value={r.referenceRange||''} onChange={e=>setCustomRows(a=>a.map((x,j)=>j===i?{...x,referenceRange:e.target.value}:x))} placeholder="Reference" className="col-span-3 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800"/><button onClick={()=>setCustomRows(a=>a.filter((_,j)=>j!==i))} className="col-span-1 p-2 text-rose-500"><Trash2 className="w-4 h-4"/></button></div>)}<button onClick={()=>setCustomRows(a=>[...a,{name:'',unit:'',referenceRange:''}])} className="w-full py-2 rounded-xl border border-dashed border-cyan-400 text-cyan-600 text-sm font-bold"><Plus className="inline w-4 h-4 mr-1"/>Add Test</button></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowCustom(false)} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-sm font-bold">Cancel</button><button onClick={addCustomPanel} className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-sm font-extrabold">Save Custom Panel</button></div></div></div>}
 </div>;
};
