import React,{useState} from 'react';
import {Pill,Plus,Activity,Clock,Trash2,Zap,X} from 'lucide-react';
import {Patient,Medication,Infusion} from '../../../types/clinical';
import {useApp} from '../../../context/AppContext';

interface Props{patient:Patient}
const input='w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-sm text-slate-900 dark:text-white';

export const MedicationSection:React.FC<Props>=({patient})=>{
 const {updatePatient,showToast}=useApp();
 const [activeTab,setActiveTab]=useState<'infusions'|'scheduled'|'prn'>('infusions');
 const [showMed,setShowMed]=useState(false); const [showInf,setShowInf]=useState(false);
 const [medName,setMedName]=useState(''); const [medDose,setMedDose]=useState(''); const [medRoute,setMedRoute]=useState('Oral'); const [medFreq,setMedFreq]=useState('Once daily (OD)'); const [medIndication,setMedIndication]=useState('');
 const [infDrug,setInfDrug]=useState(''); const [infDose,setInfDose]=useState(''); const [infUnit,setInfUnit]=useState('mcg/kg/min'); const [infRate,setInfRate]=useState(''); const [infConcentration,setInfConcentration]=useState(''); const [infCarrier,setInfCarrier]=useState(''); const [infLine,setInfLine]=useState('');
 const meds=Array.isArray(patient.medications)?patient.medications:[]; const infusions=Array.isArray(patient.infusions)?patient.infusions:[];
 const scheduled=meds.filter(m=>m.type==='Scheduled'); const prn=meds.filter(m=>m.type==='PRN');
 const resetMed=()=>{setMedName('');setMedDose('');setMedRoute('Oral');setMedFreq('Once daily (OD)');setMedIndication('');};
 const addMedication=(e:React.FormEvent)=>{e.preventDefault();if(!medName.trim()||!medDose.trim())return;const type=activeTab==='prn'?'PRN':'Scheduled';const med:Medication={id:`med-${Date.now()}`,name:medName.trim(),dose:medDose.trim(),route:medRoute,frequency:medFreq,indication:medIndication.trim()||'Therapeutic',type};updatePatient(patient.id,{medications:[...meds,med]});setShowMed(false);resetMed();showToast(`Added ${med.name}`,'success');};
 const addInfusion=(e:React.FormEvent)=>{e.preventDefault();if(!infDrug.trim()||!infDose.trim()||!infRate.trim())return;const inf:Infusion={id:`inf-${Date.now()}`,drugName:infDrug.trim(),dose:Number(infDose)||0,unit:infUnit,rateMlHr:Number(infRate)||0,concentration:infConcentration.trim()||undefined,carrierFluid:infCarrier.trim()||undefined,lineSite:infLine.trim()||undefined};updatePatient(patient.id,{infusions:[...infusions,inf]});setShowInf(false);setInfDrug('');setInfDose('');setInfRate('');setInfConcentration('');setInfCarrier('');setInfLine('');showToast(`Started infusion ${inf.drugName}`,'success');};
 const deleteMed=(id:string)=>updatePatient(patient.id,{medications:meds.filter(m=>m.id!==id)});
 const deleteInf=(id:string)=>updatePatient(patient.id,{infusions:infusions.filter(i=>i.id!==id)});
 const openMedication=()=>{if(activeTab==='prn')resetMed();setShowMed(true);};
 return <div className="space-y-6 max-w-5xl mx-auto animate-in fade-in duration-150">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><Pill className="w-5 h-5 text-cyan-500"/> Pharmacotherapy & Continuous Infusions</h2><p className="text-xs text-slate-500 dark:text-slate-400">Vasoactive titration, ICU sedatives, scheduled cardiac regimens & PRN medications</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowInf(true)} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 text-xs font-semibold"><Activity className="w-4 h-4 text-cyan-500"/> + Infusion</button><button onClick={openMedication} className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Plus className="w-4 h-4"/> + Medication</button></div></div>
  <div className="flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-2 overflow-x-auto"><button onClick={()=>setActiveTab('infusions')} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${activeTab==='infusions'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'}`}><Zap className="inline w-3.5 h-3.5 mr-1"/>Continuous Infusions ({infusions.length})</button><button onClick={()=>setActiveTab('scheduled')} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${activeTab==='scheduled'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'}`}><Clock className="inline w-3.5 h-3.5 mr-1"/>Scheduled Medications ({scheduled.length})</button><button onClick={()=>setActiveTab('prn')} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${activeTab==='prn'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'}`}>PRN / As Needed ({prn.length})</button></div>
  {activeTab==='infusions'&&<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{infusions.map(i=><div key={i.id} className="bg-white dark:bg-[#111C2E] border border-cyan-500/30 rounded-2xl p-4 shadow-sm space-y-3"><div className="flex items-start justify-between"><div><h4 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full bg-cyan-400 animate-pulse"/>{i.drugName}</h4><p className="text-[11px] text-slate-400">{i.concentration||'Custom concentration'}{i.lineSite?` • ${i.lineSite}`:''}</p></div><button onClick={()=>deleteInf(i.id)} className="p-1.5 text-slate-400 hover:text-rose-500"><Trash2 className="w-4 h-4"/></button></div><div className="flex justify-between pt-2 border-t border-slate-100 dark:border-slate-800"><div><span className="text-[10px] uppercase text-slate-400 font-bold block">Target Dose</span><span className="text-base font-extrabold text-cyan-500">{i.dose} {i.unit}</span></div><div className="text-right"><span className="text-[10px] uppercase text-slate-400 font-bold block">Pump Rate</span><span className="text-base font-extrabold text-slate-900 dark:text-white">{i.rateMlHr} mL/hr</span></div></div></div>)}</div>{!infusions.length&&<div className="p-8 text-center text-slate-400 bg-slate-50 dark:bg-[#111C2E] rounded-2xl border border-dashed border-slate-200 dark:border-slate-800">No active continuous infusions running.</div>}</div>}
  {(activeTab==='scheduled'||activeTab==='prn')&&<div className="space-y-3"><button onClick={openMedication} className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold shadow-sm"><Plus className="w-4 h-4"/> {activeTab==='prn'?'Add PRN Medication':'Add Scheduled Medication'}</button><div className="bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden"><div className="divide-y divide-slate-100 dark:divide-slate-800">{(activeTab==='prn'?prn:scheduled).map(m=><div key={m.id} className="p-4 flex items-center justify-between group"><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-bold text-slate-900 dark:text-white">{m.name||m.drug}</span><span className="text-xs font-semibold px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-cyan-600 dark:text-cyan-400">{m.dose}</span><span className="text-xs text-slate-400">• {m.route}</span></div><p className="text-xs text-slate-500 dark:text-slate-400">{activeTab==='prn'?'PRN: ':''}{m.frequency}{m.indication?` • ${m.indication}`:''}</p></div><button onClick={()=>deleteMed(m.id)} className="p-1.5 text-slate-400 hover:text-rose-500"><Trash2 className="w-4 h-4"/></button></div>)}{!(activeTab==='prn'?prn:scheduled).length&&<div className="p-8 text-center text-xs text-slate-400">No {activeTab==='prn'?'PRN':'scheduled'} medications recorded.</div>}</div></div></div>}
  {showMed&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-md bg-white dark:bg-[#111C2E] rounded-2xl border border-slate-200 dark:border-slate-800 p-5 shadow-2xl"><div className="flex justify-between items-center"><h3 className="text-lg font-bold text-slate-900 dark:text-white">{activeTab==='prn'?'Add PRN Medication':'Add Patient Medication'}</h3><button onClick={()=>setShowMed(false)}><X/></button></div><form onSubmit={addMedication} className="space-y-3 mt-4"><input required value={medName} onChange={e=>setMedName(e.target.value)} placeholder="Medication name" className={input}/><input required value={medDose} onChange={e=>setMedDose(e.target.value)} placeholder="Dose (e.g. 5 mg)" className={input}/><select value={medRoute} onChange={e=>setMedRoute(e.target.value)} className={input}><option>Oral</option><option>IV</option><option>IM</option><option>SC</option><option>SL</option><option>Inhaled</option><option>Topical</option><option>Rectal</option><option>Other</option></select>{activeTab!=='prn'&&<select value={medFreq} onChange={e=>setMedFreq(e.target.value)} className={input}><option>Once daily (OD)</option><option>Twice daily (BID)</option><option>Three times daily (TID)</option><option>Four times daily (QID)</option><option>Every 4 hours</option><option>Every 6 hours</option><option>Every 8 hours</option><option>Every 12 hours</option><option>Other</option></select>}{activeTab==='prn'&&<input value={medFreq} onChange={e=>setMedFreq(e.target.value)} placeholder="PRN frequency / instruction (e.g. q6h PRN)" className={input}/>}<input value={medIndication} onChange={e=>setMedIndication(e.target.value)} placeholder={activeTab==='prn'?'PRN indication (e.g. pain, nausea)':'Indication'} className={input}/><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={()=>setShowMed(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Add Medication</button></div></form></div></div>}
  {showInf&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-lg max-h-[92vh] overflow-y-auto bg-white dark:bg-[#111C2E] rounded-2xl border border-slate-200 dark:border-slate-800 p-5 shadow-2xl"><div className="flex justify-between items-center"><div><h3 className="text-lg font-bold text-slate-900 dark:text-white">Add Continuous Infusion</h3><p className="text-xs text-slate-400 mt-1">Select a standard infusion or enter a custom infusion name.</p></div><button onClick={()=>setShowInf(false)}><X/></button></div><form onSubmit={addInfusion} className="space-y-3 mt-5"><input required value={infDrug} onChange={e=>setInfDrug(e.target.value)} placeholder="Infusion name (e.g. Norepinephrine or custom name)" className={input}/><div className="grid grid-cols-2 gap-3"><input required type="number" step="any" value={infDose} onChange={e=>setInfDose(e.target.value)} placeholder="Dose" className={input}/><select value={infUnit} onChange={e=>setInfUnit(e.target.value)} className={input}><option>mcg/kg/min</option><option>mcg/min</option><option>mg/hr</option><option>units/hr</option><option>mL/hr</option><option>Other</option></select></div><input required type="number" step="any" value={infRate} onChange={e=>setInfRate(e.target.value)} placeholder="Pump rate (mL/hr)" className={input}/><input value={infConcentration} onChange={e=>setInfConcentration(e.target.value)} placeholder="Concentration (optional)" className={input}/><input value={infCarrier} onChange={e=>setInfCarrier(e.target.value)} placeholder="Carrier fluid (optional)" className={input}/><input value={infLine} onChange={e=>setInfLine(e.target.value)} placeholder="Line / site (optional)" className={input}/><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={()=>setShowInf(false)} className="px-4 py-2 text-xs">Cancel</button><button className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Add Infusion</button></div></form></div></div>}
 </div>;
};
