import React,{useMemo,useState}from'react';
import{CheckCircle2,Clock3,FlaskConical,MessageSquare,PlayCircle,Plus,X}from'lucide-react';
import{Patient}from'../../../types/clinical';
import{useApp}from'../../../context/AppContext';
import{ClinicalWorkflowService}from'../../../services/clinicalWorkflowService';
interface Props{patient:Patient}
const invStatus=(status:string)=>status==='cancelled'?'Cancelled':status==='available'||status==='reviewed'||status==='acknowledged'?'Completed':status==='pending'?'In Progress':'Pending';
const consultStatus=(status:string)=>status==='Cancelled'?'Cancelled':status==='Completed'?'Completed':status==='In Progress'||status==='Accepted'?'In Progress':'Pending';
const statusClass=(status:string)=>status==='Completed'?'bg-emerald-500/10 text-emerald-600 border-emerald-500/30':status==='In Progress'?'bg-cyan-500/10 text-cyan-600 border-cyan-500/30':'bg-amber-500/10 text-amber-600 border-amber-500/30';

export const OrdersConsultationsSection:React.FC<Props>=({patient})=>{
 const{currentUser,updatePatient,showToast}=useApp();
 const[tab,setTab]=useState<'investigations'|'consultations'>('investigations');
 const[showAdd,setShowAdd]=useState(false);
 const[orderType,setOrderType]=useState<any>('CBC');
 const[specialty,setSpecialty]=useState('Cardiology');
 const[question,setQuestion]=useState('');
 const[priority,setPriority]=useState<'routine'|'urgent'|'stat'>('routine');
 const investigations=useMemo(()=>patient.investigations||[],[patient.investigations]);
 const consultations=useMemo(()=>patient.consultations||[],[patient.consultations]);

 const syncTask=(sourceType:'investigation'|'consultation',sourceId:string,status:'Pending'|'In Progress'|'Completed'|'Cancelled')=>{
   const target=ClinicalWorkflowService.getTasks().find(t=>t.patientId===patient.id&&t.sourceType===sourceType&&t.sourceId===sourceId);
   if(target){const next=status==='Completed'?'completed':status==='In Progress'?'in_progress':'pending';if(target.status!==next)ClinicalWorkflowService.updateTaskStatus(target.id,next,currentUser);}
 };

 const createOrder=()=>{
   const now=new Date().toISOString();
   if(tab==='investigations'){
     const inv:any={id:`inv-${Date.now()}`,patientId:patient.id,unitId:patient.unitId,type:orderType,title:orderType,status:'ordered',orderedAt:now,orderedBy:currentUser.name,flag:'normal'};
     updatePatient(patient.id,{investigations:[inv,...investigations]});
     ClinicalWorkflowService.addTask({patientId:patient.id,patientName:patient.fullName,unitId:patient.unitId,title:'Order Investigation',description:orderType,priority,assignedTo:currentUser.userId,createdBy:currentUser.name,status:'pending',sourceType:'investigation',sourceId:inv.id});
     showToast('Investigation order created.','success');
   }else{
     if(!specialty.trim()||!question.trim()){showToast('Specialty and clinical question are required.','error');return;}
     const con:any={id:`consult-${Date.now()}`,patientId:patient.id,unitId:patient.unitId,specialty:specialty.trim(),clinicalQuestion:question.trim(),status:'Requested',requestedBy:currentUser.name,requestedAt:now,priority};
     updatePatient(patient.id,{consultations:[con,...consultations]});
     ClinicalWorkflowService.addTask({patientId:patient.id,patientName:patient.fullName,unitId:patient.unitId,title:'Request Consult',description:con.specialty,priority,assignedTo:currentUser.userId,createdBy:currentUser.name,status:'pending',sourceType:'consultation',sourceId:con.id});
     showToast('Consultation request created.','success');
   }
   setShowAdd(false);setQuestion('');
 };

 const updateInvestigation=(id:string,status:'ordered'|'pending'|'available'|'reviewed'|'acknowledged'|'cancelled')=>{updatePatient(patient.id,{investigations:investigations.map(x=>x.id===id?{...x,status}:x)});syncTask('investigation',id,invStatus(status));showToast('Investigation status updated.','success');};
 const updateConsultation=(id:string,status:'Requested'|'Accepted'|'In Progress'|'Completed'|'Cancelled')=>{updatePatient(patient.id,{consultations:consultations.map(x=>x.id===id?{...x,status,...(status==='Completed'?{completedAt:new Date().toISOString()}: {})}:x)});syncTask('consultation',id,consultStatus(status));showToast('Consultation status updated.','success');};

 return <div className="space-y-5 max-w-5xl mx-auto">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-xl font-bold flex items-center gap-2"><FlaskConical className="w-5 h-5 text-cyan-500"/>Orders & Consultations</h2><p className="text-xs text-slate-500">Track investigations and consultations from request through completion.</p></div><div className="flex gap-2"><button onClick={()=>setTab('investigations')} className={`px-3 py-2 rounded-xl text-xs font-bold ${tab==='investigations'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800'}`}>Investigations ({investigations.length})</button><button onClick={()=>setTab('consultations')} className={`px-3 py-2 rounded-xl text-xs font-bold ${tab==='consultations'?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800'}`}>Consultations ({consultations.length})</button><button onClick={()=>setShowAdd(true)} className="inline-flex items-center gap-1 px-3 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Plus className="w-3.5 h-3.5"/>New</button></div></div>

  {tab==='investigations'&&<div className="space-y-2">{investigations.length?investigations.map(i=>{const status=invStatus(i.status);return <div key={i.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] p-4"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-500 flex items-center justify-center shrink-0"><FlaskConical className="w-5 h-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{i.title||i.type}</b><span className={`px-2 py-1 rounded-full border text-[9px] font-black uppercase ${statusClass(status)}`}>{status}</span>{i.flag==='critical'&&<span className="px-2 py-1 rounded-full bg-rose-500/10 text-rose-500 text-[9px] font-black">CRITICAL</span>}</div><div className="text-[10px] text-slate-400 mt-1">{i.orderedAt?new Date(i.orderedAt).toLocaleString():''} • Ordered by {i.orderedBy||'Clinical Team'}</div>{i.resultsSummary&&<div className="text-xs mt-2">{i.resultsSummary}</div>}</div></div><div className="flex flex-wrap gap-2 mt-3">{status!=='Pending'&&<button onClick={()=>updateInvestigation(i.id,'ordered')} className="px-3 py-1.5 rounded-lg bg-amber-500/10 text-amber-600 text-[10px] font-bold">Pending</button>}{status!=='In Progress'&&status!=='Completed'&&<button onClick={()=>updateInvestigation(i.id,'pending')} className="px-3 py-1.5 rounded-lg bg-cyan-500/10 text-cyan-600 text-[10px] font-bold">In Progress</button>}{status!=='Completed'&&<button onClick={()=>updateInvestigation(i.id,'available')} className="px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-600 text-[10px] font-bold">Completed / Resulted</button>}</div></div>}) : <div className="p-10 text-center text-xs text-slate-400 border border-dashed rounded-2xl">No investigation orders for this patient.</div>}</div>}

  {tab==='consultations'&&<div className="space-y-2">{consultations.length?consultations.map(c=>{const status=consultStatus(c.status);return <div key={c.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] p-4"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-violet-500/10 text-violet-500 flex items-center justify-center shrink-0"><MessageSquare className="w-5 h-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{c.specialty} Consultation</b><span className={`px-2 py-1 rounded-full border text-[9px] font-black uppercase ${statusClass(status)}`}>{status}</span></div><div className="text-[10px] text-slate-400 mt-1">{c.requestedAt?new Date(c.requestedAt).toLocaleString():''} • Requested by {c.requestedBy||'Clinical Team'}</div><div className="text-xs mt-2">{c.clinicalQuestion||'No clinical question documented.'}</div>{c.responseNotes&&<div className="text-xs text-slate-500 mt-2">{c.responseNotes}</div>}</div></div><div className="flex flex-wrap gap-2 mt-3">{status!=='Pending'&&<button onClick={()=>updateConsultation(c.id,'Requested')} className="px-3 py-1.5 rounded-lg bg-amber-500/10 text-amber-600 text-[10px] font-bold">Pending</button>}{status!=='In Progress'&&status!=='Completed'&&<button onClick={()=>updateConsultation(c.id,'In Progress')} className="px-3 py-1.5 rounded-lg bg-cyan-500/10 text-cyan-600 text-[10px] font-bold">In Progress</button>}{status!=='Completed'&&<button onClick={()=>updateConsultation(c.id,'Completed')} className="px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-600 text-[10px] font-bold">Completed</button>}</div></div>}) : <div className="p-10 text-center text-xs text-slate-400 border border-dashed rounded-2xl">No consultation requests for this patient.</div>}</div>}

  {showAdd&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-lg rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">New {tab==='investigations'?'Investigation Order':'Consultation'}</h3><p className="text-xs text-slate-500 mt-1">Patient: {patient.fullName} • Bed {patient.bedNumber||'—'}</p></div><button onClick={()=>setShowAdd(false)}><X className="w-4 h-4"/></button></div><div className="space-y-3 mt-4">{tab==='investigations'?<label className="text-xs font-semibold">Investigation<select value={orderType} onChange={e=>setOrderType(e.target.value)} className="w-full mt-1 rounded-xl border p-2.5 bg-white dark:bg-slate-900"><option>CBC</option><option>ABG</option><option>ECG</option><option>Troponin</option><option>CK-MB</option><option>BNP</option><option>Echo</option><option>Imaging</option><option>Other</option></select></label>:<><label className="text-xs font-semibold">Specialty<input value={specialty} onChange={e=>setSpecialty(e.target.value)} className="w-full mt-1 rounded-xl border p-2.5 bg-white dark:bg-slate-900"/></label><label className="text-xs font-semibold">Clinical question<textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={4} className="w-full mt-1 rounded-xl border p-2.5 bg-white dark:bg-slate-900"/></label></>}<label className="text-xs font-semibold">Priority<select value={priority} onChange={e=>setPriority(e.target.value as any)} className="w-full mt-1 rounded-xl border p-2.5 bg-white dark:bg-slate-900"><option value="routine">Routine</option><option value="urgent">Urgent</option><option value="stat">STAT</option></select></label></div><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setShowAdd(false)} className="px-4 py-2 rounded-xl text-xs">Cancel</button><button onClick={createOrder} className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Create Order</button></div></div></div>}
 </div>;
};
