import React,{useMemo}from'react';
import{Bell,AlertTriangle,CheckSquare,FlaskConical,MessageSquare,X,ChevronRight}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{ClinicalWorkflowService}from'../../services/clinicalWorkflowService';
import{AuthorizationService}from'../../services/authorizationService';

export const NotificationsCenterModal:React.FC<{isOpen:boolean;onClose:()=>void}>=({isOpen,onClose})=>{
 const{patients,currentUser,setCurrentPatientId,setCurrentView,setActivePatientSection}=useApp();
 const items=useMemo(()=>{const active=AuthorizationService.filterAuthorizedPatients(patients.filter(p=>!p.isArchived),currentUser);const out:any[]=[];
 active.filter(p=>p.status==='Critical').forEach(p=>out.push({id:'critical-'+p.id,type:'Critical patient',title:p.fullName,detail:p.primaryDiagnosis||'Critical status',patientId:p.id,icon:AlertTriangle,color:'text-rose-500'}));
 ClinicalWorkflowService.getTasks().filter(t=>t.status!=='completed'&&(!t.patientId||active.some(p=>p.id===t.patientId))).forEach(t=>out.push({id:'task-'+t.id,type:t.priority==='stat'?'STAT task':'Task assigned',title:t.title,detail:t.patientName||'Unit task',patientId:t.patientId,icon:CheckSquare,color:t.priority==='stat'?'text-rose-500':'text-cyan-500'}));
 active.forEach(p=>(p.investigations||[]).filter(i=>i.status==='available'||i.flag==='critical').forEach(i=>out.push({id:'inv-'+i.id,type:i.flag==='critical'?'Critical result':'Investigation result',title:i.title,detail:p.fullName+' • '+(i.resultsSummary||i.status),patientId:p.id,icon:FlaskConical,color:i.flag==='critical'?'text-rose-500':'text-amber-500'})));
 active.forEach(p=>(p.labResults||[]).filter((l:any)=>l.status==='critical'||l.flag==='critical').forEach((l:any)=>out.push({id:'lab-'+(l.id||l.name),type:'Critical lab result',title:l.name||l.testName||'Lab result',detail:p.fullName+' • '+String(l.value||'')+' '+String(l.unit||''),patientId:p.id,icon:FlaskConical,color:'text-rose-500'})));
 active.forEach(p=>(p.consultations||[]).filter(c=>c.status!=='Completed'&&c.status!=='Cancelled').forEach(c=>out.push({id:'consult-'+c.id,type:'Consult request',title:c.specialty,detail:p.fullName+' • '+c.status,patientId:p.id,icon:MessageSquare,color:'text-violet-500'})));
 return out.slice(0,50);
 },[patients,currentUser]);
 if(!isOpen)return null;
 const open=(id?:string,section:any='overview')=>{if(id){setCurrentPatientId(id);setActivePatientSection(section);setCurrentView('patient')}onClose()};
 return <div className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-start justify-end p-3 sm:p-5"><div className="w-full max-w-md max-h-[90vh] overflow-hidden bg-white dark:bg-[#111C2E] rounded-2xl border shadow-2xl"><div className="flex items-center justify-between p-4 border-b"><div><h2 className="font-black flex items-center gap-2"><Bell className="w-4 h-4 text-cyan-500"/>Notifications</h2><p className="text-[10px] text-slate-400">{items.length} actionable notifications</p></div><button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4"/></button></div><div className="max-h-[calc(90vh-80px)] overflow-y-auto p-2">{items.length?items.map(x=>{const Icon=x.icon;return <button key={x.id} onClick={()=>open(x.patientId,x.type.includes('lab')?'labs':x.type.includes('Investigation')?'orders':x.type.includes('Consult')?'orders':x.type.includes('Task')?'orders':'overview')} className="w-full text-left p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 flex gap-3"><div className={'w-9 h-9 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center '+x.color}><Icon className="w-4 h-4"/></div><div className="min-w-0 flex-1"><div className="text-[9px] uppercase font-black text-slate-400">{x.type}</div><div className="text-xs font-bold truncate">{x.title}</div><div className="text-[10px] text-slate-400 truncate">{x.detail}</div></div><ChevronRight className="w-4 h-4 text-slate-400 mt-2"/></button>}) : <div className="p-10 text-center text-xs text-slate-400">No actionable notifications.</div>}</div></div></div>;
};