import React,{useState}from'react';
import{Activity,Droplet,FileText,Pill,Cpu,CheckSquare,UserPlus,Stethoscope,FlaskConical,MessageSquare,X,ShieldAlert}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{ACCESS_DENIED_MESSAGE}from'../../services/authorizationService';
import{ClinicalWorkflowService}from'../../services/clinicalWorkflowService';
export const QuickAddModal:React.FC<{isOpen:boolean;onClose:()=>void;onSelectAction:(action:string)=>void}>=({isOpen,onClose,onSelectAction})=>{
 const{currentUser,patients,currentPatient,updatePatient,setCurrentView,setCurrentPatientId,setActivePatientSection,showToast}=useApp();const[selected,setSelected]=useState('');const[patientId,setPatientId]=useState(currentPatient?.id||patients.find(p=>!p.isArchived)?.id||'');const[text,setText]=useState('');const[title,setTitle]=useState('');const[priority,setPriority]=useState('routine');const[frequency,setFrequency]=useState('');const[specialty,setSpecialty]=useState('');const[type,setType]=useState('CBC');
 if(!isOpen)return null;
 if(currentUser.role==='viewer')return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60"><div className="bg-white dark:bg-slate-900 rounded-2xl p-6 max-w-sm w-full text-center"><ShieldAlert className="w-8 h-8 text-amber-500 mx-auto mb-3"/><h3 className="font-bold">Quick Add Disabled</h3><p className="text-sm text-slate-500 my-3">{ACCESS_DENIED_MESSAGE} Viewers have read-only access.</p><button onClick={onClose} className="px-5 py-2 rounded-xl bg-slate-100 dark:bg-slate-800">Close</button></div></div>;
 const actions=[{id:'quick-admission',label:'Admit Patient',icon:UserPlus},{id:'quick-labs',label:'Add Labs',icon:FlaskConical},{id:'quick-progress-note',label:'Clinical Progress Note',icon:Stethoscope},{id:'quick-med-order',label:'Medication Order',icon:Pill},{id:'quick-investigation',label:'Order Investigation',icon:FlaskConical},{id:'quick-consultation',label:'Request Consultation',icon:MessageSquare},{id:'quick-task',label:'Assign Clinical Task',icon:CheckSquare}];
 const nurse=[{id:'quick-vitals',label:'Vitals Entry',icon:Activity},{id:'quick-io',label:'Intake & Output',icon:Droplet},{id:'quick-nursing-note',label:'Nursing Note',icon:FileText},{id:'quick-med-admin',label:'Med Administration',icon:Pill},{id:'quick-device',label:'Device / Line',icon:Cpu},{id:'quick-task',label:'Clinical Task',icon:CheckSquare}];
 const list=currentUser.role==='nurse'?nurse:actions;
 const selectedPatient=patients.find(p=>p.id===patientId&&!p.isArchived);
 const close=()=>{setSelected('');setText('');setTitle('');setFrequency('');setSpecialty('');setType('CBC');onClose();};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(selected==='quick-admission'){onSelectAction(selected);close();return;}if(!selectedPatient){showToast('Select an active patient first.','error');return;}setCurrentPatientId(selectedPatient.id);if(selected==='quick-labs'){setActivePatientSection('labs');setCurrentView('patient');close();return;}if(selected==='quick-progress-note'||selected==='quick-nursing-note'){setActivePatientSection('progress');setCurrentView('patient');close();return;}if(selected==='quick-med-order'||selected==='quick-med-admin'){setActivePatientSection('medication');setCurrentView('patient');close();return;}if(selected==='quick-investigation'||selected==='quick-consultation'){setActivePatientSection('orders');setCurrentView('patient');close();return;}if(selected==='quick-task'){setCurrentView('my-worklist');close();return;}if(selected==='quick-vitals'){setActivePatientSection('vitals');setCurrentView('patient');close();return;}if(selected==='quick-device'||selected==='quick-procedure'){setActivePatientSection('procedure');setCurrentView('patient');close();return;}showToast('This workflow is not available for the current role.','warning');};
 const field=<>{selected!=='quick-admission'&&<div><label className="text-xs font-bold">Patient</label><select value={patientId} onChange={e=>setPatientId(e.target.value)} className="w-full mt-1 rounded-xl border p-2.5 bg-white dark:bg-slate-800"><option value="">Select patient</option>{patients.filter(p=>!p.isArchived).map(p=><option key={p.id} value={p.id}>{p.fullName} • {p.mrn}</option>)}</select></div>}{(selected==='quick-med-order'||selected==='quick-med-admin'||selected==='quick-task')&&<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder={selected==='quick-task'?'Task title':'Medication name'} className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm"/>}{selected==='quick-med-order'||selected==='quick-med-admin'?<><input required value={text} onChange={e=>setText(e.target.value)} placeholder="Dose / concentration" className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm"/><input value={frequency} onChange={e=>setFrequency(e.target.value)} placeholder="Frequency" className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm"/></>:selected==='quick-investigation'?<select value={type} onChange={e=>setType(e.target.value)} className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800"><option>CBC</option><option>ABG</option><option>ECG</option><option>Troponin</option><option>CK-MB</option><option>BNP</option><option>Echo</option><option>Imaging</option><option>Other</option></select>:selected==='quick-consultation'?<><input value={specialty} onChange={e=>setSpecialty(e.target.value)} placeholder="Specialty / consultant" className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm"/><textarea required value={text} onChange={e=>setText(e.target.value)} placeholder="Clinical question" className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm min-h-24"/></>:<textarea required value={text} onChange={e=>setText(e.target.value)} placeholder={selected==='quick-task'?'Task description':'Clinical documentation'} className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800 text-sm min-h-24"/>}{(selected==='quick-task'||selected==='quick-consultation')&&<select value={priority} onChange={e=>setPriority(e.target.value)} className="w-full rounded-xl border p-2.5 bg-white dark:bg-slate-800"><option value="routine">Routine</option><option value="urgent">Urgent</option><option value="stat">STAT</option></select>}</>;
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"><div className="bg-white dark:bg-slate-900 rounded-2xl p-5 max-w-lg w-full border border-slate-200 dark:border-slate-800 shadow-2xl"><div className="flex items-center justify-between pb-3 border-b"><div><div className="text-[10px] font-black uppercase text-cyan-500">{selected?'Clinical Workflow':'Quick Add'}</div><h3 className="text-lg font-bold">{selected?list.find(a=>a.id===selected)?.label:'Quick Add Action'}</h3></div><button onClick={close}><X/></button></div>{!selected?<div className="grid grid-cols-2 gap-2.5 py-4">{list.map(a=>{const I=a.icon;return <button key={a.id} onClick={()=>{if(a.id==='quick-admission'){onSelectAction(a.id);close();}else setSelected(a.id)}} className="flex items-center gap-3 p-3.5 rounded-xl border text-left hover:border-cyan-500"><I className="w-5 h-5 text-cyan-500"/><span className="text-xs font-semibold">{a.label}</span></button>})}</div>:<form onSubmit={submit} className="space-y-3 pt-4">{selected==='quick-admission'?<div className="text-sm text-slate-500">Opening the full admission workflow…</div>:field}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setSelected('')} className="px-4 py-2 text-xs">Back</button>{selected!=='quick-admission'&&<button className="px-5 py-2 rounded-xl bg-cyan-500 text-slate-950 font-bold text-xs">Open Patient Section</button>}</div></form>}</div></div>;
};