import React,{useMemo,useState}from'react';
import{AlertTriangle,BedDouble,ChevronRight,Cloud,FlaskConical,Plus,RefreshCw,Sparkles,CheckSquare,BookOpen,Search}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{AuthorizationService}from'../../services/authorizationService';
import{ClinicalWorkflowService}from'../../services/clinicalWorkflowService';
import{QuickAddModal}from'../navigation/QuickAddModal';

const Panel:React.FC<{children:React.ReactNode;className?:string}>=({children,className=''})=><section className={'rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 shadow-sm '+className}>{children}</section>;
const statusClass=(s:string)=>s==='Critical'?'bg-rose-500/10 text-rose-500':s==='Unstable'?'bg-amber-500/10 text-amber-500':'bg-emerald-500/10 text-emerald-500';
export const DashboardClinicalCenter:React.FC=()=>{
 const{patients,beds,units,currentUser,setCurrentPatientId,setCurrentView,isSyncing,lastSyncTime,syncNow,setCurrentUnitId}=useApp();
 const[quickOpen,setQuickOpen]=useState(false);
 const active=useMemo(()=>AuthorizationService.filterAuthorizedPatients(patients.filter(p=>!p.isArchived),currentUser),[patients,currentUser]);
 const scopedUnits=useMemo(()=>AuthorizationService.filterAuthorizedUnits(units,currentUser).filter(u=>beds.some(b=>b.unitId===u.id)),[units,beds,currentUser]);
 const activeIds=new Set(active.map(p=>p.id));
 const scopedBeds=currentUser.role==='department_admin'||currentUser.role==='consultant'?beds:beds.filter(b=>(currentUser.assignedUnitIds||[]).includes(b.unitId));
 const occupied=scopedBeds.filter(b=>b.patientId&&activeIds.has(b.patientId)).length;
 const critical=active.filter(p=>p.status==='Critical').length;
 const unstable=active.filter(p=>p.status==='Unstable').length;
 const tasks=useMemo(()=>ClinicalWorkflowService.getTasks().filter(t=>(t.status==='pending'||t.status==='in_progress')&&(!t.patientId||activeIds.has(t.patientId))),[patients,currentUser]);
 const actionCount=active.reduce((n,p)=>n+(p.investigations||[]).filter(i=>i.status==='ordered'||i.status==='pending'||i.status==='available').length+(p.consultations||[]).filter(c=>c.status!=='Completed').length,0);
 const attention=useMemo(()=>{const map=new Map<string,{patient:any;reasons:string[];severity:'critical'|'warning'}>();active.forEach(p=>{const reasons:string[]=[];if(p.status==='Critical')reasons.push('Critical status');if(p.status==='Unstable')reasons.push('Unstable');const inv=(p.investigations||[]).filter(i=>i.status==='available'||i.flag==='critical');if(inv.length)reasons.push(String(inv.length)+' result'+(inv.length>1?'s':'')+' pending review');const con=(p.consultations||[]).filter(c=>c.status!=='Completed');if(con.length)reasons.push(String(con.length)+' consult'+(con.length>1?'s':'')+' pending');if(reasons.length)map.set(p.id,{patient:p,reasons,severity:p.status==='Critical'||inv.some(i=>i.flag==='critical')?'critical':'warning'});});return Array.from(map.values()).sort((a,b)=>Number(b.severity==='critical')-Number(a.severity==='critical')).slice(0,4)},[active]);
 const unitStats=(id:string)=>{const bs=scopedBeds.filter(b=>b.unitId===id);const occ=bs.filter(b=>b.patientId&&activeIds.has(b.patientId));return{total:bs.length,occupied:occ.length,critical:occ.filter(b=>active.find(p=>p.id===b.patientId)?.status==='Critical').length,unstable:occ.filter(b=>active.find(p=>p.id===b.patientId)?.status==='Unstable').length}};
 const openPatient=(id:string)=>{setCurrentPatientId(id);setCurrentView('patient')};
 return <div className="space-y-3 pb-4">
  <div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-cyan-500">Department Command Center</div><h1 className="text-xl sm:text-2xl font-black">Today at a glance</h1><p className="text-[11px] text-slate-400 mt-1">Focused clinical actions for mobile workflow.</p></div><button onClick={()=>void syncNow()} className="p-2 rounded-xl bg-white dark:bg-[#111C2E] border" title={lastSyncTime?'Cloud synced':'Sync'}><RefreshCw className={'w-4 h-4 text-cyan-500 '+(isSyncing?'animate-spin':'')}/></button></div>
  <Panel className="p-3"><div className="flex items-center gap-3"><BedDouble className="w-5 h-5 text-cyan-500"/><div className="flex-1 min-w-0"><div className="flex justify-between text-[10px] font-bold"><span>{occupied}/{scopedBeds.length} beds occupied</span><span>{active.length} patients</span></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-800 mt-1.5"><div className="h-1.5 rounded-full bg-cyan-500" style={{width:(scopedBeds.length?Math.min(100,occupied/scopedBeds.length*100):0)+'%'}}/></div></div><div className="text-right text-[9px]"><span className="text-rose-500 font-black">{critical} critical</span><span className="text-amber-500 font-black ml-2">{unstable} unstable</span></div></div></Panel>
  <Panel className="p-3"><div className="flex items-center justify-between mb-2"><h2 className="text-sm font-black flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-rose-500"/>Patients Needing Attention</h2><button onClick={()=>setCurrentView('patients')} className="text-[10px] font-bold text-cyan-500">View all</button></div>{attention.length?<div className="space-y-2">{attention.map(({patient,reasons,severity})=>{const bed=beds.find(b=>b.id===patient.bedId);return <button key={patient.id} onClick={()=>openPatient(patient.id)} className={'w-full text-left p-3 rounded-xl border '+(severity==='critical'?'border-rose-200 bg-rose-50/40 dark:bg-rose-950/10':'border-amber-200 bg-amber-50/30 dark:bg-amber-950/10')}><div className="flex items-center justify-between gap-2"><div className="min-w-0"><div className="text-xs font-black truncate">{patient.fullName}</div><div className="text-[9px] text-slate-400 mt-0.5">Bed {bed?.bedNumber||'—'} • {patient.primaryDiagnosis||'No diagnosis'}</div></div><span className={'px-2 py-0.5 rounded-full text-[8px] font-black uppercase '+statusClass(patient.status)}>{patient.status}</span></div><div className="flex flex-wrap gap-1 mt-2">{reasons.slice(0,3).map(r=><span key={r} className="px-1.5 py-0.5 rounded bg-white/70 dark:bg-slate-900/60 text-[8px] font-bold text-slate-500">{r}</span>)}</div></button>})}</div>:<div className="py-5 text-center text-xs text-slate-400">No patients currently require urgent attention.</div>}</Panel>
  <Panel className="p-3"><div className="flex items-center justify-between mb-2"><h2 className="text-sm font-black flex items-center gap-2"><CheckSquare className="w-4 h-4 text-cyan-500"/>My Tasks <span className="px-1.5 py-0.5 rounded-full bg-rose-500 text-white text-[9px]">{tasks.length+actionCount}</span></h2><button onClick={()=>setCurrentView('my-worklist')} className="text-[10px] font-bold text-cyan-500">View all</button></div>{tasks.slice(0,3).map(t=><button key={t.id} onClick={()=>t.patientId&&openPatient(t.patientId)} className="w-full flex items-center gap-2.5 p-2.5 rounded-xl hover:bg-slate-50 dark:hover:bg-slate-800 text-left"><CheckSquare className="w-4 h-4 text-cyan-500 shrink-0"/><div className="min-w-0 flex-1"><div className="text-xs font-bold truncate">{t.title}</div><div className="text-[9px] text-slate-400">{t.patientName||'Unit task'} • {t.priority}</div></div><ChevronRight className="w-4 h-4 text-slate-400"/></button>)}{!tasks.length&&<div className="py-3 text-xs text-slate-400">No explicit tasks. {actionCount?String(actionCount)+' clinical action'+(actionCount>1?'s':'')+' pending.':'All caught up.'}</div>}</Panel>
  <Panel className="p-3"><div className="flex items-center justify-between mb-2"><h2 className="text-sm font-black flex items-center gap-2"><Plus className="w-4 h-4 text-cyan-500"/>Quick Add</h2><button onClick={()=>setQuickOpen(true)} className="text-[10px] font-bold text-cyan-500">More</button></div><div className="grid grid-cols-3 sm:grid-cols-6 gap-2">{[['Add Labs','labs',FlaskConical],['Investigation','inv',Search],['Consult','consult',Sparkles],['Task','task',CheckSquare],['Note','note',BookOpen],['More','more',Plus]].map(([label,id,Icon]:any)=><button key={id} onClick={()=>setQuickOpen(true)} className="min-h-[54px] rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-900/40 flex flex-col items-center justify-center gap-1"><Icon className="w-4 h-4 text-cyan-500"/><span className="text-[9px] font-bold">{label}</span></button>)}</div></Panel>
  <Panel className="p-3"><div className="flex items-center justify-between mb-2"><h2 className="text-sm font-black">Clinical Units</h2><span className="text-[9px] text-slate-400">{scopedUnits.length} units</span></div><div className="grid sm:grid-cols-2 gap-2">{scopedUnits.map(u=>{const s=unitStats(u.id);return <button key={u.id} onClick={()=>{setCurrentUnitId(u.id);setCurrentView('census')}} className="w-full text-left p-3 rounded-xl border border-slate-200 dark:border-slate-800"><div className="flex justify-between gap-2"><span className="text-xs font-black truncate">{u.name}</span><ChevronRight className="w-4 h-4 text-slate-400"/></div><div className="text-[9px] text-slate-400 mt-1">{s.occupied}/{s.total} occupied • <span className="text-rose-500">{s.critical} critical</span> • <span className="text-amber-500">{s.unstable} unstable</span></div></button>})}</div></Panel>
  <div className="flex items-center justify-between px-1 text-[9px] text-slate-400"><span className="flex items-center gap-1"><Cloud className="w-3 h-3 text-cyan-500"/>{isSyncing?'Syncing…':lastSyncTime?'Cloud synced':'Cloud sync pending'}</span><span>{scopedUnits.length} units • {active.length} patients</span></div>
  <QuickAddModal isOpen={quickOpen} onClose={()=>setQuickOpen(false)} onSelectAction={action=>{setQuickOpen(false);if(action==='quick-admission')setCurrentView('add-patient');else if(action==='quick-task')setCurrentView('my-worklist');else setCurrentView('patients')}}/>
 </div>
}