import React,{useEffect,useMemo,useState}from'react';
import{Search,X,ChevronRight,CheckSquare,FlaskConical,MessageSquare,BookOpen,Users}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{PATIENT_SECTIONS}from'../patient/PatientFileNav';
import{ClinicalWorkflowService}from'../../services/clinicalWorkflowService';
import{ComprehensiveProtocolService}from'../../services/comprehensiveProtocols';
import type{Patient}from'../../types/clinical';
import { getStoredWorkspaceAccess } from '../../services/workspaceAccess';

const SEARCH_FIELDS:Record<string,string[]>={overview:['fullName','mrn','primaryDiagnosis','secondaryDiagnoses','allergies','codeStatus','clinicalSummary'],history:['clinicalSummary','cardiovascularHistory','pastAdmissions'],vitals:['vitalsHistory','fluidRecords','hemodynamicHistory','fluidIntakeHistory','urineOutputHistory'],ecg:['ecgRecords'],examination:['examination'],cardiology:['cardiology'],medication:['medications'],icu:['ventilator'],imaging:['imaging'],labs:['labs','labResults'],procedure:['procedures'],calculators:['calculatorResults'],progress:['progressNotes'],'clinical-tools':['clinicalTools','clinicalToolsHistory'],pdf:['fullName','mrn','primaryDiagnosis','clinicalSummary','vitalsHistory','ecgRecords','cardiology','medications','ventilator','imaging','labs','procedures','calculatorResults','progressNotes']};

export const SearchModal:React.FC=()=>{const access=getStoredWorkspaceAccess();const allowedUnitIds=access?.role==='owner'?null:new Set((access?.unitIds?.length?access.unitIds:access?.unitId?[access.unitId]:[]).map(String));const{isSearchOpen,setIsSearchOpen,patients,units,currentPatient,currentView,setCurrentPatientId,setCurrentView,setCurrentUnitId,setActivePatientSection}=useApp();const[query,setQuery]=useState('');
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setIsSearchOpen(true)}else if(e.key==='Escape')setIsSearchOpen(false)};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[setIsSearchOpen]);
 useEffect(()=>{if(!isSearchOpen)setQuery('')},[isSearchOpen]);
 const q=query.trim().toLowerCase();const inPatient=currentView==='patient'&&!!currentPatient;
 const patientResults=useMemo(()=>{const scoped=patients.filter(p=>!allowedUnitIds||allowedUnitIds.has(String(p.unitId)));if(!q)return scoped.slice(0,6);return scoped.filter(p=>{const unit=units.find(u=>u.id===p.unitId);return [p.fullName,p.mrn,p.primaryDiagnosis,p.status,p.sex,p.codeStatus,p.unitId,unit?.name,p.bedId,p.clinicalSummary?.chiefComplaint,p.clinicalSummary?.hpi,...(p.secondaryDiagnoses||[])].filter(Boolean).join(' ').toLowerCase().includes(q)}).slice(0,12)},[q,patients,units,allowedUnitIds]);
 const taskResults=useMemo(()=>q?ClinicalWorkflowService.getTasks().filter(t=>[t.title,t.description,t.patientName,t.status,t.priority,t.assignedTo].filter(Boolean).join(' ').toLowerCase().includes(q)).slice(0,8):[],[q]);
 const clinicalResults=useMemo<any[]>(()=>{const scopedPatients=patients.filter(p=>!allowedUnitIds||allowedUnitIds.has(String(p.unitId)));if(!q)return[];const investigations=scopedPatients.flatMap(p=>(p.investigations||[]).filter(i=>[i.title,i.type,i.status,i.resultsSummary].filter(Boolean).join(' ').toLowerCase().includes(q)).map(i=>({kind:'investigation',patient:p,item:i})));const consults=scopedPatients.flatMap(p=>(p.consultations||[]).filter(c=>[c.specialty,c.status,c.clinicalQuestion,c.assignedClinician].filter(Boolean).join(' ').toLowerCase().includes(q)).map(c=>({kind:'consult',patient:p,item:c})));return [...investigations,...consults].slice(0,12)},[q,patients,allowedUnitIds]);
 const protocolResults=useMemo(()=>q?ComprehensiveProtocolService.getOfficialProtocols().concat(ComprehensiveProtocolService.getPersonalProtocols()).filter(p=>(p.title+' '+p.category+' '+p.content).toLowerCase().includes(q)).slice(0,8):[],[q]);
 const sectionResults=inPatient&&q&&currentPatient?PATIENT_SECTIONS.filter(section=>(SEARCH_FIELDS[section.id]||[]).some(key=>{const value=(currentPatient as any)[key];return value!==undefined&&value!==null&&JSON.stringify(value).toLowerCase().includes(q)})):[];

 if(!isSearchOpen)return null;
 const openPatient=(p:Patient)=>{setCurrentPatientId(p.id);setCurrentUnitId(p.unitId);setActivePatientSection('overview');setCurrentView('patient');setIsSearchOpen(false)};
 const goTask=(patientId?:string)=>{if(patientId){setCurrentPatientId(patientId);setCurrentView('patient')}else setCurrentView('my-worklist');setIsSearchOpen(false)};
 return <div className="fixed inset-0 z-50 flex items-start justify-center pt-20 sm:pt-28 px-4 bg-black/70 backdrop-blur-sm"><div className="fixed inset-0" onClick={()=>setIsSearchOpen(false)}/><div className="w-full max-w-2xl bg-white dark:bg-[#111C2E] rounded-2xl border border-slate-200 dark:border-slate-800 shadow-2xl overflow-hidden relative z-10"><div className="flex items-center px-4 py-3.5 border-b gap-3"><Search className="w-5 h-5 text-cyan-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={inPatient?'Search inside this patient file...':'Search patients, beds, tasks, investigations, consults or protocols...'} className="w-full bg-transparent text-sm outline-none"/><button onClick={()=>setIsSearchOpen(false)}><X className="w-5 h-5 text-slate-400"/></button></div><div className="max-h-[70vh] overflow-y-auto p-2 space-y-2">
 {inPatient?<section><div className="px-3 py-2 text-[10px] font-black uppercase text-cyan-500">This Patient File</div>{sectionResults.map(section=><button key={section.id} onClick={()=>{setActivePatientSection(section.id);setIsSearchOpen(false)}} className="w-full p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-left flex justify-between"><div><b className="text-xs">{section.label}</b><div className="text-[10px] text-slate-400">Matching saved data</div></div><ChevronRight className="w-4 h-4"/></button>)}{!sectionResults.length&&<div className="p-6 text-center text-xs text-slate-400">No matching data found.</div>}</section>:<>
 {q&&<><section><div className="px-3 py-1 text-[10px] font-black uppercase text-cyan-500 flex items-center gap-2"><Users className="w-3.5 h-3.5"/>Patients</div>{patientResults.map(p=><button key={p.id} onClick={()=>openPatient(p)} className="w-full p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-left flex justify-between"><div><b className="text-xs">{p.fullName}</b><div className="text-[10px] text-slate-400">MRN {p.mrn} • {units.find(u=>u.id===p.unitId)?.name||p.unitId} • Bed {p.bedId||'—'}</div></div><ChevronRight className="w-4 h-4"/></button>)}</section>
 <section><div className="px-3 py-1 text-[10px] font-black uppercase text-cyan-500 flex items-center gap-2"><CheckSquare className="w-3.5 h-3.5"/>Tasks</div>{taskResults.map(t=><button key={t.id} onClick={()=>goTask(t.patientId)} className="w-full p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-left flex justify-between"><div><b className="text-xs">{t.title}</b><div className="text-[10px] text-slate-400">{t.patientName||'Unit task'} • {t.status} • {t.priority}</div></div><ChevronRight className="w-4 h-4"/></button>)}</section>
 <section><div className="px-3 py-1 text-[10px] font-black uppercase text-cyan-500 flex items-center gap-2"><FlaskConical className="w-3.5 h-3.5"/>Investigations & Consults</div>{clinicalResults.map((x:any)=><button key={x.kind+'-'+x.item.id} onClick={()=>openPatient(x.patient)} className="w-full p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-left flex justify-between"><div><b className="text-xs">{x.kind==='investigation'?x.item.title:x.item.specialty}</b><div className="text-[10px] text-slate-400">{x.patient.fullName} • {x.item.status}</div></div><ChevronRight className="w-4 h-4"/></button>)}</section>
 <section><div className="px-3 py-1 text-[10px] font-black uppercase text-cyan-500 flex items-center gap-2"><BookOpen className="w-3.5 h-3.5"/>Protocols</div>{protocolResults.map(p=><button key={p.id} onClick={()=>{setCurrentView('protocols');setIsSearchOpen(false)}} className="w-full p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-left flex justify-between"><div><b className="text-xs">{p.title}</b><div className="text-[10px] text-slate-400">{p.category}</div></div><ChevronRight className="w-4 h-4"/></button>)}</section>
 </>}
 {!q&&<div className="p-8 text-center text-xs text-slate-400">Start typing to search across the clinical workspace.</div>}
 </>}
 </div><div className="px-4 py-2 bg-slate-50 dark:bg-slate-900/60 border-t text-[10px] text-slate-400 flex justify-between"><span>Ctrl/Cmd + K</span><span>ESC</span></div></div></div>};
