import React,{useEffect,useRef,useState}from'react';
import {App as CapacitorApp}from'@capacitor/app';
import {AppProvider,useApp}from'./context/AppContext';
import {AppHeader}from'./components/navigation/AppHeader';
import {BottomNav}from'./components/navigation/BottomNav';
import {LoginScreen}from'./components/auth/LoginScreen';
import {UnitAccessGate}from'./components/auth/UnitAccessGate';
import {DashboardClinicalCenter}from'./components/home/DashboardClinicalCenter';
import {UnitCensusView}from'./components/census/UnitCensusView';
import {PatientFileView}from'./components/patient/PatientFileView';
import {ActivePatientsView}from'./components/patients/ActivePatientsView';
import {AddPatientPage}from'./components/patient/AddPatientPage';
import {ArchiveView}from'./components/archive/ArchiveView';
import {CalculatorsHub}from'./components/calculators/CalculatorsHub';
import {SettingsView}from'./components/settings/SettingsView';
import {HandoverView}from'./components/handover/HandoverView';
import {PersonalWorklistView}from'./components/worklist/PersonalWorklistView';
import {TeamDirectoryView}from'./components/team/TeamDirectoryView';
import {ProtocolLibraryView}from'./components/protocols/ProtocolLibraryView';
import {DepartmentStatisticsView}from'./components/statistics/DepartmentStatisticsView';
import {AuditTrailView}from'./components/audit/AuditTrailView';
import {SearchModal}from'./components/search/SearchModal';
import {CheckCircle2,AlertCircle,Info,X,WifiOff}from'lucide-react';
import {Capacitor}from'@capacitor/core';
import {installWebRealtimeCloudSync} from'./services/webCloudSyncBridge';
import {ensureOwnerWorkspace,getStoredWorkspaceAccess,MASTER_ACCOUNT_EMAIL,MASTER_WORKSPACE_ID}from'./services/workspaceAccess';import {restoreLocalDataFromCloud}from'./services/cloudSyncBridge';
import {StorageService}from'./services/storage';
import './services/pdfArabicSupport';
import {installPdfDownloadBridge}from'./services/pdfDownloadBridge';

let refreshTimer:ReturnType<typeof setTimeout>|null=null;
const scheduleClinicalRefresh=()=>{if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{refreshTimer=null;window.dispatchEvent(new CustomEvent('cardiovault-data-restored'));},120);};
const snapshotData=(s:any):any=>{try{return typeof s?.data==='function'?s.data():(s?.data||{});}catch{return{};}};
const snapshotId=(s:any)=>String(s?.id||s?.documentId||s?.reference?.id||'');
const stripCloudMeta=(v:any)=>{if(!v||typeof v!=='object')return v;const{updatedAt,schemaVersion,...clinical}=v;return clinical;};
const replaceCollection=(collection:'units'|'beds'|'patients',event:any)=>{const snapshots=Array.isArray(event?.snapshots)?event.snapshots:[];const values=snapshots.map((s:any)=>({...stripCloudMeta(snapshotData(s)),id:snapshotId(s)})).filter((x:any)=>x.id);const previous=(StorageService as any)[collection==='units'?'getUnits':collection==='beds'?'getBeds':'getPatients']?.()||[];restoreLocalDataFromCloud(collection,values);if(previous.length!==values.length||JSON.stringify(previous)!==JSON.stringify(values)){localStorage.setItem('cardiovault_last_cloud_sync',new Date().toISOString());scheduleClinicalRefresh();}};

const AppContent:React.FC=()=>{const{auth,currentView,setCurrentView,toasts,dismissToast,syncNow}=useApp();const[accessReady,setAccessReady]=useState(()=>!Capacitor.isNativePlatform()||!!getStoredWorkspaceAccess());const[online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);const handlingPop=useRef(false);const hasLocalSession=!!localStorage.getItem('cardiovault_auth_v2');
 useEffect(()=>{installPdfDownloadBridge();},[]);
 useEffect(()=>{const onOnline=()=>{setOnline(true);void syncNow();};const onOffline=()=>setOnline(false);window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);};},[syncNow]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||Capacitor.isNativePlatform())return;let active=true;const start=async()=>{try{const stop=await installWebRealtimeCloudSync(()=>{if(active){window.dispatchEvent(new CustomEvent('cardiovault-data-restored'));}});return stop;}catch(error){console.warn('Web realtime cloud sync setup failed:',error);return ()=>{};}};let stop:(()=>void)|null=null;void start().then(fn=>{if(active)stop=fn;else fn();});return()=>{active=false;stop?.();};},[auth.isAuthenticated,auth.isLocked,auth.userEmail]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;if(!window.history.state?.cardiovault)window.history.replaceState({cardiovault:true,view:currentView},'');},[auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady,currentView]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;if(handlingPop.current){handlingPop.current=false;return;}const current=window.history.state?.view;if(current!==currentView)window.history.pushState({cardiovault:true,view:currentView},'');},[currentView,auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;const onPop=()=>{const view=window.history.state?.view;if(view){handlingPop.current=true;setCurrentView(view);}};const onBack=async()=>{if(currentView==='patient'){const detail={handled:false};window.dispatchEvent(new CustomEvent('cardiovault-patient-back',{detail}));if(detail.handled)return;}if(window.history.length>1)window.history.back();else await CapacitorApp.exitApp();};window.addEventListener('popstate',onPop);let listener:{remove:()=>Promise<void>}|undefined;CapacitorApp.addListener('backButton',onBack).then(x=>{listener=x;}).catch(()=>{});return()=>{window.removeEventListener('popstate',onPop);void listener?.remove();};},[auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady,setCurrentView,currentView]);
 if(!online)return <div className="min-h-screen bg-[#070B13] text-white flex items-center justify-center p-6"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-[#0F172A] p-7 text-center shadow-2xl"><div className="w-14 h-14 mx-auto rounded-2xl bg-rose-500/10 text-rose-400 flex items-center justify-center mb-4"><WifiOff className="w-7 h-7"/></div><h1 className="text-xl font-extrabold">Internet connection required</h1><p className="text-sm text-slate-400 mt-2">CardioVault is cloud-only. Clinical data is not available in Offline Mode. Reconnect to the internet to continue.</p><div className="mt-4 text-[11px] text-slate-500">Waiting for a secure cloud connection…</div></div></div>;
 if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession)return <LoginScreen/>;if(Capacitor.isNativePlatform()&&!accessReady)return <UnitAccessGate/>;const render=()=>{switch(currentView){case'home':return <div className="max-w-7xl mx-auto w-full px-3 sm:px-6 py-4 space-y-4"><DashboardClinicalCenter/></div>;case'census':return <UnitCensusView/>;case'handover':return <HandoverView/>;case'patient':return <PatientFileView/>;case'patients':return <ActivePatientsView/>;case'add-patient':return <AddPatientPage/>;case'archive':return <ArchiveView/>;case'calculators':return <CalculatorsHub/>;case'my-worklist':return <PersonalWorklistView/>;case'team':return <TeamDirectoryView/>;case'protocols':return <ProtocolLibraryView/>;case'statistics':return <DepartmentStatisticsView/>;case'audit-trail':return <AuditTrailView/>;case'settings':return <SettingsView/>;default:return <DashboardClinicalCenter/>;}};return <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-[#070B13] text-slate-900 dark:text-slate-100 transition-colors duration-200"><AppHeader/><main className="flex-1 w-full safe-bottom-content">{render()}</main><BottomNav/><SearchModal/><div className="fixed bottom-[calc(4.5rem+var(--safe-area-inset-bottom,env(safe-area-inset-bottom,0px)))] md:bottom-[calc(1rem+var(--safe-area-inset-bottom,env(safe-area-inset-bottom,0px)))] right-4 z-50 flex flex-col gap-2 max-w-sm w-full pointer-events-none">{toasts.map(t=><div key={t.id} className={`pointer-events-auto flex items-center justify-between p-3.5 rounded-2xl shadow-xl border text-xs backdrop-blur-md ${t.type==='success'?'bg-emerald-950/90 border-emerald-500/40 text-emerald-100':t.type==='error'?'bg-rose-950/90 border-rose-500/40 text-rose-100':t.type==='warning'?'bg-amber-950/90 border-amber-500/40 text-amber-100':'bg-slate-900/90 border-slate-700 text-slate-100'}`}><div className="flex items-center gap-2.5">{t.type==='success'?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:t.type==='error'?<AlertCircle className="w-4 h-4 text-rose-400"/>:<Info className="w-4 h-4 text-cyan-400"/>}<span className="font-medium leading-tight">{t.message}</span></div><button onClick={()=>dismissToast(t.id)} className="p-1 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white shrink-0 ml-2"><X className="w-3.5 h-3.5"/></button></div>)}</div></div>};
export default function App(){return <AppProvider><AppContent/></AppProvider>;}