import React,{useEffect,useRef,useState}from'react';
import {App as CapacitorApp}from'@capacitor/app';
import {FirebaseFirestore}from'@capacitor-firebase/firestore';
import {AppProvider,useApp}from'./context/AppContext';
import {AppHeader}from'./components/navigation/AppHeader';
import {BottomNav}from'./components/navigation/BottomNav';
import {LoginScreen}from'./components/auth/LoginScreen';
import {UnitAccessGate}from'./components/auth/UnitAccessGate';
import {DashboardClinicalCenter}from'./components/home/DashboardClinicalCenter';
import {UnitCensusView}from'./components/census/UnitCensusView';
import {PatientFileView}from'./components/patient/PatientFileView';
import {ActivePatientsView}from'./components/patients/ActivePatientsView';
import {AddPatientPage}from'./components/patient/AddPatientPage';
import {ArchiveView}from'./components/archive/ArchiveView';
import {CalculatorsHub}from'./components/calculators/CalculatorsHub';
import {SettingsView}from'./components/settings/SettingsView';
import {HandoverView}from'./components/handover/HandoverView';
import {SearchModal}from'./components/search/SearchModal';
import {CheckCircle2,AlertCircle,Info,X,WifiOff}from'lucide-react';
import {Capacitor}from'@capacitor/core';
import {ensureOwnerWorkspace,getStoredWorkspaceAccess,MASTER_ACCOUNT_EMAIL,MASTER_WORKSPACE_ID}from'./services/workspaceAccess';
import {StorageService}from'./services/storage';
import './services/pdfArabicSupport';
import {installPdfDownloadBridge}from'./services/pdfDownloadBridge';

let refreshTimer:ReturnType<typeof setTimeout>|null=null;
const scheduleClinicalRefresh=()=>{if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{refreshTimer=null;window.dispatchEvent(new CustomEvent('cardiovault-data-restored'));},120);};
const snapshotData=(snapshot:any):any=>{try{return typeof snapshot?.data==='function'?snapshot.data():(snapshot?.data||{});}catch{return{};}};
const snapshotId=(snapshot:any):string=>String(snapshot?.id||snapshot?.documentId||snapshot?.reference?.id||'');
const stripCloudMeta=(value:any)=>{if(!value||typeof value!=='object')return value;const{updatedAt,schemaVersion,...clinical}=value;return clinical;};
const replaceCollection=(collection:'units'|'beds'|'patients',event:any)=>{const snapshots=Array.isArray(event?.snapshots)?event.snapshots:[];const values=snapshots.map((s:any)=>({...stripCloudMeta(snapshotData(s)),id:snapshotId(s)})).filter((x:any)=>x.id);const previous=(StorageService as any)[collection==='units'?'getUnits':collection==='beds'?'getBeds':'getPatients']?.()||[];if(collection==='units')StorageService.saveUnits(values);else if(collection==='beds')StorageService.saveBeds(values);else StorageService.savePatients(values);if(previous.length!==values.length||JSON.stringify(previous)!==JSON.stringify(values)){localStorage.setItem('cardiovault_last_cloud_sync',new Date().toISOString());scheduleClinicalRefresh();}};

const AppContent:React.FC=()=>{const{auth,currentView,setCurrentView,toasts,dismissToast,syncNow}=useApp();const[accessReady,setAccessReady]=useState(()=>!Capacitor.isNativePlatform()||!!getStoredWorkspaceAccess());const[online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);const[providerRefresh,setProviderRefresh]=useState(0);const handlingPop=useRef(false);const hasLocalSession=!!localStorage.getItem('cardiovault_auth_v2');
 useEffect(()=>{installPdfDownloadBridge();},[]);
 useEffect(()=>{const onOnline=()=>{setOnline(true);void syncNow();};const onOffline=()=>setOnline(false);window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);};},[syncNow]);
 useEffect(()=>{const onCloudRestore=()=>setProviderRefresh(x=>x+1);window.addEventListener('cardiovault-data-restored',onCloudRestore);window.addEventListener('cardiovault-workspace-access-granted',onCloudRestore);return()=>{window.removeEventListener('cardiovault-data-restored',onCloudRestore);window.removeEventListener('cardiovault-workspace-access-granted',onCloudRestore);};},[]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!Capacitor.isNativePlatform())return;let active=true;let attempts=0;const check=async()=>{const email=String(auth.userEmail||'').trim().toLowerCase();if(email===MASTER_ACCOUNT_EMAIL){if(active)setAccessReady(true);try{await ensureOwnerWorkspace();}catch(error){console.warn('Master workspace bootstrap failed:',error);}return;}const stored=getStoredWorkspaceAccess();if(active)setAccessReady(!!stored);if(!stored&&attempts<16){attempts+=1;window.setTimeout(()=>void check(),500);}};void check();const onAccess=()=>setAccessReady(true);window.addEventListener('cardiovault-workspace-access-granted',onAccess);window.addEventListener('cardiovault-data-restored',onAccess);return()=>{active=false;window.removeEventListener('cardiovault-workspace-access-granted',onAccess);window.removeEventListener('cardiovault-data-restored',onAccess);};},[auth.isAuthenticated,auth.isLocked,auth.userEmail]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!Capacitor.isNativePlatform())return;let active=true;const callbackIds:string[]=[];let retryTimer:ReturnType<typeof setTimeout>|null=null;const removeListeners=async()=>{for(const callbackId of callbackIds.splice(0)){try{await FirebaseFirestore.removeSnapshotListener({callbackId});}catch{}}};const start=async()=>{await new Promise(r=>setTimeout(r,800));if(!active)return;try{await FirebaseFirestore.enableNetwork();const email=String(auth.userEmail||'').trim().toLowerCase();let access=getStoredWorkspaceAccess();if(email===MASTER_ACCOUNT_EMAIL){try{await ensureOwnerWorkspace();}catch(error){console.warn('Realtime master workspace bootstrap failed:',error);}access={workspaceId:MASTER_WORKSPACE_ID,role:'owner',unitId:null,unitName:null};}if(!access?.workspaceId){retryTimer=setTimeout(()=>void start(),3000);return;}await removeListeners();const addCollection=async(collection:string,unitId?:string)=>{const options:any={reference:`workspaces/${access!.workspaceId}/${collection}`};if(unitId)options.compositeFilter={type:'and',queryConstraints:[{type:'where',fieldPath:'unitId',opStr:'==',value:unitId}]};const callbackId=await FirebaseFirestore.addCollectionSnapshotListener(options,(event:any,error:any)=>{if(error){console.warn(`Realtime ${collection} listener failed:`,error);return;}replaceCollection(collection as 'units'|'beds'|'patients',event);});callbackIds.push(callbackId);await new Promise(r=>setTimeout(r,80));};const addUnitDocument=async(unitId:string)=>{const callbackId=await FirebaseFirestore.addDocumentSnapshotListener({reference:`workspaces/${access!.workspaceId}/units/${unitId}`},(event:any,error:any)=>{if(error){console.warn('Realtime unit listener failed:',error);return;}const data=stripCloudMeta(snapshotData(event?.snapshot));const unitIdValue=snapshotId(event?.snapshot)||unitId;const current=StorageService.getUnits();const next=data&&Object.keys(data).length?[{...data,id:unitIdValue}]:[];if(JSON.stringify(current)!==JSON.stringify(next)){StorageService.saveUnits(next);localStorage.setItem('cardiovault_last_cloud_sync',new Date().toISOString());scheduleClinicalRefresh();}});callbackIds.push(callbackId);};
 if(access.role==='owner'){await addCollection('units');await addCollection('beds');await addCollection('patients');}else if(access.unitId){await addUnitDocument(String(access.unitId));await addCollection('beds',String(access.unitId));await addCollection('patients',String(access.unitId));}else{retryTimer=setTimeout(()=>void start(),3000);return;}
 }catch(error){console.warn('Realtime cloud sync setup failed:',error);if(active)retryTimer=setTimeout(()=>void start(),3000);}};void start();return()=>{active=false;if(retryTimer)clearTimeout(retryTimer);void removeListeners();};},[auth.isAuthenticated,auth.isLocked,auth.userEmail,accessReady]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;if(!window.history.state?.cardiovault)window.history.replaceState({cardiovault:true,view:currentView},'');},[auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady,currentView]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;if(handlingPop.current){handlingPop.current=false;return;}const current=window.history.state?.view;if(current!==currentView)window.history.pushState({cardiovault:true,view:currentView},'');},[currentView,auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady]);
 useEffect(()=>{if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession||!accessReady)return;const onPop=()=>{const view=window.history.state?.view;if(view){handlingPop.current=true;setCurrentView(view);}};const onBack=async()=>{if(currentView==='patient'){const detail={handled:false};window.dispatchEvent(new CustomEvent('cardiovault-patient-back',{detail}));if(detail.handled)return;}if(window.history.length>1)window.history.back();else await CapacitorApp.exitApp();};window.addEventListener('popstate',onPop);let listener:{remove:()=>Promise<void>}|undefined;CapacitorApp.addListener('backButton',onBack).then(x=>{listener=x;}).catch(()=>{});return()=>{window.removeEventListener('popstate',onPop);void listener?.remove();};},[auth.isAuthenticated,auth.isLocked,hasLocalSession,accessReady,setCurrentView,currentView]);
 if(!online)return <div className="min-h-screen bg-[#070B13] text-white flex items-center justify-center p-6"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-[#0F172A] p-7 text-center shadow-2xl"><div className="w-14 h-14 mx-auto rounded-2xl bg-rose-500/10 text-rose-400 flex items-center justify-center mb-4"><WifiOff className="w-7 h-7"/></div><h1 className="text-xl font-extrabold">Internet connection required</h1><p className="text-sm text-slate-400 mt-2">CardioVault is cloud-only. Clinical data is not available in Offline Mode. Reconnect to the internet to continue.</p><div className="mt-4 text-[11px] text-slate-500">Waiting for a secure cloud connection…</div></div></div>;
 if(!auth.isAuthenticated||auth.isLocked||!hasLocalSession)return <LoginScreen/>;if(Capacitor.isNativePlatform()&&!accessReady)return <UnitAccessGate/>;const render=()=>{switch(currentView){case'home':return <div className="max-w-7xl mx-auto w-full px-3 sm:px-6 py-4 space-y-4"><DashboardClinicalCenter/></div>;case'census':return <UnitCensusView/>;case'handover':return <HandoverView/>;case'patient':return <PatientFileView/>;case'patients':return <ActivePatientsView/>;case'add-patient':return <AddPatientPage/>;case'archive':return <ArchiveView/>;case'calculators':return <CalculatorsHub/>;case'settings':return <SettingsView/>;default:return <DashboardClinicalCenter/>;}};return <div key={providerRefresh} className="min-h-screen flex flex-col bg-slate-50 dark:bg-[#070B13] text-slate-900 dark:text-slate-100 transition-colors duration-200"><AppHeader/><main className="flex-1 w-full safe-bottom-content">{render()}</main><BottomNav/><SearchModal/><div className="fixed bottom-[calc(4.5rem+var(--safe-area-inset-bottom,env(safe-area-inset-bottom,0px)))] md:bottom-[calc(1rem+var(--safe-area-inset-bottom,env(safe-area-inset-bottom,0px)))] right-4 z-50 flex flex-col gap-2 max-w-sm w-full pointer-events-none">{toasts.map(t=><div key={t.id} className={`pointer-events-auto flex items-center justify-between p-3.5 rounded-2xl shadow-xl border text-xs backdrop-blur-md ${t.type==='success'?'bg-emerald-950/90 border-emerald-500/40 text-emerald-100':t.type==='error'?'bg-rose-950/90 border-rose-500/40 text-rose-100':t.type==='warning'?'bg-amber-950/90 border-amber-500/40 text-amber-100':'bg-slate-900/90 border-slate-700 text-slate-100'}`}><div className="flex items-center gap-2.5">{t.type==='success'?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:t.type==='error'?<AlertCircle className="w-4 h-4 text-rose-400"/>:<Info className="w-4 h-4 text-cyan-400"/>}<span className="font-medium leading-tight">{t.message}</span></div><button onClick={()=>dismissToast(t.id)} className="p-1 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white shrink-0 ml-2"><X className="w-3.5 h-3.5"/></button></div>)}</div></div>;};
export default function App(){const[refresh,setRefresh]=useState(0);useEffect(()=>{const onRestore=()=>setRefresh(x=>x+1);window.addEventListener('cardiovault-data-restored',onRestore);window.addEventListener('cardiovault-workspace-access-granted',onRestore);return()=>{window.removeEventListener('cardiovault-data-restored',onRestore);window.removeEventListener('cardiovault-workspace-access-granted',onRestore);};},[]);return <AppProvider key={refresh}><AppContent/></AppProvider>;}