import React,{useMemo,useState}from'react';
import {Search,Calculator,Heart,Activity,Wind,Gauge,Droplets,Syringe,ChevronRight,Star,Clock3,ShieldAlert}from'lucide-react';
import {Patient}from'../../types/clinical';
import {CARDIOVAULT_CALCULATORS}from'../../services/calculatorCatalog';
import {FocusedCalculator}from'./FocusedCalculator';
interface Props{patient?:Patient;embedded?:boolean;}
type Filter='All'|'Cardiology'|'Emergency & Risk'|'Critical Care'|'ABG'|'Hemodynamics'|'Renal & Electrolytes'|'Drug Infusion';
const iconFor=(category:string)=>category==='Cardiology'?Heart:category==='Emergency & Risk'?ShieldAlert:category==='Critical Care'?Activity:category==='ABG'?Wind:category==='Hemodynamics'?Gauge:category==='Renal & Electrolytes'?Droplets:category==='Drug Infusion'?Syringe:Calculator;
const colorFor=(category:string)=>category==='Cardiology'?'bg-rose-500/15 text-rose-500':category==='Emergency & Risk'?'bg-orange-500/15 text-orange-500':category==='Critical Care'?'bg-blue-500/15 text-blue-500':category==='ABG'?'bg-cyan-500/15 text-cyan-500':category==='Hemodynamics'?'bg-violet-500/15 text-violet-500':category==='Renal & Electrolytes'?'bg-emerald-500/15 text-emerald-500':category==='Drug Infusion'?'bg-amber-500/15 text-amber-500':'bg-slate-500/15 text-slate-500';
const read=(key:string):string[]=>{try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x.filter(v=>typeof v==='string'):[]}catch{return[]}};
export const CalculatorsHub:React.FC<Props>=({patient,embedded=false})=>{
 const[filter,setFilter]=useState<Filter>('All');const[query,setQuery]=useState('');const[selectedId,setSelectedId]=useState<string|null>(null);const[showFav,setShowFav]=useState(false);const[favorites,setFavorites]=useState<string[]>(()=>read('cardiovault_calculator_favorites_v1'));const[recent,setRecent]=useState<string[]>(()=>read('cardiovault_calculator_recent_v1'));
 const filters:Filter[]=['All','Cardiology','Emergency & Risk','Critical Care','ABG','Hemodynamics','Renal & Electrolytes','Drug Infusion'];
 const toggleFavorite=(id:string,e:React.MouseEvent)=>{e.stopPropagation();setFavorites(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];localStorage.setItem('cardiovault_calculator_favorites_v1',JSON.stringify(next));return next;});};
 const openCalculator=(id:string)=>{setSelectedId(id);setRecent(prev=>{const next=[id,...prev.filter(x=>x!==id)].slice(0,8);localStorage.setItem('cardiovault_calculator_recent_v1',JSON.stringify(next));return next;});};
 const list=useMemo(()=>CARDIOVAULT_CALCULATORS.filter(c=>{const matchFilter=filter==='All'||c.category===filter;const matchQuery=`${c.name} ${c.subtitle} ${c.description}`.toLowerCase().includes(query.toLowerCase());const matchFav=!showFav||favorites.includes(c.id);return matchFilter&&matchQuery&&matchFav;}),[filter,query,showFav,favorites]);
 const selected=CARDIOVAULT_CALCULATORS.find(c=>c.id===selectedId);
 if(selected)return <div className={`${embedded?'':'max-w-5xl mx-auto px-4 py-6'}`}><FocusedCalculator definition={selected} patient={patient} onBack={()=>setSelectedId(null)}/></div>;
 const recentItems=recent.map(id=>CARDIOVAULT_CALCULATORS.find(c=>c.id===id)).filter(Boolean).slice(0,5) as typeof CARDIOVAULT_CALCULATORS;
 return <div className={`${embedded?'':'max-w-5xl mx-auto px-4 py-6'} space-y-4 animate-in fade-in duration-150`}>
  <div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-cyan-500/10 text-cyan-500 flex items-center justify-center"><Calculator className="w-5 h-5"/></div><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Calculators</h1><p className="text-xs text-slate-500 dark:text-slate-400">Interactive clinical calculators using entered inputs only.</p></div></div>
  <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search calculators..." className="w-full pl-9 pr-4 py-3 rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 text-sm text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/30"/></div>
  <div className="flex gap-2 overflow-x-auto no-scrollbar pb-1">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${filter===f?'bg-cyan-500 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{f}</button>)}<button onClick={()=>setShowFav(x=>!x)} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap flex items-center gap-1 ${showFav?'bg-amber-400 text-slate-950':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}><Star className="w-3.5 h-3.5"/>Favorites</button></div>
  {!query&&!showFav&&recentItems.length>0&&<div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111C2E] p-3"><div className="flex items-center gap-2 text-xs font-black mb-2"><Clock3 className="w-4 h-4 text-cyan-500"/>Recently used</div><div className="flex gap-2 overflow-x-auto no-scrollbar">{recentItems.map(c=><button key={c.id} onClick={()=>openCalculator(c.id)} className="shrink-0 rounded-xl border border-slate-200 dark:border-slate-800 px-3 py-2 text-left min-w-[170px]"><div className="text-xs font-bold truncate">{c.name}</div><div className="text-[10px] text-slate-400">{c.category}</div></button>)}</div></div>}
  <div className="space-y-1.5">{list.map(c=>{const Icon=iconFor(c.category);const fav=favorites.includes(c.id);return <button key={c.id} onClick={()=>openCalculator(c.id)} className="w-full text-left flex items-center gap-3 p-3.5 rounded-2xl bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 hover:border-cyan-500/50 transition-all"><div className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 ${colorFor(c.category)}`}><Icon className="w-5 h-5"/></div><div className="min-w-0 flex-1"><div className="font-bold text-sm text-slate-900 dark:text-white">{c.name}</div><div className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{c.subtitle}</div></div><button aria-label={fav?'Remove favorite':'Add favorite'} onClick={e=>toggleFavorite(c.id,e)} className={`p-2 rounded-xl ${fav?'text-amber-400':'text-slate-400'} hover:bg-slate-100 dark:hover:bg-slate-800`}><Star className="w-4 h-4" fill={fav?'currentColor':'none'}/></button><ChevronRight className="w-5 h-5 text-slate-400"/></button>})}</div>
  {list.length===0&&<div className="p-10 text-center border border-dashed rounded-2xl text-slate-400">No calculators match your search.</div>}
 </div>;
};
