import React, { useState } from 'react';
import { ArrowLeft, Calculator } from 'lucide-react';
import { MedicalCalculators, CalculatorDefinition } from '../../services/calculators';
import { Patient } from '../../types/clinical';

interface Props { definition: CalculatorDefinition; patient?: Patient; onBack: () => void; }
const Toggle:React.FC<{label:string;value:boolean;onChange:(v:boolean)=>void}>=({label,value,onChange})=><label className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-900/70 border border-slate-200 dark:border-slate-800 text-sm cursor-pointer"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} className="w-4 h-4 accent-cyan-500"/><span>{label}</span></label>;
const Select:React.FC<{value:number;onChange:(n:number)=>void;options:Array<[number,string]>}>=({value,onChange,options})=><select value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full px-3 py-2.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-700 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;
const Result:React.FC<{children:React.ReactNode}>=({children})=><div className="mt-5 p-4 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-slate-700 dark:text-slate-200">{children}</div>;

export const FocusedCalculator:React.FC<Props>=({definition,patient,onBack})=>{
 const age=patient?.age||58;
 const [chaAge,setChaAge]=useState(age),[chaSex,setChaSex]=useState<'Male'|'Female'>(patient?.sex==='Female'?'Female':'Male'),[chaChf,setChaChf]=useState(false),[chaHtn,setChaHtn]=useState(false),[chaStroke,setChaStroke]=useState(false),[chaVascular,setChaVascular]=useState(false),[chaDiabetes,setChaDiabetes]=useState(false);
 const [hasHtn,setHasHtn]=useState(false),[hasRenal,setHasRenal]=useState(false),[hasLiver,setHasLiver]=useState(false),[hasStroke,setHasStroke]=useState(false),[hasBleed,setHasBleed]=useState(false),[hasLabile,setHasLabile]=useState(false),[hasElderly,setHasElderly]=useState(age>65),[hasDrugs,setHasDrugs]=useState(false),[hasAlcohol,setHasAlcohol]=useState(false);
 const [heartHistory,setHeartHistory]=useState(0),[heartEcg,setHeartEcg]=useState(0),[heartAge,setHeartAge]=useState(age>=65?2:age>=45?1:0),[heartRisk,setHeartRisk]=useState(0),[heartTroponin,setHeartTroponin]=useState(0);
 const [timiAge,setTimiAge]=useState(false),[timiCad,setTimiCad]=useState(false),[timiKnown,setTimiKnown]=useState(false),[timiAspirin,setTimiAspirin]=useState(false),[timiAngina,setTimiAngina]=useState(false),[timiMarkers,setTimiMarkers]=useState(false),[timiSt,setTimiSt]=useState(false);
 const cha=MedicalCalculators.calcCHA2DS2VASc({chf:chaChf,htn:chaHtn,age75Plus:chaAge>=75,diabetes:chaDiabetes,strokeOrTia:chaStroke,vascularDisease:chaVascular,age65To74:chaAge>=65&&chaAge<75,isFemale:chaSex==='Female'});
 const has=MedicalCalculators.calcHASBLED({hypertension:hasHtn,renalDisease:hasRenal,liverDisease:hasLiver,strokeHistory:hasStroke,priorBleeding:hasBleed,labileINR:hasLabile,elderly:hasElderly,drugs:hasDrugs,alcohol:hasAlcohol});
 const heart=MedicalCalculators.calcHEART({history:heartHistory,ecg:heartEcg,age:heartAge,riskFactors:heartRisk,troponin:heartTroponin});
 const timi=MedicalCalculators.calcTIMINSTEMI({age65Plus:timiAge,threeCadFactors:timiCad,knownCadStenosis50:timiKnown,aspirinPast7Days:timiAspirin,severeAnginaPast24h:timiAngina,elevatedMarkers:timiMarkers,stDeviation05mm:timiSt});
 const render=()=>{switch(definition.id){
 case 'cha2ds2-vasc':return <><div className="grid sm:grid-cols-2 gap-3"><div><label className="text-xs text-slate-500">Age</label><input type="number" value={chaAge} onChange={e=>setChaAge(Number(e.target.value))} className="w-full mt-1 px-3 py-2.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-700"/></div><div><label className="text-xs text-slate-500">Sex</label><select value={chaSex} onChange={e=>setChaSex(e.target.value as 'Male'|'Female')} className="w-full mt-1 px-3 py-2.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-700"><option>Male</option><option>Female</option></select></div></div><div className="grid gap-2 mt-4"><Toggle label="Heart failure / LV dysfunction" value={chaChf} onChange={setChaChf}/><Toggle label="Hypertension" value={chaHtn} onChange={setChaHtn}/><Toggle label="Prior stroke / TIA" value={chaStroke} onChange={setChaStroke}/><Toggle label="Vascular disease / CAD" value={chaVascular} onChange={setChaVascular}/><Toggle label="Diabetes mellitus" value={chaDiabetes} onChange={setChaDiabetes}/></div><Result><div className="flex justify-between font-bold"><span>Score: {cha.score}</span><span>{cha.risk} Risk</span></div><p className="text-xs mt-2">Annual stroke rate: {cha.strokeRisk}</p><p className="text-xs mt-1">{cha.recommendation}</p></Result></>;
 case 'has-bled':return <><div className="grid gap-2"><Toggle label="Hypertension (SBP >160 mmHg)" value={hasHtn} onChange={setHasHtn}/><Toggle label="Abnormal renal function" value={hasRenal} onChange={setHasRenal}/><Toggle label="Abnormal liver function" value={hasLiver} onChange={setHasLiver}/><Toggle label="Stroke history" value={hasStroke} onChange={setHasStroke}/><Toggle label="Prior major bleeding" value={hasBleed} onChange={setHasBleed}/><Toggle label="Labile INR" value={hasLabile} onChange={setHasLabile}/><Toggle label="Age >65 years" value={hasElderly} onChange={setHasElderly}/><Toggle label="Drugs / antiplatelets / NSAIDs" value={hasDrugs} onChange={setHasDrugs}/><Toggle label="Alcohol excess" value={hasAlcohol} onChange={setHasAlcohol}/></div><Result><div className="flex justify-between font-bold"><span>Score: {has.score}</span><span>{has.riskLevel}</span></div><p className="text-xs mt-2">Bleeding rate: {has.bleedingRate}</p><p className="text-xs mt-1">{has.advice}</p></Result></>;
 case 'heart-score':return <><div className="grid gap-4"><div><label className="text-xs text-slate-500">History</label><Select value={heartHistory} onChange={setHeartHistory} options={[[0,'Slightly suspicious (0)'],[1,'Moderately suspicious (1)'],[2,'Highly suspicious (2)']]}/></div><div><label className="text-xs text-slate-500">ECG</label><Select value={heartEcg} onChange={setHeartEcg} options={[[0,'Normal (0)'],[1,'Non-specific repolarization / BBB (1)'],[2,'Significant ST depression (2)']]}/></div><div><label className="text-xs text-slate-500">Age</label><Select value={heartAge} onChange={setHeartAge} options={[[0,'<45 years (0)'],[1,'45–64 years (1)'],[2,'≥65 years (2)']]}/></div><div><label className="text-xs text-slate-500">Risk factors</label><Select value={heartRisk} onChange={setHeartRisk} options={[[0,'None (0)'],[1,'1–2 risk factors (1)'],[2,'≥3 risk factors / known atherosclerotic disease (2)']]}/></div><div><label className="text-xs text-slate-500">Troponin</label><Select value={heartTroponin} onChange={setHeartTroponin} options={[[0,'≤1× normal limit (0)'],[1,'1–3× normal limit (1)'],[2,'>3× normal limit (2)']]}/></div></div><Result><div className="flex justify-between font-bold"><span>HEART: {heart.score}/10</span><span>{heart.risk} Risk</span></div><p className="text-xs mt-2">MACE estimate: {heart.maceRate}</p><p className="text-xs mt-1">{heart.management}</p></Result></>;
 case 'timi-nstemi':return <><div className="grid gap-2"><Toggle label="Age ≥65 years" value={timiAge} onChange={setTimiAge}/><Toggle label="≥3 CAD risk factors" value={timiCad} onChange={setTimiCad}/><Toggle label="Known CAD stenosis ≥50%" value={timiKnown} onChange={setTimiKnown}/><Toggle label="Aspirin use in past 7 days" value={timiAspirin} onChange={setTimiAspirin}/><Toggle label="Severe angina in past 24 hours" value={timiAngina} onChange={setTimiAngina}/><Toggle label="Elevated cardiac markers" value={timiMarkers} onChange={setTimiMarkers}/><Toggle label="ST deviation ≥0.5 mm" value={timiSt} onChange={setTimiSt}/></div><Result><div className="flex justify-between font-bold"><span>TIMI: {timi.score}/7</span><span>{timi.risk.split(' (')[0]}</span></div><p className="text-xs mt-2">{timi.risk}</p></Result></>;
 default:return <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 text-sm">This calculator continues to use the existing validated calculation engine. A dedicated one-calculator screen is applied to the core Cardiology scores; remaining tools retain their existing engine until their focused form is migrated.</div>;
 }};
 return <div className="space-y-4"><button onClick={onBack} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-bold text-cyan-600 dark:text-cyan-400 bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800"><ArrowLeft className="w-4 h-4"/> Back to Calculators</button><div className="bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm"><div className="flex items-start gap-3"><div className="w-11 h-11 rounded-xl bg-cyan-500/10 text-cyan-500 flex items-center justify-center"><Calculator className="w-5 h-5"/></div><div><h2 className="text-xl font-bold text-slate-900 dark:text-white">{definition.name}</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{definition.description}</p></div></div><div className="mt-5">{render()}</div><div className="mt-6 pt-4 border-t border-slate-200 dark:border-slate-800 text-[11px] text-slate-500">Verify inputs and interpret results in clinical context.</div></div></div>;
};
