import React,{useState} from 'react';
import { Settings, Shield, Moon, Sun, Lock, Database, RefreshCw, User, Download, Upload, Building2, BedDouble, Cloud, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { StorageService } from '../../services/storage';
import { UnitManagementModalV2 } from '../units/UnitManagementModalV2';
import { BedManagementModal } from '../units/BedManagementModal';

export const SettingsView:React.FC=()=>{
 const{theme,toggleTheme,auth,lockApp,resetDatabase,showToast,syncNow,isSyncing,lastSyncTime}=useApp();
 const[showUnits,setShowUnits]=useState(false),[showBeds,setShowBeds]=useState(false),[syncError,setSyncError]=useState(()=>localStorage.getItem('cardiovault_last_cloud_sync_error_detail')||'');
 const[doctorName,setDoctorName]=useState(auth.userName),[doctorEmail,setDoctorEmail]=useState(auth.userEmail),[newPin,setNewPin]=useState(''),[confirmPin,setConfirmPin]=useState('');
 const updateProfile=(e:React.FormEvent)=>{e.preventDefault();StorageService.saveAuth({userName:doctorName,userEmail:doctorEmail});showToast('Clinician profile updated.','success');};
 const updatePin=(e:React.FormEvent)=>{
   e.preventDefault();
   const cleanPin=newPin.replace(/\D/g,'').slice(0,4),cleanConfirm=confirmPin.replace(/\D/g,'').slice(0,4);
   if(cleanPin.length!==4){showToast('PIN must be exactly 4 digits.','error');return;}
   if(cleanPin!==cleanConfirm){showToast('PIN confirmation does not match.','error');return;}
   StorageService.saveAuth({pinCode:cleanPin});
   setNewPin('');setConfirmPin('');
   showToast('Security PIN updated successfully.','success');
   window.setTimeout(()=>window.location.reload(),250);
 };
 const backup=()=>{const data=StorageService.exportDatabaseBackup();const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`cardiovault_backup_${new Date().toISOString().split('T')[0]}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Clinical database exported.','success');};
 const importBackup=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.name.toLowerCase().endsWith('.json')){showToast('Please select a CardioVault JSON backup file.','error');return;}const reader=new FileReader();reader.onload=()=>{try{const text=String(reader.result||'');const parsed=JSON.parse(text);if(!Array.isArray(parsed?.units)||!Array.isArray(parsed?.beds)||!Array.isArray(parsed?.patients)){showToast('Invalid CardioVault backup: units, beds and patients are required.','error');return;}if(!window.confirm(`Import this backup and replace the current local database?\n\n${parsed.patients.length} patients • ${parsed.units.length} units • ${parsed.beds.length} beds`))return;if(!StorageService.importDatabaseBackup(text)){showToast('Backup could not be imported.','error');return;}showToast('Backup imported successfully. Reloading…','success');window.setTimeout(()=>window.location.reload(),350);}catch(error){console.error('Backup import error:',error);showToast('Invalid or corrupted backup file.','error');}};reader.onerror=()=>showToast('Unable to read the backup file.','error');reader.readAsText(file);};
 const retryCloudSync=async()=>{setSyncError('');showToast('Testing CardioVault cloud connection…','info');await syncNow();const detail=localStorage.getItem('cardiovault_last_cloud_sync_error_detail')||'';setSyncError(detail);if(detail){showToast(`Cloud Sync error: ${detail}`,'error');}else{showToast('Cloud Sync completed successfully.','success');}};
 const clearDisplayedError=()=>{setSyncError('');};
 const card='bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm';
 const input='w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-cyan-500/40 focus:border-cyan-500 touch-manipulation';
 return <div className="max-w-4xl mx-auto px-4 py-6 pb-28 space-y-6 animate-in fade-in duration-150">
   <div><h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><Settings className="w-6 h-6 text-cyan-500"/> System Settings & Security</h1><p className="text-xs text-slate-500 dark:text-slate-400">Physician profile, privacy, appearance, data persistence and clinical units.</p></div>
   <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
     <div className={card}><h2 className="text-sm font-bold mb-4 flex items-center gap-2"><User className="w-4 h-4 text-cyan-500"/> Clinician Profile</h2><form onSubmit={updateProfile} className="space-y-3"><label className="text-xs font-semibold">Full Name & Title<input type="text" value={doctorName} onChange={e=>setDoctorName(e.target.value)} className={input+' mt-1'} /></label><label className="text-xs font-semibold">Email<input type="email" value={doctorEmail} onChange={e=>setDoctorEmail(e.target.value)} className={input+' mt-1'} /></label><button type="submit" className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Update Profile</button></form></div>
     <div className={card}><h2 className="text-sm font-bold mb-4 flex items-center gap-2"><Shield className="w-4 h-4 text-emerald-500"/> Security PIN</h2><form onSubmit={updatePin} className="space-y-3"><div className="grid grid-cols-2 gap-2"><div><label className="block text-[11px] text-slate-500 dark:text-slate-400 mb-1">New PIN</label><input type="text" inputMode="numeric" autoComplete="new-password" maxLength={4} placeholder="••••" value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,'').slice(0,4))} className={input+' text-center tracking-[0.45em]'} /></div><div><label className="block text-[11px] text-slate-500 dark:text-slate-400 mb-1">Confirm PIN</label><input type="text" inputMode="numeric" autoComplete="new-password" maxLength={4} placeholder="••••" value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,'').slice(0,4))} className={input+' text-center tracking-[0.45em]'} /></div></div><div className="flex flex-wrap gap-2"><button type="submit" className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-xs font-bold touch-manipulation">Confirm PIN</button><button type="button" onClick={lockApp} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-semibold touch-manipulation"><Lock className="inline w-3.5 h-3.5"/> Lock Screen</button></div><p className="text-[10px] text-slate-500 dark:text-slate-400">Enter 4 digits in both fields, then press Confirm PIN.</p></form></div>
     <div className={card}><h2 className="text-sm font-bold mb-3 flex items-center gap-2">{theme==='dark'?<Sun className="w-4 h-4 text-amber-400"/>:<Moon className="w-4 h-4 text-indigo-500"/>} Visual Theme</h2><button type="button" onClick={toggleTheme} className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-semibold touch-manipulation">{theme==='dark'?'Switch to Light Mode':'Switch to Dark Mode'}</button></div>
     <div className={card}><h2 className="text-sm font-bold mb-3 flex items-center gap-2"><Database className="w-4 h-4 text-cyan-500"/> Database & Backup</h2><div className="flex flex-wrap gap-2"><button type="button" onClick={backup} className="px-3 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Download className="inline w-3.5 h-3.5"/> Export Backup</button><label className="px-3 py-2 rounded-xl bg-emerald-500 text-white text-xs font-bold cursor-pointer"><Upload className="inline w-3.5 h-3.5"/> Import Backup<input type="file" accept="application/json,.json" onChange={importBackup} className="hidden"/></label><button type="button" onClick={()=>{if(window.confirm('Reset database to the standard clinical sample?'))resetDatabase();}} className="px-3 py-2 rounded-xl bg-rose-500/10 text-rose-500 border border-rose-500/30 text-xs font-semibold"><RefreshCw className="inline w-3.5 h-3.5"/> Reset Sample</button></div><p className="text-[10px] text-slate-500 dark:text-slate-400 mt-2">Import replaces the current local clinical database after confirmation.</p></div>
   </div>
   <div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><Cloud className="w-5 h-5 text-cyan-500"/> Cloud Sync Diagnostics</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Test the current Firebase account and show the exact Firestore sync error instead of a generic message.</p></div><button type="button" disabled={isSyncing} onClick={retryCloudSync} className="px-4 py-2 rounded-xl bg-cyan-500 disabled:opacity-50 text-slate-950 text-xs font-bold touch-manipulation"><RefreshCw className={`inline w-3.5 h-3.5 mr-1 ${isSyncing?'animate-spin':''}`}/> {isSyncing?'Testing…':'Test Cloud Sync'}</button></div><div className="mt-4 space-y-2"><div className="flex items-center gap-2 text-xs"><CheckCircle2 className="w-4 h-4 text-emerald-500"/><span>Authenticated account:</span><strong className="break-all">{auth.userEmail||'No local account email'}</strong></div><div className="text-[11px] text-slate-500 dark:text-slate-400">Last successful sync: {lastSyncTime||'Not recorded in this session'}</div>{syncError?<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-700 dark:text-rose-300"><div className="font-bold flex items-center gap-2 mb-1"><AlertCircle className="w-4 h-4"/> Exact Cloud Sync error</div><div className="font-mono break-words">{syncError}</div><button type="button" onClick={clearDisplayedError} className="mt-2 text-[11px] underline">Clear displayed error</button></div>:<div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900 p-3 text-xs text-slate-500 dark:text-slate-400">No stored Cloud Sync error detail. Press <strong>Test Cloud Sync</strong> to run a fresh diagnostic.</div>}</div></div>
   <div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><Building2 className="w-5 h-5 text-cyan-500"/> Unit Management</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Add, rename or safely delete clinical units.</p></div><button type="button" onClick={()=>setShowUnits(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Manage Units</button></div></div>
   <div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><BedDouble className="w-5 h-5 text-cyan-500"/> Bed Management</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Add beds or remove empty beds from any clinical unit.</p></div><button type="button" onClick={()=>setShowBeds(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Manage Beds</button></div></div>
   <UnitManagementModalV2 isOpen={showUnits} onClose={()=>setShowUnits(false)}/><BedManagementModal isOpen={showBeds} onClose={()=>setShowBeds(false)}/>
 </div>;
};
