import React,{useEffect,useState} from 'react';
import {Settings,Shield,Moon,Sun,Lock,Database,RefreshCw,User,Download,Upload,Building2,BedDouble,Cloud,AlertCircle,CheckCircle2,KeyRound,Copy,Eye,EyeOff,LockKeyhole} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {StorageService} from '../../services/storage';
import {UnitManagementModalV2} from '../units/UnitManagementModalV2';
import {BedManagementModal} from '../units/BedManagementModal';
import {canManageStructure,getUnitAccessCodes,generateUnitAccessCode,revokeUnitAccessCode,isOwnerAccess,UnitAccessCode} from '../../services/workspaceAccess';

export const SettingsView:React.FC=()=>{
 const{theme,toggleTheme,auth,lockApp,resetDatabase,showToast,syncNow,isSyncing,lastSyncTime,units}=useApp();
 const[showUnits,setShowUnits]=useState(false),[showBeds,setShowBeds]=useState(false),[syncError,setSyncError]=useState(()=>localStorage.getItem('cardiovault_last_cloud_sync_error_detail')||'');
 const[doctorName,setDoctorName]=useState(auth.userName),[newPin,setNewPin]=useState(''),[confirmPin,setConfirmPin]=useState('');
 const[accessCodes,setAccessCodes]=useState<UnitAccessCode[]>([]);const[loadingCodes,setLoadingCodes]=useState(false);const[showCodes,setShowCodes]=useState(true);
 const owner=isOwnerAccess()&&canManageStructure();
 const refreshCodes=async()=>{if(!owner)return;setLoadingCodes(true);try{setAccessCodes(await getUnitAccessCodes());}catch(error:any){showToast(String(error?.message||'Could not load Unit Access Codes.'),'error');}finally{setLoadingCodes(false);}};
 useEffect(()=>{void refreshCodes();},[owner,units.length]);
 const updateProfile=(e:React.FormEvent)=>{e.preventDefault();StorageService.saveAuth({userName:doctorName});showToast('Clinician profile updated.','success');};
 const updatePin=(e:React.FormEvent)=>{e.preventDefault();const cleanPin=newPin.replace(/\D/g,'').slice(0,4),cleanConfirm=confirmPin.replace(/\D/g,'').slice(0,4);if(cleanPin.length!==4){showToast('PIN must be exactly 4 digits.','error');return;}if(cleanPin!==cleanConfirm){showToast('PIN confirmation does not match.','error');return;}StorageService.saveAuth({pinCode:cleanPin});setNewPin('');setConfirmPin('');showToast('Security PIN updated successfully.','success');window.setTimeout(()=>window.location.reload(),250);};
 const backup=()=>{const data=StorageService.exportDatabaseBackup();const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`cardiovault_backup_${new Date().toISOString().split('T')[0]}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Clinical database exported.','success');};
 const importBackup=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.name.toLowerCase().endsWith('.json')){showToast('Please select a CardioVault JSON backup file.','error');return;}const reader=new FileReader();reader.onload=()=>{try{const text=String(reader.result||'');const parsed=JSON.parse(text);if(!Array.isArray(parsed?.units)||!Array.isArray(parsed?.beds)||!Array.isArray(parsed?.patients)){showToast('Invalid CardioVault backup: units, beds and patients are required.','error');return;}if(!window.confirm(`Import this backup and replace the current local database?\n\n${parsed.patients.length} patients • ${parsed.units.length} units • ${parsed.beds.length} beds`))return;if(!StorageService.importDatabaseBackup(text)){showToast('Backup could not be imported.','error');return;}showToast('Backup imported successfully. Reloading…','success');window.setTimeout(()=>window.location.reload(),350);}catch(error){console.error('Backup import error:',error);showToast('Invalid or corrupted backup file.','error');}};reader.onerror=()=>showToast('Unable to read the backup file.','error');reader.readAsText(file);};
 const retryCloudSync=async()=>{setSyncError('');showToast('Testing CardioVault cloud connection…','info');await syncNow();const detail=localStorage.getItem('cardiovault_last_cloud_sync_error_detail')||'';setSyncError(detail);if(detail)showToast(`Cloud Sync error: ${detail}`,'error');else showToast('Cloud Sync completed successfully.','success');};
 const copyCode=async(code:string)=>{try{await navigator.clipboard.writeText(code);showToast('Unit Access Code copied.','success');}catch{showToast(code,'info');}};
 const generateForUnit=async(unitId:string,unitName:string)=>{try{const code=await generateUnitAccessCode(unitId,unitName,'clinical_editor');await refreshCodes();await copyCode(code);}catch(error:any){showToast(String(error?.message||'Could not generate access code.'),'error');}};
 const revoke=async(code:string)=>{if(!window.confirm('Revoke this Unit Access Code? Anyone using the old code will lose access after the session is refreshed.'))return;try{await revokeUnitAccessCode(code);await refreshCodes();showToast('Unit Access Code revoked.','success');}catch(error:any){showToast(String(error?.message||'Could not revoke code.'),'error');}};
 const card='bg-white dark:bg-[#111C2E] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm';const input='w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-cyan-500/40 focus:border-cyan-500';
 return <div className="max-w-4xl mx-auto px-4 py-6 pb-28 space-y-6 animate-in fade-in duration-150">
   <div><h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><Settings className="w-6 h-6 text-cyan-500"/> System Settings & Security</h1><p className="text-xs text-slate-500 dark:text-slate-400">Physician profile, privacy, cloud workspace and clinical units.</p></div>
   <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
    <div className={card}><h2 className="text-sm font-bold mb-4 flex items-center gap-2"><User className="w-4 h-4 text-cyan-500"/> Clinician Profile</h2><form onSubmit={updateProfile} className="space-y-3"><label className="text-xs font-semibold">Full Name & Title<input type="text" value={doctorName} onChange={e=>setDoctorName(e.target.value)} className={input+' mt-1'}/></label><label className="text-xs font-semibold">Google/Firebase Account Email<input type="email" value={auth.userEmail} readOnly className={input+' mt-1 opacity-70 cursor-not-allowed'}/></label><button type="submit" className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Update Profile</button></form></div>
    <div className={card}><h2 className="text-sm font-bold mb-4 flex items-center gap-2"><Shield className="w-4 h-4 text-emerald-500"/> Security PIN</h2><form onSubmit={updatePin} className="space-y-3"><div className="grid grid-cols-2 gap-2"><input type="text" inputMode="numeric" maxLength={4} placeholder="New PIN" value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,'').slice(0,4))} className={input+' text-center tracking-[0.45em]'}/><input type="text" inputMode="numeric" maxLength={4} placeholder="Confirm PIN" value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,'').slice(0,4))} className={input+' text-center tracking-[0.45em]'}/></div><div className="flex flex-wrap gap-2"><button type="submit" className="px-4 py-2 rounded-xl bg-emerald-500 text-white text-xs font-bold">Confirm PIN</button><button type="button" onClick={lockApp} className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-semibold"><Lock className="inline w-3.5 h-3.5"/> Lock Screen</button></div></form></div>
    <div className={card}><h2 className="text-sm font-bold mb-3 flex items-center gap-2">{theme==='dark'?<Sun className="w-4 h-4 text-amber-400"/>:<Moon className="w-4 h-4 text-indigo-500"/>} Visual Theme</h2><button type="button" onClick={toggleTheme} className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-semibold">{theme==='dark'?'Switch to Light Mode':'Switch to Dark Mode'}</button></div>
    <div className={card}><h2 className="text-sm font-bold mb-3 flex items-center gap-2"><Database className="w-4 h-4 text-cyan-500"/> Database & Backup</h2><div className="flex flex-wrap gap-2"><button type="button" onClick={backup} className="px-3 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold"><Download className="inline w-3.5 h-3.5"/> Export Backup</button><label className="px-3 py-2 rounded-xl bg-emerald-500 text-white text-xs font-bold cursor-pointer"><Upload className="inline w-3.5 h-3.5"/> Import Backup<input type="file" accept="application/json,.json" onChange={importBackup} className="hidden"/></label>{owner&&<button type="button" onClick={()=>{if(window.confirm('Reset database to the standard clinical sample?'))resetDatabase();}} className="px-3 py-2 rounded-xl bg-rose-500/10 text-rose-500 border border-rose-500/30 text-xs font-semibold"><RefreshCw className="inline w-3.5 h-3.5"/> Reset Sample</button>}</div><p className="text-[10px] text-slate-500 dark:text-slate-400 mt-2">Clinical data remains scoped to the active CardioVault Workspace.</p></div>
   </div>
   {owner&&<div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><KeyRound className="w-5 h-5 text-cyan-500"/> Unit Access Codes</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Each Unit has its own code. Give a code only to users who should see that Unit.</p></div><button type="button" onClick={()=>setShowCodes(v=>!v)} className="px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-xs font-semibold">{showCodes?<EyeOff className="inline w-3.5 h-3.5 mr-1"/>:<Eye className="inline w-3.5 h-3.5 mr-1"/>}{showCodes?'Hide':'Show'} Codes</button></div><div className="mt-4 space-y-3">{loadingCodes?<div className="text-xs text-slate-500">Loading codes…</div>:units.map(unit=>{const existing=accessCodes.find(c=>c.unitId===unit.id&&c.active);return <div key={unit.id} className="rounded-xl border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div><div className="font-bold text-sm">{unit.name}</div><div className="text-[10px] text-slate-500">{existing?'Active access code':'No active code'}</div></div>{showCodes&&existing?<div className="flex items-center gap-2"><code className="px-2 py-1 rounded-lg bg-slate-100 dark:bg-slate-900 font-mono text-xs tracking-wider">{existing.code}</code><button type="button" onClick={()=>void copyCode(existing.code)} className="p-2 rounded-lg bg-cyan-500/10 text-cyan-500"><Copy className="w-4 h-4"/></button><button type="button" onClick={()=>void revoke(existing.code)} className="p-2 rounded-lg bg-rose-500/10 text-rose-500"><LockKeyhole className="w-4 h-4"/></button></div>:<button type="button" onClick={()=>void generateForUnit(unit.id,unit.name)} className="px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 text-xs font-bold"><KeyRound className="inline w-3.5 h-3.5 mr-1"/> Generate Code</button>}</div></div>})}</div></div>}
   <div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><Cloud className="w-5 h-5 text-cyan-500"/> Cloud Sync</h2><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Current account and exact Firestore sync diagnostics.</p></div><button type="button" disabled={isSyncing} onClick={retryCloudSync} className="px-4 py-2 rounded-xl bg-cyan-500 disabled:opacity-50 text-slate-950 text-xs font-bold"><RefreshCw className={`inline w-3.5 h-3.5 mr-1 ${isSyncing?'animate-spin':''}`}/>{isSyncing?'Testing…':'Test Cloud Sync'}</button></div><div className="mt-4 space-y-2"><div className="flex items-center gap-2 text-xs"><CheckCircle2 className="w-4 h-4 text-emerald-500"/><span>Authenticated account:</span><strong className="break-all">{auth.userEmail||'No account email'}</strong></div><div className="text-[11px] text-slate-500">Last successful sync: {lastSyncTime||'Not recorded in this session'}</div>{syncError&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-700 dark:text-rose-300"><div className="font-bold flex items-center gap-2 mb-1"><AlertCircle className="w-4 h-4"/> Exact Cloud Sync error</div><div className="font-mono break-words">{syncError}</div></div>}</div></div>
   {owner&&<><div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><Building2 className="w-5 h-5 text-cyan-500"/> Unit Management</h2><p className="text-xs text-slate-500 mt-1">Owner-only: add, rename or delete clinical units.</p></div><button type="button" onClick={()=>setShowUnits(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Manage Units</button></div></div><div className={card}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-base font-bold flex items-center gap-2"><BedDouble className="w-5 h-5 text-cyan-500"/> Bed Management</h2><p className="text-xs text-slate-500 mt-1">Owner-only: add/remove beds and change unit capacity.</p></div><button type="button" onClick={()=>setShowBeds(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-xs font-bold">Manage Beds</button></div></div></>}
   {!owner&&<div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs text-amber-700 dark:text-amber-300"><LockKeyhole className="inline w-4 h-4 mr-2"/>Unit and Bed Management is restricted to the Workspace Owner.</div>}
   {owner&&<><UnitManagementModalV2 isOpen={showUnits} onClose={()=>setShowUnits(false)}/><BedManagementModal isOpen={showBeds} onClose={()=>setShowBeds(false)}/></>}
 </div>;
};
