import React,{useState}from'react';
import {LockKeyhole,ShieldCheck}from'lucide-react';
import {CardioLogo}from'../CardioLogo';

export const OfflineUnlockScreen:React.FC<{identity?:string;onUnlock:(pin:string)=>Promise<boolean>}>=({identity,onUnlock})=>{
 const[pin,setPin]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!/^\\d{4,8}$/.test(pin)){setError('Enter the 4–8 digit CardioVault PIN.');return;}setBusy(true);const ok=await onUnlock(pin);setBusy(false);if(!ok){setPin('');setError('Incorrect PIN or the offline cache could not be unlocked.');}};
 return <div className="min-h-screen bg-[#070B13] text-white flex items-center justify-center p-5"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-[#0F172A] p-7 shadow-2xl text-center"><div className="mb-5"><CardioLogo size="xl" showText={false}/></div><LockKeyhole className="w-8 h-8 mx-auto text-cyan-400"/><h1 className="text-2xl font-extrabold mt-3">Offline Read-Only</h1><p className="text-sm text-slate-400 mt-2">Cloud connection is unavailable. Unlock the encrypted cache with your CardioVault PIN to view your previously authorized clinical data.</p>{identity&&<div className="mt-3 text-[11px] text-slate-500 break-all">{identity}</div>}<div className="mt-5 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-3 text-left text-xs text-amber-300"><ShieldCheck className="inline w-4 h-4 mr-1"/> Offline mode is read-only. No clinical changes are saved or uploaded while offline.</div><form onSubmit={submit} className="mt-5 space-y-3"><input autoFocus type="password" inputMode="numeric" autoComplete="off" maxLength={8} value={pin} onChange={e=>setPin(e.target.value.replace(/\\D/g,'').slice(0,8))} placeholder="PIN" className="w-full rounded-xl bg-slate-900 border border-slate-700 px-4 py-3 text-center tracking-[0.45em] text-lg outline-none focus:border-cyan-500"/>{error&&<p className="text-xs text-rose-400">{error}</p>}<button disabled={busy||pin.length<4} className="w-full py-3 rounded-xl bg-cyan-500 text-slate-950 font-bold disabled:opacity-50">{busy?'Unlocking…':'Unlock Offline Cache'}</button></form><p className="mt-4 text-[10px] text-slate-500">Reconnect to the internet to resume normal editing and cloud synchronization.</p></div></div>;
};
