import React,{useEffect,useState} from 'react';
import {KeyRound,ShieldCheck,ArrowRight,Loader2} from 'lucide-react';
import {redeemUnitAccessCode,getStoredWorkspaceAccess,isMasterAccount,ensureOwnerWorkspace} from '../../services/workspaceAccess';
import {CardioLogo} from '../CardioLogo';
import {useApp} from '../../context/AppContext';
import {Capacitor} from '@capacitor/core';

export const UnitAccessGate:React.FC=()=>{
 const{auth,logout,showToast}=useApp();
 const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[checking,setChecking]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{let active=true;let attempts=0;const check=async()=>{try{if(await isMasterAccount()){await ensureOwnerWorkspace();if(active)setChecking(false);return;}const access=getStoredWorkspaceAccess();if(access){if(active)setChecking(false);return;}}catch{}attempts+=1;if(attempts>=12&&active)setChecking(false);else window.setTimeout(()=>void check(),500);};void check();return()=>{active=false;};},[]);

 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const access=await redeemUnitAccessCode(code);showToast(`Access granted: ${access.unitName||'Unit'}`,'success');window.dispatchEvent(new CustomEvent('cardiovault-workspace-access-granted'));window.location.reload();}catch(err:any){const message=String(err?.message||'Access code could not be verified.');setError(message);showToast(message,'error');}finally{setBusy(false);}};
 return <div className="min-h-screen bg-[#070B13] flex items-center justify-center p-4 text-slate-100"><div className="w-full max-w-md bg-[#0F172A] border border-slate-800 rounded-3xl p-7 shadow-2xl text-center"><CardioLogo size="lg" showText={false}/><h1 className="text-2xl font-extrabold mt-4">Workspace Access</h1>{checking?<div className="mt-6 flex items-center justify-center gap-2 text-sm text-slate-400"><Loader2 className="w-4 h-4 animate-spin"/>Checking your CardioVault workspace…</div>:<><p className="text-xs text-slate-400 mt-2">This account is not assigned to a workspace. Enter the Unit Access Code provided by the workspace owner.</p><div className="mt-5 rounded-2xl border border-cyan-900/60 bg-cyan-950/20 p-4 text-left"><div className="flex items-center gap-2 text-cyan-300 text-xs font-bold"><ShieldCheck className="w-4 h-4"/> Unit-scoped access</div><p className="text-[11px] text-slate-400 mt-1">Only the unit attached to this code will be visible.</p></div><form onSubmit={submit} className="mt-5 space-y-3"><label className="block text-left text-xs font-semibold text-slate-300">Unit Access Code<input autoFocus value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="CV-XXXX-XXXX-XX" className="mt-1 w-full rounded-xl bg-slate-900 border border-slate-700 px-3 py-3 text-center tracking-[0.18em] font-mono text-sm outline-none focus:border-cyan-500"/></label>{error&&<p className="text-xs text-rose-400 text-left">{error}</p>}<button disabled={busy||code.trim().length<10} className="w-full py-3 rounded-xl bg-cyan-500 text-slate-950 font-bold text-sm disabled:opacity-50"><KeyRound className="inline w-4 h-4 mr-2"/>{busy?'Verifying…':'Access Unit'}<ArrowRight className="inline w-4 h-4 ml-2"/></button></form><button type="button" onClick={logout} className="mt-4 text-xs text-slate-500 hover:text-white">Sign out</button></>}</div></div>;
};
